### ISSUE TITLE
MMS - Cancelation Letter corrections

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#1]
Correction in sentence:
In addition to the above benefits, I feel strongly that the major benefit of being an AERA member is havingtoll-free access to our
-add space between having toll-free access

Correction in sentence:
 They are like havinga full time technical expert on staff but
-add space between having a

Correction in sentence:
The monthly payment plan isa simple credit card payment or direct withdrawal from your checking
-add space between is a

Thank you!

**Comment by SagarPC** [comment]
@kbt1 : We have done with this change and uploaded change on production. Please check once and let us know if any query.

**Comment by kbt1** [comment]
looks good. thank you
