### ISSUE TITLE
Report information doesn't match membership record

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#100]
I pulled a report from the export data tab in membership with the following selections:

![image](https://user-images.githubusercontent.com/26386841/57325946-eb051c80-70d0-11e9-913b-df5fada34a38.png)
![image](https://user-images.githubusercontent.com/26386841/57325984-007a4680-70d1-11e9-8cf3-085e453cdd43.png)

In the report member ID 625 shows 2 additional contacts both listed as Michael Sullivan

![image](https://user-images.githubusercontent.com/26386841/57326080-3e776a80-70d1-11e9-8ae6-1d104547f991.png)

However, when you go into Membership and look at ID 625 there are no Additional Contacts listed

![image](https://user-images.githubusercontent.com/26386841/57326175-7e3e5200-70d1-11e9-8c97-0b38de7af584.png)

Can you look into where the report is pulling the information from and fix it so it is pulling it correctly?

**Comment by stellaballa** [comment]
@aharmening  we will look into this. Can you post the report you downloaded as well.

**Comment by amandagoyette** [comment]
[Membership-05-07-2019 (4).xlsx](https://github.com/stellaballa/AERA/files/3154154/Membership-05-07-2019.4.xlsx)

**Comment by amandagoyette** [comment]
This may help, I'm not sure.  
Member #44280 doesn't have any additional contacts, but the report shows 
![image](https://user-images.githubusercontent.com/26386841/57327232-07568880-70d4-11e9-89b7-e299a43a00a4.png)

**Comment by SagarPC** [comment]
@aharmening  We fixed this issue on the live. Now it will only export available additional contacts.
