### ISSUE TITLE
MMS-Conferences Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#101]
1) I would like to add 1 more option to the dropdown. 
- Attendee
- Exhibitor
- Non Member Exhibitor
- Exhibitor - Literature Only

2) There is a bug with edit exhibitor name, it doesn’t save. It does work for attendees.

**Comment by SagarPC** [comment]
+++++++++++++++++++++
_1. I would like to add 1 more option to the dropdown._
+++++++++++++++++++++
We are working on this and it will be upload on stage by tomorrow.

+++++++++++++++++++++
_2.There is a bug with edit exhibitor name, it doesn’t save. It does work for attendees._
+++++++++++++++++++++
We looked into this issue and FirstName and Last Name updated successfull. I added "_" after FirstName and LastName to test on live. See below image and reverted my update after testing.
<img width="840" alt="mms_update_exhibitor_name" src="https://user-images.githubusercontent.com/31076567/58094937-74e3d800-7bef-11e9-9053-b57e141c689b.png">

**Comment by kbt1** [comment]
#2. Edit an exhibitor name - its for additional attendee names. If you look at ID#3061 and try to edit Larry Berger Jr, it wont save it.

**Comment by SagarPC** [comment]
@kbt1  Yes, got that. We will look and fix this as well.

**Comment by SagarPC** [comment]
@kbt1 
+++++++++++++++++++++
_1. I would like to add 1 more option to the dropdown._
+++++++++++++++++++++
We added new option as suggested. Also, added related things in Add/Edit/Export conference.

+++++++++++++++++++++
_2.There is a bug with edit exhibitor name, it doesn’t save. It does work for attendees._
+++++++++++++++++++++
We fixed this issue and now it's working on live.

**Comment by kbt1** [comment]
Works perfect!  Thank you!
