### ISSUE TITLE
Prosis Pro - Expiring Notification

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#102]
Stella
I have had 5 members contacting me this week stating they are getting messages about their Prosis Pro account is expiring however, they are on the monthly payment plan and should NOT get any notification. Can you look into this and make sure monthly payment users do not get notifications if this can be set up.
Thank you!

**Comment by stellaballa** [comment]
Hi @kbt1  we will look into this. Can you give us the account for these members? I think it might have to do with turning the notification off for monthly member, but I want to make sure there's nothing else with these specific member accounts.

**Comment by kbt1** [comment]
I didnt keep track of their member number.
I am including a list of members that are on the monthly payment plan so you have member #s you can check.
[Companies w monthly payment prosis.xlsx](https://github.com/stellaballa/AERA/files/3218276/Companies.w.monthly.payment.prosis.xlsx)

**Comment by SagarPC** [comment]
@kbt1 We fixed the issue and turning the notification off for monthly member.

**Comment by kbt1** [comment]
I will keep track of member numbers if I get any calls but this should take care of it.

Thank you!
