### ISSUE TITLE
TB1896 Printing

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#103]
When we go to print TB 1896, we are getting the following error message:

Application has generated error. We have logged this error and will look into it soon.
Please contact system administrator if needed.
Error Message: Invalid nested tag td found, expected closing tag div.
Error Reference Number: 10620198426325

Thank you,

**Comment by SagarPC** [comment]
@stevefox3781  I fixed this issue and now TB 1896 print is working.

**Comment by stevefox3781** [comment]
Working good!!! Thank you
