### ISSUE TITLE
Downloading TB's to a PDF File

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#104]
When we go to download a TB to a PDF file, the file it is wanting to save to is a ASPX file extension and not PDF. Is that something on our end or within the program? If you can look into this and let me know we would appreciate it. 

Thank you

**Comment by SagarPC** [comment]
@stevefox3781  Please give me one of the example TB# where I can check.

**Comment by stevefox3781** [comment]
They all seem to be doing it. You can use TB1896 for example. The print page opens up and when we click the "arrow" to download to to a PDF, that is when the other extension is coming up.

**Comment by SagarPC** [comment]
@stevefox3781  It should work now. I just updated code for that.

**Comment by stevefox3781** [comment]
Perfect - works great!!!

Thank you,
