### ISSUE TITLE
Repsonse Section Tech Queue

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#105]
Can we make in the response section of a tech call it so we can upload a .jpg file as well as a PDF? Sometimes we get the answer from a vendor (picture) in a .jpg format and need to add it to the call. Change the name to Upload File as well. 

![image](https://user-images.githubusercontent.com/26387391/59300923-01fdd800-8c56-11e9-9b85-959bdb619d67.png)

Thanks,

**Comment by stellaballa** [comment]
@stevefox3781  we will look into it.

**Comment by SagarPC** [comment]
@stevefox3781  We are working on this and we will move this change in live by Monday.

**Comment by SagarPC** [comment]
@stevefox3781  We uploaded this change in stage and live both. Please verify and confirm our update.

**Comment by stevefox3781** [comment]
Working great. Thank you Sagar for the quick work, we greatly appreciate it.
