### ISSUE TITLE
Dues Batch - Line Item Correction

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#106]
Can you make the following correction please:
Batch 6-13-19sf
ID#12236 should be ID#12326
Dates should be 7/1/2019-7/1/2020
Check
$399

![image](https://user-images.githubusercontent.com/26387044/59622787-26dfc880-90f8-11e9-9e52-71257e6aa967.png)

Thank you. let me know when done.
Karen

**Comment by stellaballa** [comment]
@kbt1  we will look into it.

**Comment by SagarPC** [comment]
@kbt1 We updated batch 6-13-19sf as requested. Please check and confirm our update.

**Comment by kbt1** [comment]
Perfect.
Thank you!
