### ISSUE TITLE
Creating Tech Call - Missing Info

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#107]
Created a tech call this morning for ID 33239 and the caller name did not come over from membership. Also when I went to email from the tech call, the email address did not show up in the TO box, I had to copy and paste. 

Tech Call
![image](https://user-images.githubusercontent.com/26387391/59685351-98278600-91a1-11e9-9d14-e89aa369ee4e.png)

Membership
![image](https://user-images.githubusercontent.com/26387391/59685396-af667380-91a1-11e9-8492-132dbb5d829b.png)

**Comment by stevefox3781** [comment]
Went into a call this morning that was taken yesterday and the phone and fax numbers are missing this morning. I think something weird is going on.

**Comment by stevefox3781** [comment]
The tech call came through as a spec request that was on the tab but did not get an email on it. Regarding the phone or fax, maybe they did not fill it out.

**Comment by stellaballa** [comment]
@SagarPC  please look into this.

**Comment by SagarPC** [comment]
@stevefox3781 I looked into this issue and notice something weird setup for this member. 

1) If we look into this member main information, there is Name and Phone number. No email address.
2) There is one unknown additional contact with email only.

We are showing information inside Tech Call as "Caller" 1st priority to the additional contact with Tech Department, 2nd other additional contacts, 3rd main contact. 

If we look into this case Tech Call behavior is correct as per the logic. 

There is no name in additional contact just email and as per the logic we are considering additional contacts detail where name is blank and email existed. (see image point:2)

If we select caller with the name "Wade Dunnaway" from the selection, there is no email. (see image point:1) 

![image](https://user-images.githubusercontent.com/31076567/59742087-72c27700-928a-11e9-8e2a-61c19a2717f1.png)

Please let me know if any chnage required in this logic.

**Comment by stevefox3781** [comment]
@SagarPC no changes are needed with the logic. It is working exactly like it should.  I moved the email address into the correct location in the membership record and it is working perfectly. Sorry for the extra work on a mistake on our end where it seems someone put the email address in the wrong location. 

Thank you for taking the time to look into this for us.

**Comment by stevefox3781** [comment]
@SagarPC @stellaballa  after talking to staff here, the only time that we should be pulling from the Additional Contact is if TECH is populated in the Department section for a tech call. Anything else, Accounting or N/A or just an email filled in should not pull to a tech call. It should pull the membership information when creating a tech call. 

I need to talk to some additional staff people about some procedures here and we might need to add a box to the membership record. I will keep Stella informed on this.
