### ISSUE TITLE
Prosis Pro - Shop Counter

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#11]
We have a member having issues with the Shop Counter.
Jake 
Sampson Racing #43196

When creating invoices, he will start to type in a box and all the suggestions start coming up and go off the screen, like too many are coming up.
He says it makes his program funky.
He uses Google Chrome.
Last week he had to get an invoice done and used IE and it worked ok but his printing doesn’t work good with IE?
I have no idea what to tell him, any suggestions?

**Comment by stellaballa** [comment]
Hi Karen,
Will look into this.
Stella

**Comment by kbt1** [comment]
thank you.
  **Members with login issues today:**
I have had about a dozen calls and emails from members saying they are already logged in.
Some are repeats from last week and I ask if they are sharing logins with several employees and they say no. Some admit they forget to "sign out" and just close the browser.
Most of the calls today are telling me after this weekend they are locked out and that could be if you did something over the weekend.
Is there a way if the member gets the message "You are already logged in" a button appears and they have to click on it and it resets their account like the button you have for me to reset their account?

**Comment by stellaballa** [comment]
Hi Karen,
We've done some update over the weekend hoping it would fix the logout issue, we will keep looking into it. 
Stella

**Comment by kbt1** [comment]
I will keep you posted if the calls continue this week.

**Comment by stellaballa** [comment]
@kbt1 We've done some update, it should fix the issue, please keep me posted.

**Comment by SagarPC** [comment]
@kbt1 / @stellaballa :
We are looking into  Shop Counter issue, for now we have removed code for the auto-fill dropdown. This issue occur only because that client having bunch of record to show in auto-fill. 

We can put limit like start auto fill down after 3 character type in text box. Please let us know your thoughts on this.

**Comment by kbt1** [comment]
I would think auto fill after 5 characters are typed in box. Let me see what Steve thinks.

**Comment by kbt1** [comment]
We agree auto fill after 3 characters.
Let me know when done and I will contact the member and have him try.

**Comment by SagarPC** [comment]
We have done with this change and uploaded on production. Also we have implemented custom code for the auto fill option. We have added scroll when we have too many data to show as suggestions. 

<img width="280" alt="suggestion" src="https://user-images.githubusercontent.com/31076567/30165818-0beb14b4-93ff-11e7-8ae9-a52ea2b3e1e6.png">

**Comment by kbt1** [comment]
I will have the member test it and let me know.
thank you

**Comment by kbt1** [comment]
Heard back from member that the change made is perfect.
