### ISSUE TITLE
Converting Call from Spec Request

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#111]
Have a call in the Specification Request that when we click on get an error message. I have a screen shot of the call and the error. We did do another spec request and it worked fine. 

![image](https://user-images.githubusercontent.com/26387391/60273363-9ce3ec80-98bb-11e9-8f9a-03e56d82279a.png)

![image](https://user-images.githubusercontent.com/26387391/60273382-aa00db80-98bb-11e9-99a1-8837ea00f574.png)

**Comment by SagarPC** [comment]
@stevefox3781  There issue with the expiry date. We fixed this issue and now it should work.

**Comment by stevefox3781** [comment]
Thank you!!
