### ISSUE TITLE
Alternate Contact's email doesn't appear in report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#112]
![image](https://user-images.githubusercontent.com/26386841/61403938-0001e700-a89c-11e9-9707-f47e01ee80bf.png)
When I do the sort I get this list. 
![image](https://user-images.githubusercontent.com/26386841/61404009-1f007900-a89c-11e9-869a-95865a9283ad.png)
The highlighted address above has a secondary email that's not listed:
![image](https://user-images.githubusercontent.com/26386841/61404072-3fc8ce80-a89c-11e9-983a-0feecdc24f40.png)
We need these listed in this report unless they are marked unsubscribed

**Comment by amandagoyette** [comment]
@stellaballa I don't see where this one is updated yet.

**Comment by stellaballa** [comment]
@aharmening  let me check, sometimes it might take some time for the data to update, but we will look into it.

**Comment by SagarPC** [comment]
@aharmening We are not exporting additional contact with "Email Blast Report" till today. We just updated logic and now exporting additional contact email under "Email Blast Report".

It will not be export don't publish or unsubscribed email. Please verify this update on stage.

**Comment by amandagoyette** [comment]
This looks good
