### ISSUE TITLE
Drop down on Additional contacts needs to be updated

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#113]
We had discussed that for the Department, there will be 3 options Tech, Accounting and Other.  Currently it's still N/A instead of Other
![image](https://user-images.githubusercontent.com/26386841/61404388-f9c03a80-a89c-11e9-890d-3f5c624990a3.png)

**Comment by SagarPC** [comment]
@aharmening  We added Other option for the Department as well. Please check and confirm our update.

**Comment by amandagoyette** [comment]
Perfect thanks!
