### ISSUE TITLE
Export Tab doesn't show unsubscribed

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#114]
When selecting criteria there's no option for the unsubscribed or unpublished.  I thought maybe it was in the report automatically when email is selected, which would work just fine, but I don't see it there either. I've included screen shots of my sort here:
![image](https://user-images.githubusercontent.com/26386841/61404808-e9f52600-a89d-11e9-909a-2ff4c9157dd1.png)
![image](https://user-images.githubusercontent.com/26386841/61404827-f7121500-a89d-11e9-971d-90476946f88e.png)

I checked this record in the report:
![image](https://user-images.githubusercontent.com/26386841/61404983-54a66180-a89e-11e9-8ddf-35f1b178dace.png)

No where in the exported excel file can I see that this one is unsubscribed or why.
[Membership-07-17-2019 (2).xlsx](https://github.com/stellaballa/AERA/files/3403473/Membership-07-17-2019.2.xlsx)

**Comment by SagarPC** [comment]
@aharmening  now we are exporting member and additional member email as a blank if unsubscribed with "Export Data" tab. Please check. 

If "Don't publish" is selected then all email main member email and additional email both will be exported as blank with other member detail.

Please let me know if there is any change required in this logic.

**Comment by amandagoyette** [comment]
@SagarPC we need it to pull that info, but have a column that reflects if they've opted for Don't Publish or Unsubscribed.  If it's unsubscribed there should also be a reason listed.  We should also show the title on the additional contacts.  I'm attaching an excel file with what we're hoping to see.  The columns in gray are the ones I've added.  
[Sample.xlsx](https://github.com/stellaballa/AERA/files/3411827/Sample.xlsx)

**Comment by SagarPC** [comment]
@aharmening We added an additional column in Export function as you suggested. Please verify our update and let us know if any change.

**Comment by amandagoyette** [comment]
this looks good by me thanks!  Sorry for the slow reply I was out of the office.
