### ISSUE TITLE
Printing TB2795

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#115]
When we go to print TB2795, we got the following error message. 

![image](https://user-images.githubusercontent.com/26387391/61539596-79671a00-aa01-11e9-877f-b8aa5eeb00d2.png)

**Comment by SagarPC** [comment]
@stevefox3781  Please check, now it should work. There is an issue with HTML content inside this TB.

**Comment by stevefox3781** [comment]
Works great!!! Thank you for the quick response.
