### ISSUE TITLE
AERA-Dues Processing

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#116]
After I create a batch to enter I go in and enter each payment for Membership and Prosis Pro.
Depending on when they pay, sometimes I need to adjust start date which you have as default of the date of entry. I can adjust Prosis Pro start date but when I adjust the Membership start date it somehow defaults back to the date of entry. This needs to be corrected.  All start dates Must be the first of a month. 
For an example see Dues Batch 8-6-19kt Date: 08/06/2019 By: Karen Tendering
I changed all dates from 8/6/19 to 8/1/19 and as soon as I print my report and post, it reverted back to 8/6/19.  In my screen shot below, see ID#44569. Start date was adjusted for both Membership and Prosis however, it reverted back for Membership.

![image](https://user-images.githubusercontent.com/26387044/62573219-2c859f00-b85b-11e9-8e7e-45818f3a0df9.png)

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look?

**Comment by kbt1** [comment]
can you make the system make the start date as follows:
if entering in dues on the 1st-15th of month make it the 1st of the current month
if entering in dues on the 16th-31st of month make it the 1st of the following month

example - enter dues 8/6/19, start date should = 8/1/19 and end date =8/1/20
enter dues 8/19/19, start date should = 9/1/19 and end date = 9/1/20

let me know if you have questions. this way i dont have to make any changes.

**Comment by SagarPC** [comment]
@kbt1 We looked into this issue and notice this issue with one special case. 

It's occur when user Join Date  is today's date and we are going to make entry in today on same date.

We fixed this issue in local and now it will consider 1st of this month for the Member and Prosis Pro user.

We also considered your below logic to implement this update. 
++++++++++++++
_if entering in dues on the 1st-15th of month make it the 1st of the current month
if entering in dues on the 16th-31st of month make it the 1st of the following month_
++++++++++++++

Currently we are doing tesing with this update and we will upload this change on live by tomorrow.

**Comment by kbt1** [comment]
Thank you.

**Comment by SagarPC** [comment]
@kbt1  We uploaded this change on stage and live both.

**Comment by kbt1** [comment]
fix works! thank you!
