### ISSUE TITLE
Liter Size Missing from Dropdown

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#118]
When we go to look up a Nissan 3.8L engine, the liter size of 3.8 is missing from the dropdown. If you look up the engine by the model, GT-R, the engine can be found. The 3.8 is missing from the dropdown in both the user version and CMS. 

![image](https://user-images.githubusercontent.com/26387391/63459759-c2542900-c41a-11e9-8435-47ccb3e6952a.png)

**Comment by stellaballa** [comment]
Thanks @stevefox3781, @SagarPC  can you please take a look?

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue and not it's showing correct data in the dropdown.

![image](https://user-images.githubusercontent.com/31076567/63593942-cc208c80-c5d2-11e9-81af-67f5efad8610.png)

**Comment by stevefox3781** [comment]
Working great!!!

Thank you
