### ISSUE TITLE
Dues Batch-Correction Needed

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#119]
can you please make the following correction to a posted transaction in a dues batch:
Closed Batch: 9-5-19kt Date: 09/05/2019 By: Karen Tendering

Line 11 should be  Type: MUS  Amount Due $559.00
everything else is correct.

![image](https://user-images.githubusercontent.com/26387044/64547163-ad6c0680-d2f1-11e9-81d5-3038daf6a105.png)

Thank you!

**Comment by stellaballa** [comment]
@kbt1  Will do

**Comment by SagarPC** [comment]
@kbt1  We update "SUS" with "MUS" for member id 24253 & Batch: 9-5-19kt.

**Comment by kbt1** [comment]
Can you also make Amount Due $559 insteaad of $459 - Thank you!
![image](https://user-images.githubusercontent.com/26387044/64615064-69cfd600-d39f-11e9-862e-918aa2f9b5ff.png)

**Comment by SagarPC** [comment]
@kbt1  We updated amount with $559.00

**Comment by kbt1** [comment]
perfect, thank you!
