### ISSUE TITLE
Prosis Pro - account over limit not correct.

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#12]
I am trying to help a member add a login under Member 1201 who is an Enterprise user.
![image](https://user-images.githubusercontent.com/26387044/30073102-36c8aa8a-9232-11e7-8c5a-8fe8d831516d.png)

They have 5 logins but yet, when i add a user, this is the error I get:
![image](https://user-images.githubusercontent.com/26387044/30073090-29cc0fe8-9232-11e7-8116-94166812eded.png)

**Comment by SagarPC** [comment]
We have looked into this and notice we need to update #Users with Account Type.  It should be 20 or less than 20 for Enterprise member. 

<img width="605" alt="user_count" src="https://user-images.githubusercontent.com/31076567/30114629-0b702ae8-9336-11e7-9e17-e72ecfff126a.png">

**Comment by kbt1** [comment]
I didnt even notice # Users box.
I will try and beleive once i update that, it will work.
thank you!
