### ISSUE TITLE
Monthly Reports - Mailing List

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#121]
It appears that anyone who is unsubscribed from emails is not appearing on the mailing list.  They should only be removed from the email list as we still need to be sending them member mailings.  Can we fix this? 
Examples of those missing off the Monthly report Mailing List:

Dwayne   Wolfe | 1085707 Alberta Ltd dba Perfect   Performance | PO Box 759 | La Crete | AB | T0H 2H0 | CANADA | AC
-- | -- | -- | -- | -- | -- | -- | --
Dennis Marson | 4x4 Shop Inc | 1210 Holman Ct | Caldwell | ID | 83605 | USA | AC
Marvin Turner | A+ Engine Rebuilders | PO Box 33394 | Reno | NV | 89533-3394 | USA | AC
Larry Smith | ABC Auto Parts Ltd | 201 S High St | Longview | TX | 75601 | USA | AC
David Mattison | Abrahams Machine Service Inc | PO Box 3986 | Davenport | IA | 52808-3986 | USA | AC
Ron Storer | ABS Products | 591 W Apollo St | Brea | CA | 92821 | USA | AS
Paul Nixon | Acme Auto Parts | 219 E Pecan St | Sherman | TX | 75090 | USA | AC
Ben Adams | Adams Automotive & Machine | 1100 N 5th St | Grand Forks | ND | 58203-2445 | USA | AC
Marc Fontaine | ADF Diesel Rive-Sud | 185 Paul-Gauguin | Candiac | PQ | J5R 0G7 | CANADA | AC

**Comment by SagarPC** [comment]
@aharmening We removed unsubscribed checked from the Mailing List report, now it's working as requested.
