### ISSUE TITLE
MMS-Monthly Report Bug

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#123]
MMS
Monthly Report
Under Monthly Call Reports I select the following:
Prosis Pro 30 days trial with Membership
date range of 9/15/2019-10/31/2019
this should pull all members that have a 30 day trial of Prosis Pro expiring in that date range so I can see if they want to subscribe.
The report comes up but all the address data is missing.
[MonthlyCallReport Sample.xlsx](https://github.com/stellaballa/AERA/files/3702576/MonthlyCallReport.Sample.xlsx)

Can you look into this please. All the other options work except for the Prosis Pro 30 day trial with Membership.

Thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 We looked into this issue and now extracting the address from the Mailing Address.

Please check and confirm our update.

**Comment by kbt1** [comment]
It looks good but it isnt pulling phone and/or fax.

**Comment by SagarPC** [comment]
@kbt1 Please check now we extracted phone and fax from the membership detail.

**Comment by kbt1** [comment]
perfect, thank you!
