### ISSUE TITLE
Prosis Pro Spec Request Converted to Call in Management System

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#124]
In our Management Software, when we convert a prosis pro spec request to a tech call the From field comes up as a phone. Can we get that changed to the email icon or maybe better yet a computer (unless you have a better idea). Trying to get a better idea where the call came from when looking at them and maybe if we saw a computer, we would konw that came from Prosis Pro. Just a thought.  

The top one in the example is a spec request from Prosis Pro and the bottom is a request that was emailed to us directly. 

![image](https://user-images.githubusercontent.com/26387391/67858152-84444700-fae6-11e9-9eb1-910adf992bc8.png)

Thanks,

**Comment by SagarPC** [comment]
@stevefox3781 Please see below image we updated logic to show computer icon if Origin is selected as "Prosis Pro Spec. Request". This change is uploaded on live

![image](https://user-images.githubusercontent.com/31076567/68115136-b22def00-ff1d-11e9-94f4-7e3411b2167f.png)

**Comment by stevefox3781** [comment]
That looks great!!

Steve Fox
AERA Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org<http://www.aera.org/>
