### ISSUE TITLE
AERA MMS Conference Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#126]
In MMS, under the Conference Tab, AERA VIP Party, the Attendees Registered count is incorrect:

![image](https://user-images.githubusercontent.com/26387044/68798771-9f51a380-061c-11ea-8ad1-0a57a455e3ec.png)

i refreshed my screen and exit and went back in and same results

The screen shows 81 but when I run the report, it is over 100 which is correct.
[AERA VIP Party Attendee List.xlsx](https://github.com/stellaballa/AERA/files/3843176/AERA.VIP.Party.Attendee.List.xlsx)

Please look into this.
Thank you!

**Comment by stellaballa** [comment]
@SagarPC  please look into this.

**Comment by kbt1** [comment]
FYI: its good in Chrome, its incorrect in IE.
is it an IE issue?

**Comment by stellaballa** [comment]
@kbt1  that's really strange, can you do a clear cache on the IE and see if the number gets updated?

**Comment by kbt1** [comment]
how do you clear cashe?
if i clear this, will it effect logins and passwords?

**Comment by stellaballa** [comment]
@kbt1  can you refresh the browser? If not let us look into it on IE, and you can keep working on Chrome.

**Comment by kbt1** [comment]
look into IE 
i refreshed and it doesnt update on IE

**Comment by SagarPC** [comment]
@kbt1 There is no issue with the code and logic. We are showing that statistic using Ajax request and IE cached the Ajax request and using previously cached data. If you reload screen using "Ctrl + F5" then it will show you the correct result in IE as well.

I suggest to use google chrome for the AERA MMS, Prosis Pro CMS and AERA Edu.

**Comment by kbt1** [comment]
Ctrl F5 works. thanks!
