### ISSUE TITLE
Ad Phone Number in Prosis Pro Header

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#127]
Some members have commented that there is no phone number listed to contact AERA if they are in Prosis Pro. Would it be possible to add the phone number in the top header as shown in the image? 

![image](https://user-images.githubusercontent.com/26387391/72816629-182d3700-3c2e-11ea-9fac-87f6fcf91ba9.png)

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  please update

**Comment by SagarPC** [comment]
@stevefox3781 We added contact info. as you requested and uploaded on live. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/72872185-b85c8c00-3d12-11ea-92b3-e7716891bba0.png)

**Comment by stevefox3781** [comment]
Looks great, thank you!
