### ISSUE TITLE
Dashboard Parts Suppliers

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#128]
We will be adding a new supplier to the Prosis Pro parts listing and I wanted to get them started on the Dashboard right away. I went and added them (ELGIN INDUSTRIES) in CMS (see image below) and refreshed my screen several times, logged out and back in but they never came up. Is there something that needs to be changed on the back end so that those change during a refresh? Also I would like them to display on the dashboard in a random order, not the same all the time. 

![image](https://user-images.githubusercontent.com/26387391/73197891-c423c600-40f7-11ea-972e-c66cd9fe3da6.png)

Any questions, let me know. 

Steve

**Comment by stellaballa** [comment]
@SagarPC  can you check to see why the logo is not showing up?

**Comment by SagarPC** [comment]
@stellaballa We have a function to show only 3 top logos on the dashboard. This is fix logic.

Please let me know if any change required in this logic.

**Comment by stellaballa** [comment]
@SagarPC  Yes we would like to only show 3 logos at a time, but if there are more then 3 logos, the logos will rotate, when member refreshes the browser it will load the other logos.

**Comment by stellaballa** [comment]
@stevefox3781  just talked to Sagar about this. It turns out the function for random logo loading hasn't been built yet. I think we decided not to build it until we have more than 3 logos.  Sagar will be working on this, it will be done by end of the week.

**Comment by stevefox3781** [comment]
Ok sounds good. Thank you!

Steve Fox
AERA Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372

**Comment by SagarPC** [comment]
@stevefox3781 It's upload on live and now we are showing banner in random order on dashboard for each request.

**Comment by stevefox3781** [comment]
Everything is working great!

Thank you
