### ISSUE TITLE
NOTICE BANNER

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#129]
I was going to put a notice out there that we would be doing server maintenance beginning Friday night at midnight and should be completed by 8am on Saturday Feb 1. I typed that all in on CMS, and went to prosis pro and it is not there. It used to be in a Yellow banner across the top of the page in the old one. Wondering if it got lost when we did the latest update. 

If someone can look into it and add the notice for me, that would be great. 

Thank you

**Comment by stellaballa** [comment]
Thanks @stevefox3781  we will look into it.
@SagarPC  can you please take a look and make sure the banner is on the website?

**Comment by SagarPC** [comment]
@stevefox3781  It's already there and I added test notification to verify. It's also showing on customer login. Please refer below admin URL to add notification .

https://www.prosispro.com/admin/Managenotice.aspx

![notice-add-update](https://user-images.githubusercontent.com/31076567/73420586-fbd57c80-4348-11ea-9b14-f5c42780ea09.png)

**Comment by SagarPC** [comment]
We added message from our end.

![notice-on-user-login](https://user-images.githubusercontent.com/31076567/73421451-e746b380-434b-11ea-9437-af8d6eb22d56.png)

**Comment by stevefox3781** [comment]
Thank you, sorry for the extra work.
