### ISSUE TITLE
Pixel Banner Report CMS

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#130]
Would it be possible to make a check boxes of the companies that I would like to pull reports for? Some want them and some do not and when I pull the report currently, I get everyone. Would just make is easier. 

![image](https://user-images.githubusercontent.com/26387391/73669818-bcbb6a00-466d-11ea-8bb5-c18829a6125a.png)

Any questions, let me know. 

Thanks,

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look and let me know the level of effort?

**Comment by stellaballa** [comment]
@stevefox3781  talked to Sagar about this, we will build this out as part of the monthly maintenance.

**Comment by stevefox3781** [comment]
Sounds good thank you!

Steve Fox
AERA Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372

**Comment by SagarPC** [comment]
We started work on this and it will be upload on live before end of this week.

**Comment by stevefox3781** [comment]
Thank you for the update.

**Comment by SagarPC** [comment]
@stevefox3781 & @stellaballa  We have a total of 2471 companies listed under AERA. If we show all companies checkbox then the checkbox list will be huge ( [aera-company-list.xlsx](https://github.com/stellaballa/AERA/files/4189955/aera-company-list.xlsx) ). 

What I am thinking is, we will show the list of companies after selecting "From Data" and "To Date". It will reduce number of companies count and show only those companies which going to export in the report.

Please let me know if it will work for you.

Regards,

**Comment by stevefox3781** [comment]
The pixel banner section is for the parts suppliers only, not all the Prosis Pro users. I have included a report for reference. Currently there should only be 3 options to choose from - Elgin,  Maxiforce and Reliance. Hope this makes sense and if you have any questions, let me know. 

[Tracking-02-12-2020.xlsx](https://github.com/stellaballa/AERA/files/4192576/Tracking-02-12-2020.xlsx)

**Comment by SagarPC** [comment]
@stevefox3781  I am clear now. We need to provide Sponser not a Company selection.

**Comment by stevefox3781** [comment]
Correct

**Comment by SagarPC** [comment]
@stevefox3781 We are done with this change and uploaded on live.

![image](https://user-images.githubusercontent.com/31076567/74435703-194b3000-4e8b-11ea-928e-5205fc5966b7.png)

**Comment by stevefox3781** [comment]
Looks to be working great. 

Thank you!
