### ISSUE TITLE
Dashboard Suppliers

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#131]
One of our suppliers decided to quit advertising so I removed them from CMS but they are still showing up. I have circled the one in red that needs to be removed. 

![image](https://user-images.githubusercontent.com/26387391/74043390-e8e92a80-498e-11ea-88ca-b39534c33c68.png)

![image](https://user-images.githubusercontent.com/26387391/74043348-d53dc400-498e-11ea-8476-2f4e626cad89.png)
 
Thank you,

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look

**Comment by SagarPC** [comment]
I will look and update you asap.

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue on live and stage both.

**Comment by stevefox3781** [comment]
Great thank you! Working good.
