### ISSUE TITLE
Prosis Pro and Firefox - Password Reset

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#133]
Stella
I have spoken to a few members that use Fire Fox and when they are notified to change their password, they change it but it never accepts it and just keeps asking them to change the password.
my solution for them until this is fixed is to use Google Chrome.
Anything you can do? I know the guys have spoken to members having the same issues.

**Comment by stellaballa** [comment]
@kbt1  we will look into the FireFox issue.

**Comment by SagarPC** [comment]
@stellaballa I checked with the FireFox version 73.0.1 and it's working fine for us. 

Please provide client FireFiox version and name of that client so we can check with that specific client.

**Comment by stellaballa** [comment]
@kbt1  can you give us more info on the Firefox version of this member?

**Comment by kbt1** [comment]
Unfortunately i dont have more details so when this happens, i will find out what version of Firefox they are on and give you their login info. 
Thanks!
