### ISSUE TITLE
Online Training Reset Feature 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#134]
The user name reset doesnt work anymore.
![User Reset Login](https://user-images.githubusercontent.com/26387044/75719470-6a845d80-5c9a-11ea-8775-a6fe384a3901.png)

I try to login and the cursor just spins. 

 I have 4 students that were logged in Feb 27th and they cant get logged in today.
The following 4 user names need to be reset asap, they are with a school doing this in class and trying to take the midterm exam:
KWKILGORE
NMQUALE
PASONNEN
EAGUILAR
 
Thank you

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@kbt1  Please try now, I addressed this issue.

**Comment by kbt1** [comment]
works now. thank you!
