### ISSUE TITLE
New Feature: Student Report in Online Training

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#135]
I reviewed this and pulled the report for a couple Groups.
Everything looks good except, it only show the Cylinder Head and Machinist Test

This report needs to show each chapter score and the 2 exams.
Also, can you make the column header read: Cylinder Head Exam not cylinder and Engine Machinist Exam not mechinist and the Chapter Headings should be Ch 1, Ch 2, etc.

this is the report i pulled.
[StudentReportSample.xlsx](https://github.com/stellaballa/AERA/files/4283043/StudentReportSample.xlsx)

This is how I would like to see it:
[StudentReportKaren.xlsx](https://github.com/stellaballa/AERA/files/4283063/StudentReportKaren.xlsx)

I thought this is how it showed in the sample you sent me.

**Comment by kbt1** [comment]
this is the sample report you sent that i thought it would look like, i couldnt find this earlier
[Studentmarksheetreport_132276432069572635_.xlsx](https://github.com/stellaballa/AERA/files/4283881/Studentmarksheetreport_132276432069572635_.xlsx)

**Comment by stellaballa** [comment]
@kbt1  this is a different report from our previous conversation. The report we posted that got approved was this one. 
https://github.com/stellaballa/AERA/issues/132
[group-leader-report.xlsx](https://github.com/stellaballa/AERA/files/4283931/group-leader-report.xlsx)

And in your comment, you said that was the correct report. Did we miss something?

**Comment by kbt1** [comment]
the report you provided above is correct. the report i pull in the database is not correct.
you had said the new report was live and when i log in under my login information or an instructor, that is not the report that is pulled.

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look at the report, maybe it's pulling the wrong data.

**Comment by SagarPC** [comment]
@kbt1 

**1) Admin Login:**
http://aeraedu.com/#/login
UserName: karen
Password: 5jiVsFo
![image](https://user-images.githubusercontent.com/31076567/75948698-237caf00-5eca-11ea-8daf-8fa207325104.png)

Report: [Studentreport_132278569395214017_.xlsx](https://github.com/stellaballa/AERA/files/4291013/Studentreport_132278569395214017_.xlsx)

We did not make any change in this report and export function for the Admin.

**2) AERA Group Leader / Teacher Login:** 
http://aeraedu.com/#/login
UserName: vposeyins
Password: BC2020
![image](https://user-images.githubusercontent.com/31076567/75949233-963a5a00-5ecb-11ea-9e13-a184e4785bfd.png)

Report: [Studentmarksheetreport_132278576241890393_.xlsx](https://github.com/stellaballa/AERA/files/4291042/Studentmarksheetreport_132278576241890393_.xlsx)

We implemented this report only for the AERA  Group Leader / Teacher Login as per the requirement.

We did not make any change for the SAM TECH User and Group Leader / Teacher Login.

Please let us know if any questions or changes required in this.

**Comment by kbt1** [comment]
I logged in as
 **UserName: vposeyins
Password: BC2020**
this is the report it pulls, it isnt like the sample you have attached above.
[Student Report Karen Gets when logged in as Vic Posey Instructor.xlsx](https://github.com/stellaballa/AERA/files/4293278/Student.Report.Karen.Gets.when.logged.in.as.Vic.Posey.Instructor.xlsx)

**Comment by SagarPC** [comment]
@kbt1 Please log in now and reload screen using the "Ctrl + F5" button. Your browser might have a cache and it's still showing you old report. 

Please try again and let me know what report comes us.

**Comment by kbt1** [comment]
That is perfect! Thank you!
