### ISSUE TITLE
Prosis Pro Account - Desktop Download Heading

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#136]
Can we change the second Prosis Pro Account Settings title in the picture below to PROSIS PRO Desktop Installation? We have members who are on the web thinking that they are updating there web program and are downloading the desktop. Also can we add - "If you are using the web version, you don't have to download the desktop version" or something similar. Trying to keep guys that are using the web only from downloading the desktop unless they absolutely need it. 

Any questions, let me know. 

![image](https://user-images.githubusercontent.com/26387391/75986547-e3aacd00-5eb3-11ea-9b39-985e6ed1f667.png)

**Comment by stellaballa** [comment]
@SagarPC, please update

**Comment by SagarPC** [comment]
@stevefox3781 We updated text for the English version. Please provide the same content for Spanish, French, Dutch, Danish, German, Italian, Swedish, Portuguese languages 

![image](https://user-images.githubusercontent.com/31076567/76139089-19e27b00-6073-11ea-8ec9-ea8e4bc3ca50.png)

**Comment by stevefox3781** [comment]
Can we change the top heading back to what it was - PROSIS PRO Account Settings and leave the second heading the way it its?

**Comment by SagarPC** [comment]
@stevefox3781  Please see below image, is it ok?

![image](https://user-images.githubusercontent.com/31076567/76221072-7f369780-623e-11ea-9276-cbe049f66249.png)

**Comment by stevefox3781** [comment]
Perfect!

Steve Fox
AERA Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org

**Comment by SagarPC** [comment]
Ok, updated same on live.

**Comment by stevefox3781** [comment]
Great thank you!

Steve Fox
AERA Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org
