### ISSUE TITLE
Prosis Pro Advanced Searches

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#137]
We are using the Advanced Searches and they do not seem to be working correctly as we are not getting any search results when we search. The first example is of the Bore Size search. I tried searching 3.500 and got back no results. The engine searched is Allis Chalmers D14 with that bore size. 

![image](https://user-images.githubusercontent.com/26387391/77598190-266a2e80-6ecf-11ea-9242-ce9ffbdfe2e9.png)

![image](https://user-images.githubusercontent.com/26387391/77598214-384bd180-6ecf-11ea-91d9-9c0279d474e3.png)

The following example is of the Rod Search - Big End Diameter. Used the same engine with a size of 2.0615 and get no results. 

![image](https://user-images.githubusercontent.com/26387391/77598377-a1334980-6ecf-11ea-96ca-c1d160783e30.png)

![image](https://user-images.githubusercontent.com/26387391/77598402-b7410a00-6ecf-11ea-9f66-26d152d51567.png)

Any questions, please let me know.

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue.

![image](https://user-images.githubusercontent.com/31076567/77917563-57c07100-72b8-11ea-9245-0132234a67a3.png)

**Comment by stevefox3781** [comment]
Seems to be working good. 

Thank you!!
