### ISSUE TITLE
Shop Tools Engine Calculator

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#138]
I believe we may have lost part of the formula for the the calculator. When you enter a gasket thickness on the first calculation, it seems to work. If you change it, the calculation does not change. I have included a screen shot of what was done and then changed it and no change. 

![image](https://user-images.githubusercontent.com/26387391/77598794-c1afd380-6ed0-11ea-97f1-a46db23ed0bb.png)

![image](https://user-images.githubusercontent.com/26387391/77598830-da1fee00-6ed0-11ea-8832-b6e3120ed494.png)

Any questions, let me know.

**Comment by stellaballa** [comment]
@SagarPC can you please take a look?

**Comment by SagarPC** [comment]
We checked calculation and it seems working fine.

In the above example "Gasket Thickness" is "0" and if "Gasket Bore Diameter" is in multiplication with "Gasket Thickness". If we multiply anything with 0 then it's remain 0, so it's not affecting anything in the calculation. 

Please add "Gasket Thickness" and  "Gasket Bore Diameter" both, it will change the calculation.

Please let me know if any questions.

Regards,

**Comment by stevefox3781** [comment]
Well I guess non of us here now how or own system works - LOL!!!

Thank you I will pass the information along and sorry for the time spent researching this.
