### ISSUE TITLE
Casting Search

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#139]
All of us have tried searching for a casting number in Prosis Pro and does not seem to be working. The number I used was 3970010 which is listed in Prosis Pro under Chevrolet Caprice 1977-82 VIN L 5.7L 350 CID engine. I have tried all options (Contains, Exact, Begins With etc) and no results come back.  Can you please look into this and see what the issue is? Any questions please let me know.

**Comment by stellaballa** [comment]
@stevefox3781  we will take a look.

**Comment by SagarPC** [comment]
@stevefox3781 We addressed this issue and uploaded on live. Please see below image for reference.

![image](https://user-images.githubusercontent.com/31076567/78037150-c8cf5980-7388-11ea-83d0-e3382fe9bf1f.png)
