### ISSUE TITLE
MMS - additional contacts

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#14]
we have some outdated additional contacts in membership records and when I delete the information out of each field and click on save, it doesnt delete it.
Can you make it so we can delete additional contacts from membership records.

**Comment by stellaballa** [comment]
@SagarPC please look into this.

**Comment by SagarPC** [comment]
now additional contacts will be deleted with remove all field related to additional contact.

![image](https://user-images.githubusercontent.com/31076567/30239634-d0a2321c-957e-11e7-9732-f0dcbb377d02.png)

**Comment by kbt1** [comment]
works good.
