### ISSUE TITLE
Duplicating Tech Calls

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#140]
Every once in a while, we get a tech call that is duplicated when creating a new call. The call comes in, the member ID is entered, saved and then we see something similar to what is highlighted below. Can someone please look into why this is happening. 

![image](https://user-images.githubusercontent.com/26387391/78709956-23f9d280-78da-11ea-83be-a0a398c6b00f.png)

Thank you!

**Comment by stellaballa** [comment]
@stevefox3781  we will look into this.
@SagarPC

**Comment by SagarPC** [comment]
@stevefox3781  We looked into this issue and not found any straightforward issue with this. This issue occurs because of simultaneous click on Save button during create Tech Call.

We will add a check to prevent simultaneous on Save butting in create tech call and upload.

**Comment by SagarPC** [comment]
@stevefox3781  We fixed and added a check to prevent duplicate insert on double click.

**Comment by stevefox3781** [comment]
Great thank you. Appreciate all your time on this. 

Take care and be safe!
