### ISSUE TITLE
Editing Overview In CMS. 

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#142]
The valves per cylinder specification seems to be disappearing in the overview when you go back in to edit an engine. You edit, save and the spec is missing sometimes. The value needs to be reentered again when it should stay.

**Comment by stellaballa** [comment]
@SagarPC  check the screen shot with this engine spec. When you click edit, the cylinder is empty, but in preview, it says 4. If you click save, it would remove the 4 from the spec. 
<img width="1031" alt="Screen Shot 2020-05-07 at 11 21 21 AM" src="https://user-images.githubusercontent.com/30122790/81338966-51b17300-9062-11ea-942d-172bbfca2adf.png">

**Comment by SagarPC** [comment]
@stevefox3781 We looked into this issue and fixed on live. Please check and confirm our update.

Regards,

**Comment by stevefox3781** [comment]
Looks to be working correctly. Thank you for getting that fixed for us.
