### ISSUE TITLE
Prosis Pro CMS Export Report

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#145]
We went to export a report for in the Cylinder Block section for Main Cap Torque & Additional Main Cap Bolts, it seems to be pulling a spec from the Main to Cam Bore Distance for the Additional Main Cap Bolts. The AMCB spec should be a torque spec like the Main Cap Torque. I have included a screen shot of the report. 

![image](https://user-images.githubusercontent.com/26387391/83659090-b3dd9500-a588-11ea-82fa-942c1f492a34.png)

Any questions, let me know. 

Thanks, 
Steve

**Comment by stellaballa** [comment]
@SagarPC  can you please look into this.

**Comment by SagarPC** [comment]
@stevefox3781  We looked and fixed this issue on live. Please export data again and confirm our changes on live.

Regards,

**Comment by stevefox3781** [comment]
@SagarPC seems to be working great. 

Thank you!!!
