### ISSUE TITLE
Correction for Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#147]
Can you please fix the following transaction.
6-23-2020 Monthly ACH BatchDate: 06/29/2020By: Karen Tendering
first entry ID#37772 Should be ID#34472  everything else is correct.
![image](https://user-images.githubusercontent.com/26387044/86038768-1484b400-ba07-11ea-9724-a452c8650bbe.png)

let me know when done.

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@kbt1 We update membership number as you suggested.
