### ISSUE TITLE
Correction for a Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#148]
I just found this error. Can you please correct 2 issues with the following Dues Batch Name:  7/87/2020SFDate: 07/07/2020By: Steve Fox

![image](https://user-images.githubusercontent.com/26387044/88223300-d60c9e80-cc2c-11ea-8c63-bd9bb5eea706.png)

should be 7/7/2020SF not 7/87/2020SF

![image](https://user-images.githubusercontent.com/26387044/88224111-20424f80-cc2e-11ea-8122-0ba1fcfb9e4f.png)
the 3rd transaction for ID#13761 for $459 should be for Prosis not membership

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  can you please update.

**Comment by SagarPC** [comment]
@kbt1 We are done with the update. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/88286654-b483e380-cd0e-11ea-8673-048a8fb67d85.png)

**Comment by kbt1** [comment]
Perfect, thank you!
