### ISSUE TITLE
ADVANCE SEARCH FUNCTION - CYLINDER HEAD - FREE LENGTH

### ISSUE THREAD

**Issue by Dphagen** [stellaballa/AERA#149]
First off, it should state **Outer Spring Free Length**. I went to John Deere and I searched a simple 2.00, as it doesn't give " or Metric option like before. So, results showed this (1.2598" (32.000 MM) MIN). Well I was thinking, inches, but it pull anything that showed 2.00 which is searching all numbers Imperial and Metric. So the question is can we add the Inches/MM option we have now? 
  
![Capture inches-mm](https://user-images.githubusercontent.com/26655532/88428582-c8851f00-cdba-11ea-842f-0b276674902a.JPG)

Dave****

**Comment by stevefox3781** [comment]
Moved to Prosis Pro Update
