### ISSUE TITLE
Tech Call Report

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#15]
I have included a report of tech calls and included a screen shot of what attributes I selected for the report. In the excel file I have gone through and highlighted the doubles in the report, which I really don’t want to change this part of the report as I like the information we get after looking at it in more detail. 

In doing some thinking about this the last couple of days, I am thinking we add another section under the Export Data tab calling it “Call Reports”. In that section, we would have the ability to select a date range for closed callsonly and run the report. The output would give us the number of calls for the month, kind of like how Karen gets her monthly totals for Membership & PROSIS PRO. Also in that section, we take the names of the techs like we have in the screen shot attached and we can select the tech and a date range that would output the number of calls they closed during the month. We would not need any of the details that are in the attached excel file, just numbers. 

Hopefully I have not confused you on this and all makes sense. Any questions, let me know. 

![tech call report screen](https://user-images.githubusercontent.com/26387391/30280541-a2b49e00-96d5-11e7-853d-b6d323ae9a84.jpg)

[July Tech Call Report.xlsx](https://github.com/stellaballa/AERA/files/1292909/July.Tech.Call.Report.xlsx)

**Comment by stellaballa** [comment]
@stevefox3781 your explanation is clear, I will discuss this with Sagar to make sure he understands the requirements.

**Comment by SagarPC** [comment]
@stellaballa : We have uploaded close call report on stage, can you please check and confirm.

http://71.13.159.202/aeramms_stage/techcallqueuelist.aspx
UserName: SF
Password: test123

![image](https://user-images.githubusercontent.com/31076567/30337677-b4441628-9806-11e7-83ac-2d5aac369db5.png)

**Comment by stevefox3781** [comment]
It seems to be working correctly, but when I put in a range of 7/1/2017-7/31/20107, it comes back with the following error - see screen shot. 

![image](https://user-images.githubusercontent.com/26387391/30343059-a4e22250-97c1-11e7-9599-79ee68bddfad.png)

**Comment by SagarPC** [comment]
@stevefox3781 : It's only because of there is no closed tech call on stage. We have uploaded same on report on production please verify on production.

http://71.13.159.202/aeramms/techcallqueuelist.aspx

**Comment by stevefox3781** [comment]
That makes sense. - LOL, sorry for the confusion on that. 

All is good.
