### ISSUE TITLE
Correction for a Dues Batch in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#150]
Can you please make the following correction in this dues batch:
7-14-2020 Monthly CC BatchDate: 07/14/2020By: Karen Tendering
ID#42731  should be for Prosis

![image](https://user-images.githubusercontent.com/26387044/89312091-73f46600-d63c-11ea-8bc6-c055720b66a7.png)

Thank you very much!

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@kbt1 We updated with Prosis Pro. Please see below image.

![image](https://user-images.githubusercontent.com/31076567/89401603-26a6f000-d733-11ea-9031-55bb2c541078.png)

**Comment by kbt1** [comment]
the 2 dates need to be corrected and then this is good.
Start date = 08/01/2020 and new expiration date= 09/01/2020

**Comment by SagarPC** [comment]
updated start and exp. date. Please see below image for the reference.

![image](https://user-images.githubusercontent.com/31076567/89419669-421ff400-d74f-11ea-8aff-063f75c9398c.png)

**Comment by kbt1** [comment]
Good to go.
Thank you!
