### ISSUE TITLE
Monthly Report - Active Member Locator

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#151]
I just noticed, when I run the Active Member Locator Report under Monthly Report Tab in MMS, most records are missing the **Category Code**.
Can you correct this please.
See sample
[Sample report- Missing category codes.xlsx](https://github.com/stellaballa/AERA/files/5029284/Sample.report-.Missing.category.codes.xlsx)

**Comment by stellaballa** [comment]
@SagarPC  please look into it.

**Comment by SagarPC** [comment]
@kbt1 We fixed this issue and now it's exporting all category code.

[ActiveMemberReport-Website-8802.xlsx](https://github.com/stellaballa/AERA/files/5033417/ActiveMemberReport-Website-8802.xlsx)

**Comment by kbt1** [comment]
thank you. looks good.
