### ISSUE TITLE
AERA MMS

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#152]
@SagarPC  can you make the web address link to the site? Open a new window. 

![image001 png@01D66B38 6A10E100](https://user-images.githubusercontent.com/30122790/89458991-d0c74d80-d71c-11ea-97c2-a01df94ac0c4.png)

**Comment by SagarPC** [comment]
@stellaballa We are updated code and now website is showing as link and open in new tab when user click on that.

![image](https://user-images.githubusercontent.com/31076567/89507957-d8edbe80-d7ea-11ea-8844-63434912a9ab.png)

**Comment by stevefox3781** [comment]
Works perfect! Thank you for getting this done so quickly.
