### ISSUE TITLE
MMS-Dues Batch Needs Fixed

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#155]
I accidentally entered the wrong dates on this dues import batch.
**It should be start date 9/1/2020 end date 10/1/2020.** 
can you update all the dates. I would appreciate it.

batch 8-25-2020kt Monthly ACH BatchDate: 08/25/2020By: Karen Tendering
![image](https://user-images.githubusercontent.com/26387044/91188556-0aa1c900-e6b7-11ea-801d-fa448b6d75c7.png)

let me know when fixed.  Thank you!

**Comment by stellaballa** [comment]
@SagarPC  please update.

**Comment by kbt1** [comment]
I forgot to mention. The dates need to be corrected in the dues batch, but the dates in MMS records need to be corrected also.
Would it be easier to delete this batch and I will redo with correct dates?
Let me know.

**Comment by SagarPC** [comment]
We updated start date and exp. date as requested. Please see below image for reference.

![image](https://user-images.githubusercontent.com/31076567/91299969-1d53f500-e7c0-11ea-9796-10f93ebbe69d.png)

**Comment by kbt1** [comment]
All the records in MMS dates need to be updated also.
Start 9/1/2020 and Exp 10/1/2020

![image](https://user-images.githubusercontent.com/26387044/91305905-6466c980-e771-11ea-8f80-9b2f59b84a2d.png)

**Comment by SagarPC** [comment]
Prosis Pro and Membership both which exist in "8-25-2020kt Monthly ACH Batch" batch, correct?

**Comment by kbt1** [comment]
The dues batch dates are correct with your changes.
Now the all the dates in MMS each member record need to be updated.
When you post the batch, it automatically updates all the records but since this has already been posted, all the dates have to be updated.

**Comment by kbt1** [comment]
unless there is a way for you to UNPOST the batch and then i can post it and it will correct all the dates.

**Comment by SagarPC** [comment]
Updated MMS record with new date. Please check!

**Comment by kbt1** [comment]
Perfect. Thank you very much!
