### ISSUE TITLE
Dues Batch Correction Needed

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#156]
In dues Batch 8-10-2020kt Monthly Credit Card BatchDate: 08/10/2020By: Karen Tendering
can you change ID#44652 to ID#44655 for both records.

![image](https://user-images.githubusercontent.com/26387044/91881393-0b060b00-ec47-11ea-9ad2-f88a712c4f25.png)

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look.

**Comment by SagarPC** [comment]
@kbt1 Updated record as you requested.

![image](https://user-images.githubusercontent.com/31076567/91971182-68c55080-ed36-11ea-939b-83b1e724e53c.png)

**Comment by kbt1** [comment]
good to go. thank you!
