### ISSUE TITLE
MMS - Email Invoice and EP Subscription Glitch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#157]
This morning I emailed a batch of invoices in MMS for Nov 1.
At the same time, Amanda was emailing an EP subscriber about their subscription.
If you look at the email below, it looks like our emails crossed and somehow my email and her subscription reminder email went to this member.
The member and EP subscriber are not with the same company or linked in any way.
I don’t know who else this affected, this is the only member that contacted me about it. Hopefully this is the only member it affected. Looks like Amanda and I emailed at the same time and this might have happened.
 
Can you please look into this.

[Glitch sample.pdf](https://github.com/stellaballa/AERA/files/5226421/Glitch.sample.pdf)

**Comment by stellaballa** [comment]
@SagarPC  can you please look into this.

**Comment by SagarPC** [comment]
We are looking into this and will send an update on this asap.

**Comment by SagarPC** [comment]
@kbt1  We are not able to reproduce this issue but we separate out code for all email function on Membership page and now it should not conflict in any case.

**Comment by kbt1** [comment]
I think that should help. I believe Amanda and I just happened to emailing at the same time.
So hopefully with the new code, if her and I are emailing at the same time, it wont happen again.
She emails out of the EP tab and I email in the MMS tab.

Thank you!
