### ISSUE TITLE
Ability to add more pictures under a certain casting number

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#158]
We would like have the ability to add up to 5 pictures per casting number. We may not use all 5 but would like to have that option.

**Comment by stellaballa** [comment]
@SagarPC  can we update this function?

**Comment by SagarPC** [comment]
@stellaballa  We are working on this and it will be completed in this week.

**Comment by SagarPC** [comment]
This we completed and uploaded on stage. It's working fine for us on the stage website. Please let us know if we can move it to live.

**Comment by stevefox3781** [comment]
@SagarPC yes please do!

**Comment by SagarPC** [comment]
@stevefox3781  We added a function to add multiple images for the casting number and also shown images in Gallery view on click. Please see the below image for reference for that.

1) Click on Browse button
![image](https://user-images.githubusercontent.com/31076567/97569518-49346680-1a0d-11eb-9c91-31038304764d.png)

2) Select multiple images that you want to upload.
![image](https://user-images.githubusercontent.com/31076567/97572962-0c696f00-1a0f-11eb-883f-a768f96ee6e3.png)

3) Click on Open and Save the casting number.

4) You can remove a specific image by editing the casting number add new images in the same way as explained in step 23.
![image](https://user-images.githubusercontent.com/31076567/97573164-59e5dc00-1a0f-11eb-9e87-6058f840c741.png)
