### ISSUE TITLE
Slidebars Missing From Compression Calucator

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#159]
The slide bars seem to be missing from the Amount to Mill off Head and Piston Speed. There used to be a slide bar you could grab and move, but it is missing. 

![image](https://user-images.githubusercontent.com/26387391/94184623-cba79480-fe69-11ea-9335-8f948b86f2ae.png)

**Comment by stellaballa** [comment]
@SagarPC  please take a look

**Comment by SagarPC** [comment]
@stevefox3781 We fixed this issue on stage and live both. Please see the below image for reference.

![Screenshot](https://user-images.githubusercontent.com/31076567/95088741-f4207000-0740-11eb-8fcb-648b95a8ffa8.png)

**Comment by stevefox3781** [comment]
Great thank you!!
