### ISSUE TITLE
Custom Engine Casting Numbers

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#16]
A member called us asking about adding casting numbers to a Custom Engine that they have created. It appears that there is no option for this that they or us can find. Can we add the box in the screen shot below to the Custom Engine option? 

![image](https://user-images.githubusercontent.com/26387391/30381168-40df028c-9861-11e7-935a-8a6a780ab7d4.png)

**Comment by SagarPC** [comment]
We have done with this change and uploaded on stage and production.
