### ISSUE TITLE
Technical Bulleting Printing Issues - Urgent Please

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#160]
I updated our TB2451 in CMS as the alignment on the chart was all messed up. After uploading and going to print from the user side, the chart is missing from the printed version. Here is a screen shot of both. Can you please look into this and fix as soon as possible. I am not sure what happened. 

![image](https://user-images.githubusercontent.com/26387391/94486914-b605d800-01a5-11eb-8a91-0544f50e185e.png)

![image](https://user-images.githubusercontent.com/26387391/94486936-c0c06d00-01a5-11eb-843b-7de93bb5cdef.png)

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@stevefox3781  We fixed the format issue and now bulletin number 2451 showing the correct view.

**Comment by stevefox3781** [comment]
Thank you for getting this taken care of quickly.
