### ISSUE TITLE
Kubota D1105B Engine Missing

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#162]
We are looking up a Kubota D1105-B under Model, the engine does not show up. The option to select the Model is there, but when you click on search results, nothing comes back. We had a member looking for specs on 8/27/2020 looking for specs and we were able to send it them from Prosis Pro. Today, not there. Can you look into this and see if this is something we did or a glitch. 

[KUBOTAD1105B08272020_fax_27082020144950.pdf](https://github.com/stellaballa/AERA/files/5329881/KUBOTAD1105B08272020_fax_27082020144950.pdf)

![D1105-B Member](https://user-images.githubusercontent.com/26387391/95127829-3f755700-071e-11eb-9721-1ff45787f8ff.jpg)

Any questions, let me konw. 

Steve

**Comment by stellaballa** [comment]
@SagarPC  please check.

**Comment by SagarPC** [comment]
This call is under the closed tab. We checked and result in showing that call. Please let me know if we are looking at wrong place.

![image](https://user-images.githubusercontent.com/31076567/95321455-b21a3a00-08b8-11eb-9ebb-ca117aa25416.png)

**Comment by stevefox3781** [comment]
The closed call was just an example that it was the engine was in Prosis Pro back on that date. When we searched for that engine in Prosis Pro & CMS on 10/5, it was not in either. We searched last night for it and it was in Prosis Pro and CMS and is still there. Nto sure what happened but looks like it fixed itself. I will go ahead and close this issue.

**Comment by stellaballa** [comment]
@SagarPC  can you take a closer look.

**Comment by SagarPC** [comment]
@stevefox3781 Please email us if you faced same issue again. We cheked but did no find any issue with seach.
