### ISSUE TITLE
Member Information Missing from Specification Request

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#163]
This happened once last week and we had it happen again today. The member number nor company name came through on the specification request. It seems to show up in the email we get, but not on the tech call for MMS. I have included a screen shot of the specification request, email and membership record. I thought it might have been the user last week until we got it again today. Any questions, let me know. 

![image](https://user-images.githubusercontent.com/26387391/95236369-730eba80-07cc-11eb-8e06-899a949bb959.png)

![image](https://user-images.githubusercontent.com/26387391/95236495-9b96b480-07cc-11eb-8930-32135db80736.png)

![image](https://user-images.githubusercontent.com/26387391/95236553-b23d0b80-07cc-11eb-91d2-e59296b23bb1.png)

**Comment by stellaballa** [comment]
@SagarPC  please look into this.

**Comment by SagarPC** [comment]
We are looking into this issue and finding a solution. This issue occurs because of session time-out on the user side.

**Comment by SagarPC** [comment]
We fixed this issue and will upload it on live with the next update of casting number.

**Comment by stevefox3781** [comment]
@SagarPC sounds good. Thank you for fixing this for us.

**Comment by SagarPC** [comment]
@stevefox3781  It's done and uploaded on live.

**Comment by stevefox3781** [comment]
@SagarPC Thank you!
