### ISSUE TITLE
Prosis Pro Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#164]
I emailed you these details also. This member is in the UK.
I have a new member who has been using Prosis Pro for a couple weeks and all of a sudden he got this message yesterday and cant log in.
I was able to login under his credentials so I am not sure what the issue is.

I'm using Chrome and have had no problems until yesterday. This is the message I keep getting, each time I try to reload it the Error Reference Number changes:

**Application has generated error. We have logged this error and will look into it soon.
Please contact system administrator if needed.
Error Message: 'ddlMobileSectionDescAdvance' has a SelectedValue which is invalid because it does not exist in the list of items. Parameter
name: value
Error Reference Number: 71020208357847

Try to again to see if that resolve this issue and if not, Please contact system administrator. To go continue here.**

Can you look into this and let us know what he can do to log in.

**Comment by SagarPC** [comment]
Please ask the user to open the below link in his browser and try to do login again.

https://www.prosispro.com/logoff.aspx

Please let us know if the issue persists after this action.

**Comment by kbt1** [comment]
Note: he is using a Phone to login which i didnt know at first.

the member tried the new link above and here is his reply:
I've clicked on this link and as soon as I click login, the error notification is displayed again.

**Comment by SagarPC** [comment]
@kbt1  please provide a username so we can try from our end as well.

**Comment by kbt1** [comment]
Login: Modus Engine Services
Password: 44736

he tried logging in from Chrome, Safari
Reply from member: I tried typing in the address manually and I get the error notification immediately (no prompt for username and password). I disabled the wifi on my phone and typed the address manually into Safari, this got me to the prompt to reset my account, which I did. I then logged in successfully, however, when I tried a search it froze and the error notification is displayed.

**Comment by SagarPC** [comment]
I tried and it's working for me in mobile and desktop both with Safari borowser. 

can you please ask customer to clear cookies and try again to do login? There might be issue with correpted cookies in his browser and becase of that they are getting error.

**Comment by kbt1** [comment]
Thank you, i have passed this along and will keep you posted if this works or not.

**Comment by kbt1** [comment]
Sagar
Can you tell me steps to clear cookies, he doesnt know how to do that.

**Comment by kbt1** [comment]
The member cleared the cookies and all is good again. 
Thank you!

**Comment by kbt1** [comment]
Sagar, this member is still having issues.

I spoke too soon ! I was able to search by make and model without issue. 
However, when I went to the advanced search, specifically search by con rod big end housing diameter, the program quit again and displayed the error notice. This was what I was doing over the last couple of days, searching all engines 2.268" big end housing.

can you see what the issue is.

**Comment by kbt1** [comment]
Sagar
I had a staff member try the same search and he got the same error on his phone and the web version.
It completely locked up his phone and web version and he had to reboot to get back in.
t**he issue seems to be  advanced search, search by component and size, make of all, selection of connecting rod, description, big end housing bore and it doesnt matter measurement, you get an error.** 

please look into this.  

![error message](https://user-images.githubusercontent.com/26387044/95485412-4b982900-0957-11eb-9812-4b75ca6a0811.jpg)

**Comment by SagarPC** [comment]
Hi Karen, we will look and get back to you with some finding.

This is some special case so first need to reproduce this case and fix.

We will fix asap

**Comment by kbt1** [comment]
if you follow these exact steps on the phone or web, you should get the same error
the issue seems to be advanced search, search by component and size, make of all, selection of connecting rod, description, big end housing bore and it doesnt matter measurement, you get an error.

Keep me posted. Thank you!

**Comment by SagarPC** [comment]
@kbt1  Thanks for providing detail on this.  We addressed this issue, and test on live site. It's working for us. 

Please check from our end and provide feedback.

**Comment by kbt1** [comment]
Working for us. If i hear back from the member with more issues, i will let you know.
Thank you!
