### ISSUE TITLE
Casting Photo Submitted to AERA

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#166]
Dave had a member that added a casting photo on the users account and wanted him to send it to us. He said he could not check the box; Dave tried it on his end and same thing as did I. Wondering if the casting photo has the ability to send it to AERA, it looks like that the option is there but not active. I would think they would check the box on the right and hit Submit Image to AERA. Can you look into this for us. 

![image](https://user-images.githubusercontent.com/26387391/96627076-f6083880-12d5-11eb-8dd8-baf6d7652baf.png)

Thanks

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@stevefox3781  We made changes for the multiple casting image on stage and this issue might resolve with this update. https://github.com/stellaballa/AERA/issues/158

Should we move this change to the live, It should fix this issue.

**Comment by stevefox3781** [comment]
@SagarPC Yes you can move this to live.

**Comment by SagarPC** [comment]
Please see the below image for reference. We checked and now it's working fine.

![image](https://user-images.githubusercontent.com/31076567/97566161-63ba1000-1a0c-11eb-9910-2245b8a4a1f1.png)
