### ISSUE TITLE
Tech bulletin

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#167]
@SagarPC Can you fix the formatting on the TB? Every time when there's a & and space when you print the PDF it show up as &nbsp;

<img width="591" alt="Screen Shot 2020-10-21 at 10 10 59 AM" src="https://user-images.githubusercontent.com/30122790/96754175-c6b10480-1385-11eb-866b-33705e2c7fdd.png">

<img width="332" alt="Screen Shot 2020-10-21 at 10 04 52 AM" src="https://user-images.githubusercontent.com/30122790/96753953-7639a700-1385-11eb-892f-995f46ccf9fd.png">

**Comment by SagarPC** [comment]
We fixed this issue and uploaded on live. Please see the below image for reference.

![image (2)](https://user-images.githubusercontent.com/31076567/97005746-7cce4700-155c-11eb-90bf-e348bbd2b8b1.png)

![image (1)](https://user-images.githubusercontent.com/31076567/97005750-7dff7400-155c-11eb-95f1-be001ee4944d.png)

**Comment by stellaballa** [comment]
Thanks, @SagarPC  is there any way to run a script through the PDF to make sure this type of formatting doesn't happen? I know this is just an example, there are another ones that AERA noticed.

**Comment by SagarPC** [comment]
Our new update solved the issue so now this type of issue will not occur again for any pdf export
