### ISSUE TITLE
Custom Engine Editing

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#17]
The same member who asked about the casting numbers is now trying to edit or add specifications to the engine he has added and is getting the following error message. The member is ID #937 and the username is fxengines and password is blowfish@282. I am trying to get the information on the engine so as soon as I have that, I will pass it along. 

![custom engine spec edit](https://user-images.githubusercontent.com/26387391/30490806-b61336ae-9a00-11e7-8429-020dde88ce44.jpg)

**Comment by stevefox3781** [comment]
Here is the engine info: 

Overview             Created:  Sep 11, 2017   Edited: Sep 15, 2017
MAKE DELAHAYE          MODEL 135M                     YEAR 1949-0            VIN                  
LITER 3.6          CID 217
CYL 6

**Comment by SagarPC** [comment]
We have resolved this issue and uploaded on stage and production.
