### ISSUE TITLE
Screen Flash Real Quick

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#171]
@SagarPC @stellaballa 
It seems when searching an engine, clicking on engine etc., the screen will flash this information below for about 1 second and then disappears. We dont have any members calling about it, but it has been happening for for the last 3 days I think. I finally was able to catch a screen shot of it. 

![image](https://user-images.githubusercontent.com/26387391/97726331-1a65d100-1a9d-11eb-9679-fe35aecee5b3.png)

**Comment by stellaballa** [comment]
@SagarPC  please take a look.

**Comment by SagarPC** [comment]
@stevefox3781 We fixed this issue on live.

**Comment by stevefox3781** [comment]
@SagarPC Thank you!
