### ISSUE TITLE
Fixes/Changes for MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#172]
1.	Category codes are missing in **Associate (AS) Member** records (seems to have disappeared when you made the codes check mark boxes for active members) You need to add Associate Member Codes.
**Codes are: CM, EM, MR, PM, BP, CP, CS, ED, IM, MP, RM, SS, WD**

![image](https://user-images.githubusercontent.com/26387044/98256374-1a098200-1f44-11eb-9817-aa40b561577a.png)

2.	Add 2 new options to “Mail Code” to drop down List:	**Retired** 
							                                        **Closed Shop**

3.	Default Prosis Pro Current Users Buffer Days to 3 on all current accounts. DO NOT include Prosis Pro 30-day Trials.

4.	**Under Export Data:** 
It looks like on the export data page; the info is pulled onto a spreadsheet the same order it is listed under “Contact Info”, please rearrange the order: 
**Contact Name, Co Name, Mailing Address, Shipping Address, Phone, Fax, Email, Website, Additional Contact, Comments, Position.**

5.	On **Product Order Form**, add a box under Total $ labeled Discount $ and allow entry of negative dollar amounts for discount to be applied to an order.
Example: Total $100	Discount -$25	Shipping $10	Total $85

![image](https://user-images.githubusercontent.com/26387044/98256787-98662400-1f44-11eb-9748-2966ed19a7f3.png)

Sagar, If you have any questions, please let me know.

Thank you.
Karen

**Comment by kbt1** [comment]
Sagar, let me know if you have any questions on these fixes, Steve said he spoke with Stella and approved for these to be done.

**Comment by SagarPC** [comment]
@kbt1 We done with all the changes and doing testing. We will upload on stage first and after that upload on live before the end of this week.

**Comment by SagarPC** [comment]
@kbt1 We are done with this change and uploaded on live. Please see attached doucment file for our comment.


[#172 Testing Doc.docx](https://github.com/stellaballa/AERA/files/5536476/172.Testing.Doc.docx)

[ProsisPro-11-13-2020.xlsx](https://github.com/stellaballa/AERA/files/5536477/ProsisPro-11-13-2020.xlsx)

**Comment by kbt1** [comment]
All looks except the Assoc Member Codes. They all used to have codes and now have all reverted to Other.
see sample.
[Assoc Mbr Codes Sample.xlsx](https://github.com/stellaballa/AERA/files/5538916/Assoc.Mbr.Codes.Sample.xlsx)

for example, this is listed on the spreadsheet
2958	Irontite Products Inc	Other-Other-Other
the 3 "other-other-other" means they had 3 codes previously.

when these were added, all the assoc codes were lost somehow.

Category Code
 AC AD AF AH AL
 AM AP AY

now you added this which is good, but all the associates have reverted to other again. I thought the codes would come back correct.

Category Code
 AC AD AF AH AL
 AM AP AY AI CM
 EM MRPM BP CP
 CS ED IM MP RM
 SS WD Others

**Comment by kbt1** [comment]
I also noticed the Prosis Pro Buffer Days is not updated. 
![image](https://user-images.githubusercontent.com/26387044/99113473-ee763f80-25b4-11eb-8385-989d22460952.png)
All current prosis pro users should all be set to 3 and they dont look like they changed.
**Buffer Days
7**

**Comment by SagarPC** [comment]
I am looking into it, Will get back to you soon.

**Comment by SagarPC** [comment]
@kbt1 We almost done with the fixing in local and plan to upload on live by tomorrow.

We will inform you once we done with the live update.

**Comment by kbt1** [comment]
thank you!

**Comment by SagarPC** [comment]
1) We update buffer for all prosis pro users with 3 days.
![image](https://user-images.githubusercontent.com/31076567/99800724-cc536300-2b5a-11eb-8fc3-4c86b26981ce.png)

2) Duplicate code
Please see the bellow document for our comment and digging on this. 
Comment: [Issue Update.docx](https://github.com/stellaballa/AERA/files/5573666/Issue.Update.docx)
Reference: [Assoc Mbr Codes from 2016 MS Access DB.xlsx](https://github.com/stellaballa/AERA/files/5573670/Assoc.Mbr.Codes.from.2016.MS.Access.DB.xlsx)

**Comment by kbt1** [comment]
The prosis buffer days looks good.

you can update the Assoc Mbr Codes with the spreadsheet you attached. That is perfect.
let me know when you update the codes and i will check them.

**Comment by SagarPC** [comment]
@kbt1 We updated most of the member with proper code but still we have 73 member available with others code. We are looking into old MS Access DB to update those member as well.
[Not found category for member.xlsx](https://github.com/stellaballa/AERA/files/5583751/Not.found.category.for.member.xlsx)

**Comment by SagarPC** [comment]
@kbt1  We updated all users and added few new codes for that. Please see 
[NEW CODES.xlsx](https://github.com/stellaballa/AERA/files/5588270/NEW.CODES.xlsx)  excel file for list of new code. We also not able to add 3 code as it's listed as text in old database. We added those 3 codes in same excel. 

We have still 27 users with duplicate code. Please see [Remainig User.xlsx](https://github.com/stellaballa/AERA/files/5588276/Remainig.User.xlsx)  excel file for those users. Please let us know which action required for these users.

**Comment by kbt1** [comment]
All of the above spreadsheets:
No found category for members
New Codes
Remaining Users

all of the above are expired members so no concern at this time.

Thanks!

**Comment by SagarPC** [comment]
@kbt1  Thanks for the feedback. All remaining is already updated on live. If all looks good then you can close this ticket.
