### ISSUE TITLE
Prosis Pro - Printing in Internet Explorer

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#173]
We have a member that uses Internet Explorer for Prosis Pro. Printing doesnt seem to work this week but it did last week.
I checked Internet Explorer and it doesnt print for me but Edge and Chrome do. Is this something that needs to be fixed or does the member need to upgrade his browser?

Select an engine, click on print button, print manager opens with what sections you want to print, make selection,  click on print button and nothing happens. 

let me know.
Thanks!

**Comment by kbt1** [comment]
I just found if you select an engine that has bulletins attached, select the bulletins to print, it works.

**Comment by SagarPC** [comment]
@kbt1 We are looking into this, we found cause and working on it. It will be fixed by tomorrow and we will upload on live.

**Comment by kbt1** [comment]
thank you!

**Comment by SagarPC** [comment]
@kbt1  We fixed and uploaded the IE issue with print on live. We checked and now it's working fine.

**Comment by kbt1** [comment]
working!
