### ISSUE TITLE
Pixel Banner Export - Prosis Pro CMS

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#174]
When I export a report using the dates 11/16/2020-12/15/2020, the screen just goes blank (white). Wondering if choosing those dates is an issue instead of the first day to the last day. Tried it several times with the same results. Looking for the report for those dates under Victor Reinz. It never gets to the spreadsheet, screen just turns white.

Any questions, let me know. 

Steve

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue. Please export now.

**Comment by stevefox3781** [comment]
@SagarPC Thank you!Wworking great.
