### ISSUE TITLE
Correct Name of Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#175]
Sagar
Can you please correct the name of this dues batch in MMS:
01-01-21 BulkEntry By KT CheckDate: 12/28/2020By: Karen Tendering

Change to 12-28-2020kt Monthly ACH Batch

let me know when updated.

Thank you!

**Comment by SagarPC** [comment]
@kbt1

Updated batch name, please see below image for reference.

![image](https://user-images.githubusercontent.com/31076567/103265776-64ebc700-49d4-11eb-9d52-6fae53f13832.png)

**Comment by kbt1** [comment]
Perfect, thank you!
