### ISSUE TITLE
Supplier Links Address Field

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#178]
I am updating the Elgin image and link and it looks like the link has a limit on it. I am trying to add the following link - https://www.elginind.com/wp-content/uploads/2018/12/Elgin-2018-ProStock-Catalog.pdf and when I do, it does not all fit. Can we add length to the website address field so it will all fit? 

![image](https://user-images.githubusercontent.com/26387391/103843979-7c732180-505e-11eb-8658-877f7f442942.png)

Any questions, let me know. 

Thanks

**Comment by SagarPC** [comment]
@stevefox3781 We removed the limited length for the link, I also updated the given link for the Elgin supplier. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/103858497-702ea900-50de-11eb-8d08-a7a57ea2eec3.png)

**Comment by SagarPC** [comment]
@stevefox3781  Also looks like the "Victor Reinz" link is not proper, missing values after **utm_campaing**  

Please provide a complete link to update.

**Comment by stevefox3781** [comment]
Sagar, thank you for getting that fixed and the heads up on the Victor Reinz link as well. I have gone ahead and updated that link. 

Thanks again!
