### ISSUE TITLE
MMS - invoicing

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#18]
When emailing a Prosis Pro invoice, there is a spelling error I just noticed:

![image](https://user-images.githubusercontent.com/26387044/30561906-42a58f1c-9c82-11e7-878d-222c976ed3ca.png)

Your company’s Prosis Pro Softwaresubscription is about to expire. 
add space between Software and subscription.

**Comment by SagarPC** [comment]
We have done with this update. Please refer below image for that. Please check and confirm our update.

![18](https://user-images.githubusercontent.com/31076567/30746919-167ed1ba-9fc9-11e7-900b-547787994ac0.png)

**Comment by kbt1** [comment]
looks good
