### ISSUE TITLE
AERA Certification Database

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#180]
Hi Sagar
Amanda and I both are noticing this and wanted to see if you have the same thing happen.
This is a Group Name of LAT2021

troystuwe | lat2021
brada | lat2021ba
dylanb | lat2021db
connorb | lat2021cb
nicholasd | lat2021nd
jacobd | lat2021jd
bryceh | lat2021bh
taylorh | lat2021th
nicholass | lat2021ns

After they have been entered, i looked them up, and all looks good except the Company name is missing. (i didnt put the address in any of the records)
![image](https://user-images.githubusercontent.com/26387044/103941527-99f2ca80-50f4-11eb-8c7b-3f4592a2b779.png)

If I exit out of the record and go back in again and view it, the Company name is missing AND the boxes for the course are not checked.
![image](https://user-images.githubusercontent.com/26387044/103941643-c60e4b80-50f4-11eb-95cb-0aa1e169f763.png)

If I close the record and view it again, the boxes are checked again but the company is still missing, 

I dont know if there is something broken when the logins are put into a GROUP NAME but i entered the school name Lake Area Tech for each login and its missing. 

Can you check on your end and see if this is happening to you also?

**Comment by amandagoyette** [comment]
I received a call from SAM Tech and they're noticing the same issue.

**Comment by SagarPC** [comment]
@aharmening  and @kbt1 I fixed issue on live. I checked from my end now it's wokring for me. Please provde Company name for the user listed under "LAT2021" group. I will update from my end.

Also, add new user to verify our update. Please let me know if there is any issue.

_Note: Please reload screen by pressing "Ctrl + F5" togather becuase I did change in javascript._

**Comment by amandagoyette** [comment]
@SagarPC Lake Area Tech is the company name for everyone in the LAT2021 group

**Comment by kbt1** [comment]
All seems good today. I added this new student and all information remains if I view, exit and go back in and view.
![image](https://user-images.githubusercontent.com/26387044/104023883-e76c4780-5187-11eb-973c-2ca4ee0cb9d6.png)

If you could add Lake Area Tech to the company name for the LAT2021 Group, I would appreciate it.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 I updated company name "Lake Area Tech" for group "LAT2021"

**Comment by kbt1** [comment]
Looks good, thank you.
We will keep you posted if we find any other issues.
