### ISSUE TITLE
AERA EDU not loading

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#181]
Hi Sagar,

We received a message last night from a student that was having issues getting her test to let her complete.  She tried to go back to the log in page and it wouldn't load.  I'm finding when I go to aeraedu.com it just loads a blank page too.  Can you look into it please?

Thanks!

**Comment by SagarPC** [comment]
@aharmening  I am looking into this. I faced the same issue here as well. There might be something wrong with the server!

**Comment by SagarPC** [comment]
@aharmening  I checked and found an issue with SSL for api.aeraedu.com. It's sending errors like Certificate Revoke. I informed VCS to look into this and CC to you as well.

![image](https://user-images.githubusercontent.com/31076567/104128967-70ee6600-5390-11eb-8b69-80b631252beb.png)

**Comment by amandagoyette** [comment]
Thank you! I will keep on VCS to make sure this is resolved quickly

Amanda Harmening
Administrative Assistant
AERA Engine Builders Association

________________________________

**Comment by SagarPC** [comment]
This issue is resolved by VCS so closing this thread.
