### ISSUE TITLE
Delete a Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#182]
Can you please delete this batch
![image](https://user-images.githubusercontent.com/26387044/106057793-19513980-60b6-11eb-8007-2552f3e85afe.png)

i had a wrong date, i redid the batch with the correct date.

**Comment by SagarPC** [comment]
@kbt1 We removed the requested batch **1-27-2021 Monthly ACH Batch**.

**Comment by kbt1** [comment]
thank you!
