### ISSUE TITLE
Gas & Diesel Designation

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#184]
We would like to add a little color to the Gas & Diesel designation under Fuel Type in the search results. Leave gas the way it is and change Diesel to a green color. Some have asked for Diesel to be bold but not sure how it it would look compared to Gas not bold. If you can make the color change and send a screen shot both ways then I can make a decision. 

![image](https://user-images.githubusercontent.com/26387391/106531706-5cdfe500-64b4-11eb-9646-a3f9115286e7.png)

**Comment by SagarPC** [comment]
@stevefox3781 Please see below for the screenshots. I attached 3 different versions. Please suggest which you would like to implement.

1) Green color normal font
![image (8)](https://user-images.githubusercontent.com/31076567/106602914-a4817200-6583-11eb-8892-9551f8c5d503.png)


2) Green color bold text
![image (9)](https://user-images.githubusercontent.com/31076567/106602922-a64b3580-6583-11eb-97aa-37fd1c661f1b.png)


3) Only bold text
![image (10)](https://user-images.githubusercontent.com/31076567/106602917-a5b29f00-6583-11eb-8a87-3204f851e453.png)

**Comment by stevefox3781** [comment]
Sagar,

The consensus of the group is option 3 – bold in black.

Thank you for the suggestions.

Steve Fox
AERA VP/Operations Mgr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org<http://www.aera.org/>

**Comment by SagarPC** [comment]
@stevefox3781 We uploaded this change on live. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/107374556-b9bf4900-6b0d-11eb-980f-eab607c62f1c.png)

![image](https://user-images.githubusercontent.com/31076567/107374582-c2b01a80-6b0d-11eb-9ea9-2c5710e82d96.png)

**Comment by stevefox3781** [comment]
@SagarPC Thank you! Looks great and appreciate you getting that done for us,
