### ISSUE TITLE
Field Additions to Tech Call

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#185]
Sagar - was wondering if this would fall under the monthly or needs to be done with our yearly update to the program? We are wanting to add 3 fields to the tech calls - 1) Complete VIN 2) Serial # 3) Arrangement # as shown in the screen shot below. Let me know what you think. 

![Complete Vin, Serial Number   Arrangement Number Addition](https://user-images.githubusercontent.com/26387391/106629293-4da67900-6540-11eb-98cc-18a08b17c270.gif)

**Comment by SagarPC** [comment]
@stevefox3781 ,

That we will consider inside monthly.

**Comment by SagarPC** [comment]
@stevefox3781 I will schedule this work soon this week.

**Comment by SagarPC** [comment]
@stevefox3781  We added 1) Complete VIN 2) Serial # 3) Arrangement # box as you requested and uploaded on live.

Please check and confirm our update.

![image](https://user-images.githubusercontent.com/31076567/107372899-ef633280-6b0b-11eb-9c56-4e1f6f8f9bf5.png)

**Comment by stevefox3781** [comment]
@Sagar Looks Great! Thank you for getting that change done for us.
