### ISSUE TITLE
Engine Procedure Link Broke??? Not Sure

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#186]
Looking up the engine in Prosis Pro and when we go to click on the procedure do we get the following: 

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

It seems that maybe a link was broken??? not sure. Nobody on our end seems to recall removing the link or file from Prosis Pro. It is the same on user and CMS side. Any help or knowledge would be appreciated. Member recalls seeing it and giving to his customer in the past. 

![image](https://user-images.githubusercontent.com/26387391/106668286-b6f1b080-656f-11eb-993d-cb69cef96ca2.png)

**Comment by SagarPC** [comment]
@stevefox3781 We checked and somehow PDF not uploaded to the server. Please send me the uploaded PDF file here I will check from my end to upload.

**Comment by stevefox3781** [comment]
@SagarPC I will have to check and see if I can locate the file. We tried looking for it yesterday and no one was able to locate the file so we will need to recreate it and upload again. I can do that on my end no problem. We were just wondering if the link got broken but sounds like the file was never uploaded. Thanks for checking on this I will go ahead and close this call since we need to recreate the file more than likely. If we do find the original, I will upload it. Thank you again for looking into this.

**Comment by SagarPC** [comment]
@stevefox3781 Thanks for the information, I looked more and found the cause of the issue. It's because of the same file name linked with the more number of engines. We are fixing and upload on live asap.

**Comment by stevefox3781** [comment]
@SagarPC Ok great thank you so much! So I guess what you are saying is that if the same file applies to more than one engine, we can't have the same file number for multiple engines?

**Comment by SagarPC** [comment]
@stevefox3781 You can use the same file with the same name for the multiplier engine after fixing this issue.

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue on live. We checked for the missing PDF and found 15 PDF is missing under the different engine. Please see below for the list of those engines with PDF caption name. We need to reupload those PDF.

[MISSING-PROCEDURES-PDF.xlsx](https://github.com/stellaballa/AERA/files/5952022/MISSING-PROCEDURES-PDF.xlsx)

Please let me know if any questions.

**Comment by stevefox3781** [comment]
@SagarPC  Ok sounds good. I will start to look for those procedures. Is that something we can upload on our end or should we send to you for uploading?

**Comment by SagarPC** [comment]
You can upload from your end or you can send it to me we can upload it for
you.

**Comment by stevefox3781** [comment]
Got them all taken care of.
