### ISSUE TITLE
Update Password Reset wording in PROSIS

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#187]
Hi Sagar,

We get a lot of calls from people confused when the password reset comes up.  Karen and I were trying to decide on better wording and below is what we came up with.  Can we update the pop-ups to reflect this?  I honestly don't remember exactly what each says currently.

“It’s time to change your password”

Please create a new password below, confirm it and store the information in a safe place. When you log back in, type in your new password.

*Note: You will have to update the auto-fill if your password populates automatically, so be sure to type in the password even if it appears to be filled in

**Comment by SagarPC** [comment]
@aharmening Please see below update look for the reset password window. Please let me know if any changes required. 

I will update on live after getting your confirmation.

![image](https://user-images.githubusercontent.com/31076567/109923242-7b6c1280-7ce4-11eb-8cb7-608e7b99acad.png)

**Comment by amandagoyette** [comment]
@SagarPC  

Can we change it from **Please enter your new password** to **Please create your new password**

Otherwise it looks great!

**Comment by SagarPC** [comment]
Please see updated image

![image](https://user-images.githubusercontent.com/31076567/109985499-d163a900-7d2a-11eb-9711-d4a07dccc206.png)

**Comment by amandagoyette** [comment]
@SagarPC looks perfect.
