### ISSUE TITLE
Advanced Search Cylinder Head Sections

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#188]
I think when we revamped the Advanced Search Features, we did not supply you with a range on the Cylinder Head features. We looked up a Suzuki for a stem height spec with a range of 1.5433-1.5669 and if you type in 1.555, nothing comes up, you have to type in either 1.543 or 1.566 to get the engine to show up. I have gone ahead and listed for the cylinder head the ranges that we would like to have added to the advanced search below. If you have any questions, please let me know. 

	Stem Height (number entered in range selection +/- .015”) 
	Valve Head Diameter (number entered in range selection +/- .015”) 
	Stem Diameter (number entered in range selection +/- .005”) 
	Valve Rec/Prot (number entered in range selection +/- .015”) 
	Spring Free Length (number entered in range selection +/- .025”) 

![image](https://user-images.githubusercontent.com/26387391/110807016-3b5ae180-8248-11eb-8b00-a1e9598dc394.png)

**Comment by SagarPC** [comment]
@stevefox3781  We added range and now it's working. Please see the below image for reference.

![image (3)](https://user-images.githubusercontent.com/31076567/111029126-ecb46f80-8420-11eb-98d2-4985753af1c6.png)

**Comment by stevefox3781** [comment]
Thank you!
