### ISSUE TITLE
Rename a Dues Batch in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#189]
Hi Sagar

Can you rename a Dues Batch for me please.

3-1-2021 March Monthly Credit Card Batch Date: 03/11/2021 By: Karen Tendering

it should be **3-11-2021 March Monthly Credit Card Batch Date: 03/11/2021 By: Karen Tendering**

thank you very much.

**Comment by SagarPC** [comment]
@kbt1 We updated the batch name as you requested. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/110940574-20c65c80-835d-11eb-9d6f-352da7cb8d0c.png)

**Comment by kbt1** [comment]
Thank you for fixing it.
