### ISSUE TITLE
404- File Directory Error

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#190]
When we print the specifications and diagrams from the highlighted engine from the list below, we get the following error code. 

![image](https://user-images.githubusercontent.com/26387391/110823164-6f89ce80-8257-11eb-8765-44e2af6df63d.png)

If we take the diagrams out, the specs print fine. If diagrams are selected with specs, that is when we get the error. The same images are in the other two engines listed and the specs and images print just fine when both are selected. 

![image](https://user-images.githubusercontent.com/26387391/110823436-b8418780-8257-11eb-8861-ee5ae961f917.png)

**Comment by SagarPC** [comment]
@stevefox3781 We fixed this issue and now export is working.  

There was an issue with a special character in the file name. We updated logic to remove the special characters and now it's working.

**Comment by stevefox3781** [comment]
Great thank you!
