### ISSUE TITLE
Sending Email from Tech Call

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#191]
Is there a way to prepopulate the highlighted fields with the techs name? We have to login into MMS so it should know who we are by the login. Just a question but if it can be done we would like to do that. Also, if we can eliminate some of the extra spaces in the body where we would type, that would be great as well. 

![image](https://user-images.githubusercontent.com/26387391/111368046-6176ec00-8663-11eb-87b0-d5d3fc25919b.png)

**Comment by SagarPC** [comment]
@stevefox3781  Please see the below document for my comment and questions. 

[Task-191.docx](https://github.com/stellaballa/AERA/files/6156882/Task-191.docx)

**Comment by stevefox3781** [comment]
@SagarPC - see note in red. 

![image](https://user-images.githubusercontent.com/26387391/111486532-90459e80-8705-11eb-8e88-6ae4f0069541.png)

**Comment by SagarPC** [comment]
@stevefox3781 We implemented this function and uploaded it on live. Please check and confirm our update.

**Comment by stevefox3781** [comment]
Perfect thank you so much!

Steve Fox
AERA VP/Operations Mngr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org<http://www.aera.org>
