### ISSUE TITLE
Emailing Out of Tech Call - Email Address Issue

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#192]
Done a tech call today and member wanted the information emailed to him, no problem. Verified the email address in the call to be service@wagamonbrothers.com which was correct. I sent the email only to have them call back looking for the info. Found out that the email address when I clicked on the EMAIL button, changed to info@wagamonbrothers.com. The info email address in the membership record and the service email address is listed under Additional Contact tech. It looks like when we click on the Email button from a tech call, it is taking the email address listed in membership and not the one under additional contacts tech. See picture for example. 

Does the same to the AERA record. When you open a tech call, shows steve@aera.org but when you click email button from tech call, changes to karen@aera.org which is the email for the membership record. 

Any questions let me know. 

![image](https://user-images.githubusercontent.com/26387391/112209461-79141e80-8be7-11eb-9220-56c7a9faf70f.png)

**Comment by SagarPC** [comment]
@stevefox3781 We got your concern! You want the same email address inside the "Email" popup which we are showing on the Tech call screen, correct? If you make any change to email on the Tech call screen it should update the same in the "Email" popup, correct?

**Comment by stevefox3781** [comment]
Correct

Steve Fox
AERA VP/Operations Mngr/Tech Specialist
815-526-7348

On Mar 24, 2021, at 6:19 AM, SagarPC ***@***.***> wrote:

﻿

@stevefox3781<https://github.com/stevefox3781> We got your concern! You want the same email address inside the "Email" popup which we are showing on the Tech call screen, correct? If you make any change to email on the Tech call screen it should update the same in the "Email" popup, correct?

**Comment by SagarPC** [comment]
@stevefox3781  We did this change and uploaded on live.  Please refer to below image for reference.

![image](https://user-images.githubusercontent.com/31076567/112315517-3a0dc800-8cd0-11eb-8986-87421622956b.png)

**Comment by stevefox3781** [comment]
@SagarPC Perfect thank you!
