### ISSUE TITLE
MMS-Monthly Report-Quick Membership Counts Report

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#193]
Hi Sagar
I ran the Quick Prosis Pro Count report and I need to know what companies fall under "Companies Using Old System"

Quick Membership Count Report
Check Prosis box
Exp Date= 04/14/2021
uncheck history search box

When i run the above report, this is the result:

Prosis Pro Total   Companies Count | 1444
Prosis Pro Web Companies Count | 1223
Prosis Pro Desktop Companies Count | 45
Prosis Pro Web and Desktop Companies   Count | 174
**Total Companies Count Who Neither Using Old Systems | 2**   **Can you tell me what 2 members fall under this category?**

let me know if you have any questions.

Thank you
Karen

**Comment by kbt1** [comment]
I just updated a couple records and the numbers changed but i still have 2 unidentified on old system

Prosis Pro Total   Companies Count | 1444
Prosis Pro Web Companies Count | 1223
Prosis Pro Desktop Companies Count | 42
Prosis Pro Web and Desktop Companies   Count | 177
**Total Companies Count Who Neither Using   Old Systems | 2**

**Comment by SagarPC** [comment]
@kbt1 Please see below-listed members belong to that category.

**Member No.** / **Company Name** 
11248 / Automotive Machine Works
44644 / K & J Repair

**Comment by kbt1** [comment]
thank you, i figured out why they came up under that category.
