### ISSUE TITLE
Online Training 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#195]
Sagar
It looks like the teacher dashboard rounds up a grade from 79.57% to 80% on their dashboard, however, in the student login, the grade is 79.57% and its not passing. Can you fix this so it just rounds up anything 79.5% and up to 80% on both teacher and student dashboards to avoid this issue.

We have another student that has a passing grade on the teacher dashboard, however, under the student account, its not passing.

Chapter12 - Reconditioning Valve Train Components | 03/30/21 | **79.57%**   **update to 80% please**
User name: riczay
Password: atcrz

thanks. let me know when done.

**Comment by SagarPC** [comment]
@kbt1 We rounded score for Admin, Teacher, and Student. Now no more decimal score will be visible.

Please check our update and let us know if any changes required.

Regards,

**Comment by kbt1** [comment]
looks good.
thank you!
