### ISSUE TITLE
Online Certification 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#196]
Hi Sagar.

We have run into a student that passed with 80%, however, on the the student login and instructor login pages, they are red like he did not pass and in my admin login, its green and marked as he did pass. I didnt get notified of him passing so I havent sent him his certificates yet. 
Here is a screen shot of my admin login:
![image](https://user-images.githubusercontent.com/26387044/115767314-9cf58c00-a36e-11eb-8bae-f4595803e036.png)

Here is a screen shot of the instructor login:
![Lake Area Tech](https://user-images.githubusercontent.com/26387044/115767362-ac74d500-a36e-11eb-8f0c-498b22d61abe.jpg)

can you double check this and make sure all passing scores are green and I get an email that they have passed.
nicholas schmidt is the student that got a passing score but his score is red and not green in the instructor login.
Login: nicholass    Password: lat2021ns

Thank you!

**Comment by kbt1** [comment]
In thinking about this, I bet this student was a 79.__% and since you worked on the program, it updated it to 80%.
So anyone with 80% or greater must have their score turn green and if its 1 of the 2 exams, I get an email notifying me so I know.

**Comment by SagarPC** [comment]
@kbt1 We update logic for the email send and all other places where we are showing scores. now it will always show a rounded score and all logic will work on that rounded score.

Please let us know if you are still facing any issues.

Regards,

**Comment by kbt1** [comment]
thank you!
