### ISSUE TITLE
Diagram Printing

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#197]
Member called trying to only print the diagram checked below. When they print as well as I, get a blank page. If I select to print all diagrams, the diagram prints. Can you look into why the we can't print the diagram by itself? If I print other diagrams by themselves, they seem to print fine. 

Any questions, let me konw. 

![image](https://user-images.githubusercontent.com/26387391/116250286-34722a80-a733-11eb-905e-12e9d8dff203.png)

**Comment by SagarPC** [comment]
@stevefox3781 We checked and found an issue with the image width. We need minimum 600px width and 600 height of the image. We fixed the issue for this image and looking for the another image with the same issue.

**Comment by stevefox3781** [comment]
Thank you.
