### ISSUE TITLE
MMS - Conferences Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#2]
Now that we are using the conferences tab, there are some changes we would like to make it easier to figure out.
this is the current view with counts of attendees and exhibitors and the numbers are confusing:
![image](https://user-images.githubusercontent.com/26387044/29429612-ecf90998-8356-11e7-818d-53adb4b1f5d0.png)

Can this be changed so we have counts as:
Attendee Count: number of paid attendees in 1 count, dont break out attendee & additional attendee
Exhibiting Company Count: number of member companies for tabletops
Non Member Exhibiting Company Count: number of non-mbr companies for tabletops
Exhibitor Personnel Count: count includes name of exhibitor and additional exhibitor names in 1 count.
Delete Additional Attendee Count.

In one view we need to know how many paid attendees there are, how many member tabletops and non member tabletops and exhibitor attendee count, the current listing is confusing.

If you have questions, please call me or Steve on this. 
Thank you

**Comment by SagarPC** [comment]
@kbt1  :

We have done with the change and uploaded on production please see below for the equation that we used to show count. Please review and let me know if any any change.

Attendees: Attendee + Additional Attendee

Exhibitors: tabletops Exhibitors only.

Non Member Exhibitor: tabletops Non Member Exhibitors only.

Exhibitor Personnel Count: [tabletops Exhibitors] + [tabletops Non Member Exhibitors] + [Additional Exhibitors] + [Additional Non Member Exhibitors]

**Comment by kbt1** [comment]
looks good. thank you!
