### ISSUE TITLE
Editing Dashboard Sections

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#200]
@SagarPC Would like to change out the Online Training sometimes with some new content. When I go to change the image, it gets all messed up. Is there a way to have it convert to the correct size no matter what size image we put in or can you give me the specs for the images should be? Was changing to an engine giveaway we are doing at the PRI Show in December and switech it back to Online Training. The first image is how it looks now and the second image is how it looked before I started changing the image. Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/26387391/117705450-aa45af80-b191-11eb-9544-7122691b1856.png)

![image](https://user-images.githubusercontent.com/26387391/117705477-b467ae00-b191-11eb-88e4-610f65d4c708.png)

**Comment by SagarPC** [comment]
@stevefox3781:  That box need image in 22 : 29 ratio. We changed and uploaded image 500x659 and now it's showing full image.

Please provide us new contact if you want to update. We will help you to update.

https://calculateaspectratio.com/
![image](https://user-images.githubusercontent.com/31076567/117781010-cc0c6880-b25d-11eb-8222-d1ce62812ffa.png)

![image](https://user-images.githubusercontent.com/31076567/117781195-ffe78e00-b25d-11eb-8876-06884d2dda34.png)

**Comment by stevefox3781** [comment]
@SagarPC This is the image I am trying to use. When I input I get the following. The dimensions and pixes are less than what you had mentioned. Can you help with this please?

![EREF_ENGINE-removebg-preview](https://user-images.githubusercontent.com/26387391/117813543-d102f500-b228-11eb-8452-33acd241e34f.png)

![image](https://user-images.githubusercontent.com/26387391/117813583-deb87a80-b228-11eb-9eef-5b8ee2ef987b.png)

**Comment by SagarPC** [comment]
@stevefox3781 We uploaded the same image and its displays like below. Please let us know if this will work or any changes are needed. If you want to update the description then you can also send it to us, we will update it for you.

![image](https://user-images.githubusercontent.com/31076567/117815071-b493a680-b282-11eb-9e76-13151c062614.png)

**Comment by stevefox3781** [comment]
@SagarPC Perfect thank you!!! I will go in and change the wording. Thank you so much for your help!

**Comment by stevefox3781** [comment]
@SagarPC Can you help me again - This is what it looks like now. I need the wording to be moved up next to the image. I dont know what I am doing wrong, but probably will not make a change again - LOL!

![image](https://user-images.githubusercontent.com/26387391/117816363-0f4de380-b22c-11eb-8802-47662f377948.png)

**Comment by stevefox3781** [comment]
Here is what I would like it to say.

Purchase To Win! This year EREF is building a 540 CID Big Block Chevrolet that will be given away at the PRI Show in Indianapolis Indiana in December. All proceeds from ticket sales go to the Engine Rebuilders Education Foundation for education and training in the engine building industry. Tickets are 10 for $20 and you can get yours today by clicking the More Info below.

Steve Fox
AERA VP/Operations Mngr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org<http://www.aera.org>

**Comment by SagarPC** [comment]
@stevefox3781 Updated content, please provide "More Info" link for this updated box.

![image](https://user-images.githubusercontent.com/31076567/117830611-6df97880-b291-11eb-8f34-a6711950d05b.png)

**Comment by stevefox3781** [comment]
@SagarPC  Thank you so much!!!!!!!!!

**Comment by SagarPC** [comment]
@stevefox3781  Please provide the "More Info" link for this updated box.

![image](https://user-images.githubusercontent.com/31076567/117831404-26272100-b292-11eb-92a3-70abafc90a2b.png)

**Comment by stevefox3781** [comment]
I just changed it.

Steve Fox
AERA VP/Operations Mngr/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org<http://www.aera.org>
