### ISSUE TITLE
Mailing List for Desktop Only Prosis Pro Users

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#201]
Hi Sagar

I need a spreadsheet for the desktop only Prosis Pro users.
ID#, Contact Name, Company Name, Mailing Address, City, State, Postal Code and Country.

My current count is 42
When I pull a list, it includes both desktop and web and I want only desktop.

Thank you!

**Comment by SagarPC** [comment]
@stevefox3781 Please see attached file list of users with the requested detail.

[prosis-pro-desktop-only-users.xlsx](https://github.com/stellaballa/AERA/files/6472448/prosis-pro-desktop-only-users.xlsx)

**Comment by kbt1** [comment]
Looks good Sagar.
Thank you.
