### ISSUE TITLE
Dues Batch Posted but Did not update exp dates

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#202]
5-10-2021 Monthly Credit Card BatchDate: 05/10/2021By: Karen Tendering
I created this batch and posted it and just noticed none of the dates have been updated.
![image](https://user-images.githubusercontent.com/26387044/118673091-586ade00-b7be-11eb-815e-6dc90124d772.png)
As you see in the batch, the dates should have gone from June 1 to July 1. 
It looks like nothing happened when i posted that batch.
can you fix please.

**Comment by kbt1** [comment]
just went through the Member ID#'s.
Looks like somewhere after ID#43360 the batch didnt post. looks like everything before it did.
almost like it timed out and didnt finish. these are big batches.  562 transactions
So everyone in this batch should have a start date of 6/1/2021 and end date of 7/1/2021 in the membership system.

**Comment by SagarPC** [comment]
@kbt1 We updated all 562 members with start date of 6/1/2021 and end date of 7/1/2021.

**Comment by kbt1** [comment]
looks good.
thank you!
