### ISSUE TITLE
Online Training Time Clock

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#205]
One of the instructors at a school submitted a question regarding the clock not restarting if the student wants to take the test over again. This may only apply to schools but I wanted to have you take a look at it. 

If you take any test, submit your answers and want to take the test again because you failed, there is a retake test button to click in the pop up window that shows the wrong answers. If you click that, the count down clock doesn’t restart over. I did screen shots below of both scenarios and you will see that the clock didn’t start again. The clock will only start over if you click the Go to Dashboard button.

![OLT1](https://user-images.githubusercontent.com/26387391/122964590-08e37900-d34d-11eb-9ce0-204ace52cb87.png)

![OLT2](https://user-images.githubusercontent.com/26387391/122964594-0aad3c80-d34d-11eb-84ca-9223883be7b6.png)

**Comment by SagarPC** [comment]
@stevefox3781 We fixed this issue and now the clock will be reset on "Retek Exam" as well. 

Please check and let me know if there is any issue.

**Comment by stevefox3781** [comment]
Great thank you!
