### ISSUE TITLE
International Phone Number Fields

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#206]
Hi Sagar
Is there a way to add an International Phone Number Field to membership allowing 13-15 digits separate from the current one?
We now have someone on staff that speaks to international members and it would help to be able to enter the correct phone numbers. The current phone number box is only formatted for US numbers.

An example of what we need is:
011-57-5370-9869  most seem to be 13 digits however, some can be 14 or even 15 depending on the country and city codes.
Dial 011 then country code, then city code and then the phone number.

let us know please.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 We received your request and reviewing this feature. We will update you soon this week. Please let us know if you have any list of countries for that you want to formate.

**Comment by kbt1** [comment]
I would need this format for all international countries Not including Canada.
You can either have the format for all members or just international countries excluding USA and CANADA.
It might even be easiest to just make a numeric box without a format where we can just enter the numbers and dashes.
Whatever you think is easiest.

**Comment by SagarPC** [comment]
@kbt1 The numeric box without auto format will not take a long time (30 min of work) + easiest as of now but auto formating of all the international numbers will take a long time to implement because we need to review and implement each country format separately. This is a time-consuming process and will take a long time to complete this feature.

Please let us know your thoughts.

Regards,

**Comment by kbt1** [comment]
The numeric box that would allow us to enter the number and dashes would be good. Make it long enough for 20 characters.
example: 011-57-5370-9869 
Label the box: Int'l Phone

**Comment by SagarPC** [comment]
@kbt1 

Please see the new label location and name. if it's ok then we will upload the same on live.

![image (5)](https://user-images.githubusercontent.com/31076567/126654814-92938f8e-7ad7-40fe-b3b2-8a5b430d7a9c.png)

![image (4)](https://user-images.githubusercontent.com/31076567/126654806-7312e986-2781-408c-b84c-2f83b7368aa5.png)

**Comment by kbt1** [comment]
That looks great!

**Comment by SagarPC** [comment]
@kbt1 We uploaded it on live. Please check and confirm our update.
