### ISSUE TITLE
AERA MMS, Monthly Report Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#207]
Hi Sagar
I just found this error in the way a report is being pulled.
Under Monthly Report Tab
Active Member Locator - Website
it seems to be pulling the shipping address with the mailing address city, state and zip code.

I have attached a current membership list that includes both address listings if they have 2.
I have attached a current member locator report
If you look at the 2nd record on each for ID#15, you will see they have both address fields however, the member locator report is pulling the street address with the mailing address city, state and zip code.
This needs to be corrected because we use these addresses for an online member locator on our website and it should be the shipping address, shipping city, shipping state, shipping zip code unless there is no shipping address, in that case, use the mailing address.

if you have questions, let me know.

[Current Membership List with addresses.xlsx](https://github.com/stellaballa/AERA/files/6903488/Current.Membership.List.with.addresses.xlsx)

[Member Locator Report.xlsx](https://github.com/stellaballa/AERA/files/6903489/Member.Locator.Report.xlsx)

**Comment by SagarPC** [comment]
@kbt1 We fixed this issue on live. Please see attached updated file which we exported from AERA MMS for your reference.

[ActiveMemberReport-Website-8802.xlsx](https://github.com/stellaballa/AERA/files/6908013/ActiveMemberReport-Website-8802.xlsx)

**Comment by kbt1** [comment]
looks good. thank you!
