### ISSUE TITLE
Can you easily Pull These Counts for Me?

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#208]
Hi Sagar
I was wondering if you can easily pull these counts onto a spreadsheet for me?
1 is Membership Country Count and 1 is Prosis Pro Country Count.
here is an example.

[Membership and Prosis Country Counts.pdf](https://github.com/stellaballa/AERA/files/6908895/Membership.and.Prosis.Country.Counts.pdf)

If not, I will do it manually.
let me know.

**Comment by SagarPC** [comment]
@kbt1 We can do it and send you by Monday

**Comment by SagarPC** [comment]
@kbt1 Please see attached file for the country name with the members count. 

1) I used Mailing country name for this report. Please see below image for the reference.
2) Considered only active and non trial member in count.

![image](https://user-images.githubusercontent.com/31076567/127810046-67f67e13-3548-40dc-968c-ac8eab83127f.png)

Report:

[Membership-Country-List-02-08-2021.xlsx](https://github.com/stellaballa/AERA/files/6914609/Membership-Country-List-02-08-2021.xlsx)
[Prosis-Pro-Country-List-02-08-2021.xlsx](https://github.com/stellaballa/AERA/files/6914610/Prosis-Pro-Country-List-02-08-2021.xlsx)

**Comment by kbt1** [comment]
Hi Sagar
I need the reports to total these as of July 30th without history search
[ProsisProQuickMembershipCountReport-without history.xlsx](https://github.com/stellaballa/AERA/files/6917319/ProsisProQuickMembershipCountReport-without.history.xlsx)
[MembershipQuickMembershipCountReport-without history.xlsx](https://github.com/stellaballa/AERA/files/6917320/MembershipQuickMembershipCountReport-without.history.xlsx)

is this possible?

**Comment by SagarPC** [comment]
@kbt1 Yes, let me re-create this report.

**Comment by SagarPC** [comment]
@kbt1 Please see the attached updated file we exported as per your given criteria.

[Prosis-Pro-Country-List-02-08-2021.xlsx](https://github.com/stellaballa/AERA/files/6917568/Prosis-Pro-Country-List-02-08-2021.xlsx)

[Membership-Country-List-02-08-2021.xlsx](https://github.com/stellaballa/AERA/files/6917567/Membership-Country-List-02-08-2021.xlsx)

**Comment by kbt1** [comment]
Those are perfect! thank you!
