### ISSUE TITLE
Notes Tab

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#209]
In the following engine, when we click SEE NOTES, it goes to the PROCEDURE tab. I think this is because we had Notes/Procedures under one tab and when we split out the NOTES to a new tab, it was not linked correctly. Can you look into this for us please? 

![image](https://user-images.githubusercontent.com/26387391/128074237-dfb18588-979b-42f0-81a0-07c7bc2544cf.png)

**Comment by SagarPC** [comment]
@stevefox3781 We fixed this issue and uploaded on live. Now it's redirecting on the Notes tab.

**Comment by stevefox3781** [comment]
Thank you!
