### ISSUE TITLE
Dues Correction Needed

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#210]
Hi Sagar
I am not sure what happened, i just noticed this error in a dues batch.
Batch 7/27/2021kt
![image](https://user-images.githubusercontent.com/26387044/128364150-368df0b4-3f50-4355-9878-07505fe96080.png)
Line 15 ID#42833 Prosis Pro  dates should be 8/1/2021 to 8/1/2022

can you please fix.

thank you.

**Comment by SagarPC** [comment]
@kbt1 Please see the below image for reference. We updated the date as per your request.

![image](https://user-images.githubusercontent.com/31076567/128460352-b7f76261-a293-48cf-93b1-b26524de9bc8.png)

**Comment by kbt1** [comment]
thank you!
