### ISSUE TITLE
Online Training

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#211]
Hi Sagar:

After you updated the system for the changes you made, there seems to be an issue with users logging in now.
All the new users see are the 2 exams.
this is a group i just added:
[Helena College 2021 Group-Sample.xlsx](https://github.com/stellaballa/AERA/files/7138194/Helena.College.2021.Group-Sample.xlsx)

can you please fix this as soon as possible.
let me know when done.

thank you!

**Comment by kbt1** [comment]
Here is a screen shot after a new user logs in:
![image](https://user-images.githubusercontent.com/26387044/132724994-ee9556c1-c919-41bf-aa66-7f9451203985.png)

**Comment by SagarPC** [comment]
@kbt1 We found that issue and fixed it. We also uploaded on live and not it's showing all chapters. 

There is an issue with new users which you created using bulk entry, we fixed the issue for that screen as well. You can create a new user and verify the same from your end as well.

We checked all functions from our end and it's working for us after fixing.

Please let us know if you have any questions.

Regards,

**Comment by kbt1** [comment]
works good.
thank you!
