### ISSUE TITLE
Correction for a Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#213]
Hi Sagar
can you fixed an entry in a dues batch 9-15-2021kt Date: 09/15/2021 By: Karen Tendering
ID#44877 Marty's Custom & Machine LLC
**dates should be 10/1/2021 to 11/1/2021**
![image](https://user-images.githubusercontent.com/26387044/135641444-86b38cdf-9671-4889-8fd3-8dd8d7980555.png)

let me know when fixed.

thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated the expiration date as you requested. We did this update for the "9-14-2021kt" batch, member# 44877

![image](https://user-images.githubusercontent.com/31076567/135705377-bc1e454e-a9d4-48e4-99df-fa236186285d.png)

**Comment by kbt1** [comment]
thank you!!
