### ISSUE TITLE
Help needed to Fix a Dues Deposit

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#215]
Hi Sagar:
I have a dues batch that needs a couple of fixes.
Batch 11-29-2021kt 
![image](https://user-images.githubusercontent.com/26387044/144123764-0939c647-980c-449f-ae72-ace611338a7e.png)
1. Delete Entire Line 39: ID#44910 Uehling Machine (Steve and I duplicated this entry in 2 batches)
2. Adust # of Trans per Batch to 39
3. Adjust $ Total per Batch to $18,381.00
![image](https://user-images.githubusercontent.com/26387044/144124265-7fc5b12c-37a1-4e3b-8e2a-6b5482e6774b.png)

please let me know when done and I will rerun report and make sure it all adjusts properly.
if you have any questions, let me know.

Thank you!
Karen

**Comment by kbt1** [comment]
forgot to assign this to you.

**Comment by SagarPC** [comment]
@kbt1 We updated the record as you requested. Please see the below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/144429354-30217043-e307-4a86-9b1e-69aa50cdcbe6.png)

**Comment by kbt1** [comment]
perfect, thank you!
