### ISSUE TITLE
Searching By Size - MM

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#216]
When searching by size (see picture below) and you select MM, we think it is searching by the +/- .005" dimension that was provided by AERA. Actually if the user selects MM, is should search +/- .127 MM. The .005" stays the same for inches and needs to be updated to .127 MM on the MM Side. 

Any questions, let me know. 

![image](https://user-images.githubusercontent.com/26387391/147588324-c6c8e9c5-625e-4351-805a-68dfa09e06ea.png)

**Comment by SagarPC** [comment]
@stevefox3781 ,

We did the request change and uploaded on live.

**Comment by stevefox3781** [comment]
Thank you!
