### ISSUE TITLE
Online Certification Update - Fix to Layout of Page-Add a New User

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#217]
Hi Sagar
One thing I just noticed that I didnt before, when I add a student, the page seems out of order.
![image](https://user-images.githubusercontent.com/26387044/156213500-0b3a2045-f601-4a44-8d93-526933811f8b.png)

**This is how it should be arranged:
Member ID# Company Name
Address City
State Postal Code 
Country Phone**

otherwise, everything looks great.
I love how the account start date is automatically figured with the expiration date.
the new program has a great look to it!

**Comment by SagarPC** [comment]
@kbt1 , It is done.
![image](https://user-images.githubusercontent.com/31076567/156315920-2be36be9-2930-4352-bb79-6da8c3eb3483.png)

**Comment by kbt1** [comment]
perfect. thank you!
