### ISSUE TITLE
MMS- Monthly Report

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#22]
Under Active Member Locator - Website report
Can you have it pull the Shipping address and if the shipping address is blank, have it do the mailing address.  

These addresses are used to look up members online and the shipping address is their physical address and the PO Box could be in a different city or miles away and not where they are located.

Let me know if you have any questions.

**Comment by SagarPC** [comment]
We have done with this change and uploaded on production. Please check and confirm.

**Comment by kbt1** [comment]
looks good.
