### ISSUE TITLE
Dues Batch Fix- Feb 11 Monthly Credit Card Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#220]
Hi Sagar
I just found a couple mistakes I need your help fixing.
1. rename this batch to 2-11-2022 Monthly Credit Card Batch
2. there are 2 transactions that need to be allocated to a correct ID#.
![image](https://user-images.githubusercontent.com/26387044/156418415-fed0d112-a374-4745-a04e-77113df66780.png)

Line 189 $32.41 and Line 191 $35.22 change to ID#44812 
everything else is good.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated batch as you requested, please check and confirm our update.

Regards,

**Comment by kbt1** [comment]
all good, thank you!
