### ISSUE TITLE
Online Training - Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#221]
Hi Sagar

I am getting not connected, verify network again when i try to add someone to the system.
I logged in under Amanda's info and got the same error.
Amanda logged in under her login info and mine and has no issue.

Do you have any ideas?

**Comment by SagarPC** [comment]
@kbt1 I think there is something network security related stuff in your PC which not allowing Ajax request. 

Can you please ask your network guy to check Ajax request policy, it should allow aeraedu.com to send Ajax request.

Please let us know if you have any questions.

Regards,

**Comment by kbt1** [comment]
i will have this looked at. thank you.
