### ISSUE TITLE
Dues Batch Name Correction

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#222]
Hi Sagar
I need a batch name corrected.
2-2-2022kt   Date: 02/22/2022   By: Karen Tendering

**should be 2-22-2022kt**

Thank you!

**Comment by kbt1** [comment]
Sagar - correction to above. The batch should be 2-2-2022kt date: 02/02/2022.

**Comment by SagarPC** [comment]
@kbt1 I just want to make sure about the correct batch update, please see below for the batch which I will update. I will update "Date: 02/22/2022" with "Date: 02/02/2022", please correct me if I am wrong?

![image](https://user-images.githubusercontent.com/31076567/156744792-8ad6bdc9-c580-47f5-8dc6-a724649a5b7b.png)

**Comment by kbt1** [comment]
Batch name - 2-2-2022kt and date 02/02/2022
yes, that is correct for the change.

**Comment by SagarPC** [comment]
@kbt1 We updated date as you requested. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/156783865-0c57677d-c081-4693-a9ce-2bd23ca76f7f.png)
