### ISSUE TITLE
Online Certification - notification of completion seems broken

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#223]
hi Sagar.
I have not seen any completions since we went live with new system.
I just had someone pass. 
Ajit Dbrass
Login: ajit
password: atdbrass
can you pull a list of anyone that has completed course since March 1.
Also, can you check the same for SamTech. Any Midterm, Head or Block exams passed.

Thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 , Here I attached list of aera and semtech students who has passed the exams. I also found one issue which prevents send mail to admin, it will complete till tomorrow.
[Aera.xlsx](https://github.com/stellaballa/AERA/files/8253993/Aera.xlsx)
[Semtech.xlsx](https://github.com/stellaballa/AERA/files/8253990/Semtech.xlsx)

**Comment by kbt1** [comment]
thank you for the lists.

**Comment by SagarPC** [comment]
@kbt1 , Issue has been resolved. Now admin( karen@aera.org ) will receive the mail on completion of the course.

**Comment by kbt1** [comment]
it is working again. thank you!
