### ISSUE TITLE
SamTech Online Certification Program

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#227]
Hi Sagar
I just added a few new students under SamTech and I beleive when I add them their expiration date is supposed to be 2 years because their course is a 2 year course. Only the AERA side gets 1 year.
Can you update that please?

Thank you!

**Comment by SagarPC** [comment]
@kbt1 Yes, we can do that change. We will do that by tomorrow and send you an update on this.

**Comment by kbt1** [comment]
thank you!

**Comment by SagarPC** [comment]
@kbt1 ,
It is done.
![image](https://user-images.githubusercontent.com/31076567/161047107-a552ba29-f784-4f93-9c50-615939cf4414.png)

**Comment by kbt1** [comment]
thank you!
