### ISSUE TITLE
MMS Dues Batch Correction 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#228]
Hi Sagar
Batch 3-10-2022 Monthly Credit Card.
![image](https://user-images.githubusercontent.com/26387044/160657378-c555b672-2ab5-487a-b868-f4e1bb7cf5c8.png)

can you please change the Member ID#44823 for lines 571 and 573 to **ID#44812**
ID#44812 Membership $32.41
ID#44812 Prosis 35.22

thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated record as you requested.

**Comment by kbt1** [comment]
perfect, thank you. I updated my spreadsheet so i dont import it next month incorrectly.
