### ISSUE TITLE
Prosis Pro Login

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#23]
I have heard from 2 members today that when they login to Prosis Pro in IE, they enter their user name and password, login and it takes them back to the login screen.
They were both Napa stores that dont have access to download anything on their computer.
I suggested having them use Google Chrome and they will check with their IT Department to see if it can be changed.

Could it be the version of IE they are using?

**Comment by SagarPC** [comment]
@kbt1 / @stellaballa 

We have checked with all below OS and IE version and all working fine from our end. I think there is something wrong with they network or anything else. 

Windows: XP IE6 : working
Windows: XP IE7 : working
Windows: XP IE8 : working

Windows: 7 IE8 : working
Windows: 7 IE9 : working
Windows: 7 IE10 : working
Windows: 7 IE11 : working

Windows: 8 IE10 Metro : working
Windows: 8 IE10 Latest : working

Windows: 8.1 IE11 Metro : working
Windows: 8.1 IE11 Latest : working

Windows: 10 IE11 Latest : working
Windows: 10 IE14 Edge : working
Windows: 10 IE15 Edge : working

**Comment by kbt1** [comment]
I will keep track of this if it continues.
