### ISSUE TITLE
Prosis Pro Desktop Install on Windows 11

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#232]
Hi Sagar
I have a member who installed Prosis Pro on their new windows 11 computer and we can not activate their license.
Software ID
BFEBFBFF000AO653
Software License Key
C51E-D116-1DBA-1934-DFF3-A68C-DED7-BC4F   I generated this in MMS

Software ID
BFEBFBFF000AO653
Software License Key
C51E-D116-1DBA-1934-943F-7142-340D-A0F4    I generated this on Prosis Pro under My Account.

neither are working so I am not sure if its a windows 11 issue or something else.
can you let me know.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 can you please ask members to send a screenshots like which error they are facing? 

We will try to install in windows 11 check.

**Comment by kbt1** [comment]
It just says "Invalid License"
I will see if she can send a screen shot. She isnt very computer literate.

**Comment by kbt1** [comment]
BFEBFBFF000AO653  --- It was my mistake......i had a letter O instead of number 0 before the 653 in the software ID#.
I finally noticed it, gave them a new license and it works.

**Comment by SagarPC** [comment]
Ok, Thanks for the update.
