### ISSUE TITLE
Updated Online Certification Database

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#233]
Hi Sagar

I have run across a few records with the student login name as Karen and that is not the correct login.
I keep a spreadsheet of everyone i add.
Can you run a report and see how many other records come up with a login as Karen?
these need to be fixed so users can log in.

thanks!

**Comment by kbt1** [comment]
![image](https://user-images.githubusercontent.com/26387044/164315157-84d1d7e4-7f4c-413c-aa1e-4a2ba4b401fe.png)

i think it might be linked to our password software. but if you can double check on logins, that would help verify.

**Comment by SagarPC** [comment]
@kbt1 We checked and not found only 1 user with the Karen username and it's a admin. Also it's not linked with any other password software, I checked backed as well. 

Please let me know if you found same things again.
