### ISSUE TITLE
MMS- Membership and Prosis invoice wording change

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#234]
Hi Sagar,
On the attached membership renewal, it is for a 6 months renewal, however, it says annual renewal.
Can this be changed so anyone on the 6 month renewal plan, the wording says 6 months?
I didnt even realize this until a member asked how this is a 6 month renewal and it says annual.
Let me know

[6 month membership renewal - wording change.pdf](https://github.com/stellaballa/AERA/files/8584508/6.month.membership.renewal.-.wording.change.pdf)

if this can be changed, it needs to be for emailed invoices and printed invoices.
thank you!

**Comment by SagarPC** [comment]
@kbt1 Yes, it's possible we will do that and inform you.

**Comment by SagarPC** [comment]
@kbt1 Currently we have different Payment plan for the Membership and Prosis Pro. Is there possible like some members have 6 Month plan in membership and Yearly plan in Prosis Pro. If this is the case then we have to list payment plan with the amount dues or some other ways.

![image](https://user-images.githubusercontent.com/31076567/166240376-263949cb-4bea-4860-b6bc-23d58f8133d7.png)

**Comment by kbt1** [comment]
Yes, we have membership that do a monthly payment plan on one and pay the other Annually, or 6 months on one and annually on the other.   However it can be done would be good.

**Comment by SagarPC** [comment]
@kbt1  In this case we can update the copy of the invoice something like below. Where we can remove payment plan information from the paragraph and add that information along with amount. Please let us know your thoughts or any other suggestion for this.

![image](https://user-images.githubusercontent.com/31076567/166252917-6ffb5059-12d9-47a7-94e3-fb899b9c8689.png)

**Comment by kbt1** [comment]
Can you rearrange the wording so it is (6 month) Amount Due: $199.50?

please make the wording "6 Months"  and  "Annually"

**Comment by SagarPC** [comment]
Ok, we will consider this and upload it on live by tomorrow.

**Comment by SagarPC** [comment]
@kbt1 , It is done.
![image](https://user-images.githubusercontent.com/31076567/166454579-228c207d-281a-4e89-ba11-e0726390e241.png)

**Comment by kbt1** [comment]
looks good.
thank you!
