### ISSUE TITLE
Dues - Price Increases

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#235]
Hi Sagar
We had price increases that I entered in MMS under System Setting, Pricing.
Membership comes up correctly in dues however, if I enter a Prosis Payment, its coming up with old pricing instead of new.
as of July 1, price increases.
can you look into this please? I manually changed the incorrect amounts in my current batch.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 can you please provide more detail, where you are facing this issue? Is it inside Membership Add/Edit screen or Monthly dues export excel file? If you could provide screenshots then it will also help.

**Comment by kbt1** [comment]
Hi Sagar, 
This is happening in the DUES Processing System.
I have an open batch "Sagar Sample Batch" for you to see.
This company expires July 1, so both their membership and prosis fees should be the new prices.
However, only the membership fee is correct.
**The prosis fee is $600 which is still the old fee and should be $730.00**
![image](https://user-images.githubusercontent.com/26387044/169061732-5dfd91d8-2f13-4842-a39b-5a29c8828075.png)
See System Settings / Pricing, all the New Fees as of Date is 7/1/2022. 
Hopefully this explains it better.
let me know if you have any questions.

**Comment by SagarPC** [comment]
@kbt1 , It is done. I deleted my sample created batch.
![image](https://user-images.githubusercontent.com/31076567/169285304-ca0c9100-5611-4e36-b98f-f3cd2ba7cd18.png)

**Comment by kbt1** [comment]
I tested it and it is now correct. thank you!
