### ISSUE TITLE
Need correction done to Dues Batch in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#236]
Hi Sagar
Can you make a correction to a batch for me:
Batch= 5-25-2022 Monthly ACH Batch
Replace ID#43160 for 2 transactions to ID#44994
![image](https://user-images.githubusercontent.com/26387044/170566950-9dee39c9-7fd7-44a5-8d94-028aa034d847.png)

let me know when done.
thank you!

**Comment by SagarPC** [comment]
@kbt1 We update id# as you requested. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/170694707-1cd96072-401c-4245-a1ac-95bbe41d8276.png)

**Comment by kbt1** [comment]
Thank you very much!
