### ISSUE TITLE
Product Order Form in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#237]
Hi Sagar:
this is nothing new but i am finally asking for this to be corrected.
When in the product order form, if you hit the enter key instead of send email, you lose everything.
can you update so either it just automatically sends if you hit enter or does nothing.
If I am taking a renewal or an order and end the call, if i finish the product order and hit enter, i lose everything and have to call the member back.
![image](https://user-images.githubusercontent.com/26387044/173879108-54af14e3-bf25-4b65-b440-c447b5f0460d.png)

let me know if you can update this easily.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 Let me check. We can fix it easily. We will do that and inform you.

**Comment by SagarPC** [comment]
@kbt1 We disabled enter key on live. Please check and let me know if any other changes required.

**Comment by kbt1** [comment]
It still seems to clear the screen.

**Comment by SagarPC** [comment]
@kbt1 can you please reload the screen using CTRL + F5 and check. If you are still facing the issue then please send the video recording if possible. It will help me to understand your process.

**Comment by kbt1** [comment]
If you type in credit card details and this sample and hit enter, clears the screen before you enter anything in the top fields either for membership, prosis or under item# and description.
![image](https://user-images.githubusercontent.com/26387044/174621016-d9ee2f38-f7f6-432f-88b1-056f954a73c5.png)

If you fill in the screen as shown here, and type in the card holder name and and hit enter instead of send email, the form clears the screen.
![image](https://user-images.githubusercontent.com/26387044/174621543-588fe053-753a-4d12-8c17-92617047b0dc.png)

When you hit enter, the form clears screen and brings you here:
![image](https://user-images.githubusercontent.com/26387044/174621707-8e488df6-c05d-4bf9-b7b4-0f9c8ea3eda8.png)

**Comment by SagarPC** [comment]
@kbt1 We fixed this issue, please check now. It should work. We stop enter key function on this screen.

It should work now.

Regards,

**Comment by kbt1** [comment]
perfect. Thank you!
