### ISSUE TITLE
Correction for a Dues Batch in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#238]
Hi Sagar,
I found an error that needs to be corrected.
Batch name: 6-22-2022KT

There are 2 transactions under ID#23159
can you correct the transaction highlighted below to Prosis instead of Membership. Nothing else needs to be changed.
![image](https://user-images.githubusercontent.com/26387044/176544978-1337c77b-f8fc-4c7a-b39c-c431db528190.png)

Thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated record as you requested.

![image](https://user-images.githubusercontent.com/31076567/176604939-33298c24-7e8f-4fbf-b1e2-5d4f41e5776a.png)

**Comment by kbt1** [comment]
thank you!
