### ISSUE TITLE
Dues Batch Correction

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#239]
Hi Sagar
Can you please make a correction to a transaction in a dues batch:
batch 6-15-2022 kt #3 should be Prosis for $41.58, NOT Membership.
![image](https://user-images.githubusercontent.com/26387044/178269807-4c66984b-cd91-4268-8c02-2616d6aea827.png)

thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated record as you requested, please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/178288725-8d48eacc-e1cb-4bdf-baf2-161495d2a39e.png)

**Comment by kbt1** [comment]
great, thank you!
