### ISSUE TITLE
MMS- Monthly report

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#24]
Under Monthly Report Tab
Monthly Call Reports
I enter a date and usually it just opens the spreadsheet and I can save it after that.
Now when i enter a date, it asks me to save it first and then it opens.

Can you put it back to opening and then i can save it if i choose to.

**Comment by SagarPC** [comment]
@stellaballa 

Please see below for our findings and let us know if any action required.

I have tried with IE 11 and there is 2 option like open and save.

![image](https://user-images.githubusercontent.com/31076567/30842968-bbeaaad4-a2a3-11e7-8ec1-b72c55629299.png)

I have tried same with Chrome and there is no option like option, it's automatically download as it's browser functionality.

**Comment by kbt1** [comment]
All the other reports just open, they do not require you to save it before you open it. 

![image](https://user-images.githubusercontent.com/26387044/30878183-b5ff0c5a-a2c1-11e7-9ed2-664c45c3fb4f.png)
