### ISSUE TITLE
Dues Batch Correction #2

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#240]
Hi Sagar
can you make a correction to the following dues batch please:

07-06-22SF 
#2 should be Prosis NOT membership and Due column should be $265 NOT $230.

![image](https://user-images.githubusercontent.com/26387044/178275210-3a63a852-2208-4d7d-bb86-4bc527242e04.png)

thank you!

**Comment by SagarPC** [comment]
@kbt1 We updated record as you requested. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/178287980-de0760ed-1b0a-4941-85c0-c4e0b979eaec.png)

**Comment by kbt1** [comment]
perfect! thank you!
