### ISSUE TITLE
Prosis Pro Desktop Update for 2022

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#241]
Hi Sagar:
Once you are done with the Spanish update in Prosis Pro you are working on with Fernando, we need to get a flash drive out to Prosis Pro Desktop users. We have some members using the desktop that dont have internet or slow internet and we dont want to lose them due to no update. 

Can you let me know when this can be done so we can prepare?
Thank you!

**Comment by SagarPC** [comment]
@kbt1 I will check and make list of changes which are pending in Windows and send you and update like how much time it will take to update windows in this week.

**Comment by kbt1** [comment]
thank you. please copy Steve in the email also.

**Comment by SagarPC** [comment]
I replied in email for the estimation, you could received that.

**Comment by kbt1** [comment]
received, thank you!

**Comment by kbt1** [comment]
Hi Sagar
I am hoping now that the Spanish update work is done, we can focus on getting a desktop update ready to ship for Sept. I am receiving a lot of requests.
Let me know if this is possible. It would be nice to get it out Sept/Oct.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 We are almost done with the desktop update as well. We can send it to you with in next 2 week. We are doing testing with windows 10 and windows 11 and will be completed within 1-2 week.

**Comment by kbt1** [comment]
awesome, thank you for the update!

**Comment by SagarPC** [comment]
@kbt1 Please download latest PROSIS PRO windows application from below URL. It's contains data till 30th Aug 2022.

http://192.151.160.217/aerastage/prosisproexe/9.0.0/ProsisPRO_9.0.0.exe

Please install it from your end and let us know if you are facing any difficulties.

We will move same on live if everything is good from your end.

Please let us know if any questions.

**Comment by kbt1** [comment]
Steve and I both installed and all is good.

**Comment by SagarPC** [comment]
@kbt1 We updated 9.0 version on Prosis Pro live. User can download from there. This new software will support Window 10 and 11 both.

![image](https://user-images.githubusercontent.com/31076567/188073120-2dd70f41-e795-4d4d-b0b2-b997b5574d3f.png)
