### ISSUE TITLE
Update a Report-Membership and Prosis Country Counts

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#242]
Can you update this? I believe you ran these both for me last year. they are for AERA MidYear Board Meetings.
Membership Country Count
Prosis Country Count
see attached spreadsheets.

date as of 6/30/2022 all current exp dates pulled.

thank you!
[Membership by Country Count 2021.xlsx](https://github.com/stellaballa/AERA/files/9142671/Membership.by.Country.Count.2021.xlsx)

[Prosis Pro Country Count 2021.xlsx](https://github.com/stellaballa/AERA/files/9142672/Prosis.Pro.Country.Count.2021.xlsx)

any questions, let me know.
thank you!

**Comment by SagarPC** [comment]
@kbt1 Please see attached file for requested report. Please check and let us know if any change required.

[Membership-by-Country-Count.2022.xlsx](https://github.com/stellaballa/AERA/files/9150072/Membership-by-Country-Count.2022.xlsx)

[Prosis-Pro-Country-Count-2022.xlsx](https://github.com/stellaballa/AERA/files/9150073/Prosis-Pro-Country-Count-2022.xlsx)

**Comment by kbt1** [comment]
perfect. thank you!
