### ISSUE TITLE
MMS Dues Batch Correction

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#243]
Hi Sagar
Can you make a correction to dues batch for me:
7-18-2022kt   Date: 07/18/2022   By: Karen Tendering
Transaction #32 should be for Prosis Pro (not membership)
![image](https://user-images.githubusercontent.com/26387044/181288350-ddf482e4-22c2-4562-87a8-4126b29c02fa.png)

Thank you!

**Comment by SagarPC** [comment]
@kbt1 Updated record as you requested. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/181443762-022a399d-e57d-458e-8541-4c53a61d7144.png)

**Comment by kbt1** [comment]
thank you!
