### ISSUE TITLE
Prosis Pro Online Demo-Login Not Working

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#244]
Hi Sagar:
We have a company that signed up for the online demo of Prosis Pro. 
He actually signed up 2 times because the first one didnt work.
He emailed Amanda and asked her about it. She and I both were unable to login with his credentials.

He would like to look over Prosis Pro before he joins but is unable to.

![image](https://user-images.githubusercontent.com/26387044/183510569-b930d1eb-97b0-4b37-ac81-eb421f0e7af9.png)

here is his confirmation for the first login: 
![image](https://user-images.githubusercontent.com/26387044/183510801-e328252a-5d90-445b-b281-da37c4b16536.png)

here is his confirmation for the second login:
![image](https://user-images.githubusercontent.com/26387044/183510879-c7c15b2f-b00f-4183-b9ca-874f723ba35d.png)

can you check why it wont work and let us know?

Thank you!

**Comment by kbt1** [comment]
It says error: username or password incorrect.

**Comment by SagarPC** [comment]
@kbt1 Please check now. It should work. We fix this issue for the demo login.
