### ISSUE TITLE
Dues Batch Needs Fixing

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#245]
Hi Sagar
Can you fix the following for me:
9-9-2022 Monthly Payment Credit Card BatchDate: 09/09/2022By: Karen Tendering
2 entries under this batch need to be fixed
Number 626 and 627 should be Member #937.

![image](https://user-images.githubusercontent.com/26387044/190003412-b8d3a44b-7dfc-481e-a8c0-264260c6ea79.png)

Thank you!

**Comment by SagarPC** [comment]
@kbt1 

We updated record as you requested. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/190092815-392c73cb-8802-43c7-a4ab-f6e9124ec5cc.png)

**Comment by kbt1** [comment]
thank you!
