### ISSUE TITLE
Prosis Pro Desktop File

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#247]
Sagar
I emailed this but I wanted to send this here also.

![image](https://user-images.githubusercontent.com/26387044/190204060-cc5b3fb1-b2a5-47d0-9c89-494d0b19fc3a.png)

having issues copying the files to flashdrive.
what button do we select?

**Comment by SagarPC** [comment]
@kbt1  You can simply click on "Yes". It's because of Drive format variation.

**Comment by kbt1** [comment]
thank you. i will check this out and if i have more issues, i will let you know.
