### ISSUE TITLE
MMS- Conference Tab Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#25]
In MMS under conferences tab
on page 2 of conferences, AERA & PERA PRI VIP Party
when I click on View Details, i get this error page

![image](https://user-images.githubusercontent.com/26387044/30919946-6546a2b2-a368-11e7-991d-0aca02273bd1.png)

**Comment by stellaballa** [comment]
@kbt1 working on it.

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue and uploaded on production. Please check and confirm.

**Comment by kbt1** [comment]
looks good
