### ISSUE TITLE
Prosis Pro Desktop Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#251]
If you go under Detroit Diesel 60 series & selecting 12.7 liter you will get the following error:
![Screenshot 2022-09-28 153148](https://user-images.githubusercontent.com/26387044/192875307-9080e816-b4ed-4e93-9350-6b4b856084a1.jpg)

please let me know what the fix is.

**Comment by kbt1** [comment]
Also, just an fyi: the database version number after the download is V5.3 and should be V9.0.

**Comment by SagarPC** [comment]
@kbt1 We found cause of this issue and will send updated exe by tomorrow, also update same new version on live.

**Comment by kbt1** [comment]
does this mean I have to send out new updated flashdrives?

**Comment by SagarPC** [comment]
**Either** we can send updated flashdrives with new setup **or** we can send patch file with instruction, because it's change in windows exe so update is required.

If this user can give us access then we can make direct change in his machine as well.

Please let us know how you would like to move forward.

**Comment by kbt1** [comment]
A new exe file is fine. I can send the 35 updates out again with a note.
Do you know if this error comes from just the Detroit Diesel engines or does if effect more?
Can you send a brief description of error so i can inform members?

**Comment by SagarPC** [comment]
This error affect all those engine where we have parts available. Please see below image for your reference.

![image](https://user-images.githubusercontent.com/31076567/193070821-7ce04b13-e5ea-4e84-98bb-b2482bbef5a1.png)

**Comment by kbt1** [comment]
oh, ok!

**Comment by SagarPC** [comment]
@kbt1 We found few more issue after fixing this Engine Parts issue. We are working on that it will take 2-3 days more for us to fix and re-deploy. We will try to send you updated file asap.

Regards,

**Comment by SagarPC** [comment]
@kbt1 We uploaded new exe on Prosis Pro website and you can also download it from below link.

https://www.dropbox.com/s/b8e5c0nlomrc8r8/ProsisPRO_9.0.0.exe?dl=0

**Comment by SagarPC** [comment]
@kbt1 We updated latest software on Prosis Pro live and you can download it from below link as well. Please install this in one of your computer to check downloaded file.

https://www.dropbox.com/s/b8e5c0nlomrc8r8/ProsisPRO_9.0.0.exe?dl=0

**Comment by kbt1** [comment]
thank you Sagar, i will have Valley Computer download it.

**Comment by kbt1** [comment]
downloaded fine. version # updated and engine search with parts link works.
