### ISSUE TITLE
Updated Prosis Pro Desktop 9.0

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#252]
I was looking up a Detroit Diesel 60 Series 1986-1998 and there is a procedure, nothing is there.
![image](https://user-images.githubusercontent.com/26387044/194082443-2e337f54-a1d2-4d7d-a828-40283af14482.png)

I looked at same engine in Prosis Pro Web
![image](https://user-images.githubusercontent.com/26387044/194082530-2e45f854-149d-4a97-81aa-2c1a0d259c97.png)
the pdf is there to click and open.

can you check this out before I start doing flash drives.

**Comment by kbt1** [comment]
desktop:
![image](https://user-images.githubusercontent.com/26387044/194082890-a35e9f63-336c-4ece-b0dc-44cfb9c7d1af.png)

above are both the same for web version.

**Comment by kbt1** [comment]
Note: Steve didnt know if this procedure was added after you pulled the data.

**Comment by SagarPC** [comment]
@kbt1 We updated all missing PDFs in windows application as per the database and uploaded exe in Dropbox under below link. 

https://www.dropbox.com/s/trv7w5qgvm15xhr/ProsisPRO_9.0.0.exe?dl=0

We can also download latest data from Prosis Pro web and create new windows application with updated data till yesterday.  It will take 1-2 days only. 

Please let us know your thoughts on this.

Regards,

**Comment by kbt1** [comment]
Hi Sagar,
Yes, pull all updated data and create a new update.
Also correct the print function for the Windows 11 Formatting Issues.
Send me a new link when you are done.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 Please see updated exe on below path. Also, we updated same on Prosis Pro web. Please download and install in your one for the machine to be make sure about downloaded file.

https://www.dropbox.com/s/b20gyajblm78mur/ProsisPRO_9.0.0.exe?dl=0

**Comment by kbt1** [comment]
Sagar,
The version is still Database Verion V5.3? Everything else looks good.
![image](https://user-images.githubusercontent.com/26387044/195146321-a4588753-ddc1-4396-bdb7-198372eef1ae.png)

**Comment by SagarPC** [comment]
@kbt1 Sorry for this inconvenience, it might be revert with the live db update with latest engine and other information.

Please try below link, we updated version 9.0 in this.

https://www.dropbox.com/s/5vudgzpg8c5z663/ProsisPRO_9.0.0.exe?dl=0

**Comment by kbt1** [comment]
good to go. thank you!
