### ISSUE TITLE
Opt out of Engine Professional

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#253]
I've had a couple members who no longer want to receive their physical copy of the magazine.  Would it be possible to add something like we did for the manuals (circled in image) for EP? We'll also need an option under reports to see who selected what like we have for the manuals. 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/26386841/194637221-3686354a-7ea7-4c0a-9482-a1b8f1f9c560.png">

**Comment by SagarPC** [comment]
@amandagoyette  Please see below image for reference, we can add that option under "EP" tab and also export that selection with EP "Export Report" and "Subscriber Report". It will take 4-5 hours to implement the change and upload.

![image](https://user-images.githubusercontent.com/31076567/194851117-afd760ab-6a33-4e2a-a132-e786b3a85424.png)

**Comment by amandagoyette** [comment]
@SagarPC that location works for the EP tab.  We need to make sure it's offered under the members tab too. I've gotten the okay to proceed based on your projected time from Jim and Steve.  Thanks!

**Comment by SagarPC** [comment]
@amandagoyette Ok, so we need "Receive magazine type" checkbox in EP tab and Members tab both. We will do that and inform you asap in this week.

**Comment by SagarPC** [comment]
@amandagoyette We uploaded this change on Live. Please check Membership, EP and Reports for this change and let us know if any other changes required.

**Comment by amandagoyette** [comment]
I had to pull a list today and tested the last piece of this function it all seems to work. thank you!
