### ISSUE TITLE
Printing in Prosis Error

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#256]
Sagar
I have a member who took the attached screen shot.
This is while he is printing in Windows 10.
[Error.pdf](https://github.com/stellaballa/AERA/files/10376143/Error.pdf)

any ideas?

please let me know.

Thank you.

**Comment by SagarPC** [comment]
@kbt1 We tried but not able to reproduce it from our end. 

Can you please provide this user (member/company) name so we can check with that specific user login?

**Comment by kbt1** [comment]
Member ID#44900
Mark Richardson
Login: A1IndMach
Password: a1mark

i logged in under his account and had no issues. 
he said this is the first time this has happened.
do you know what that error means?

**Comment by SagarPC** [comment]
@kbt1 We tried with user account and also find engine where they faced issue before 2 days but today when I tried same it's working fine for us.  They tried to download below PDF for https://www.prosispro.com/EngineSpecificationDetails.aspx?eid=9940 engine.

[SUBARU-IMPREZA-01-11-20234983.pdf](https://github.com/stellaballa/AERA/files/10392369/SUBARU-IMPREZA-01-11-20234983.pdf)

Can you please ask them to try now and inform us if they are facing same issue again?

Regards,

**Comment by kbt1** [comment]
will do. thank you.

**Comment by kbt1** [comment]
member says things are printing and working correctly again.
