### ISSUE TITLE
MMS - Printing and Emailing Invoices

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#257]
Hi Sagar,

I pulled up Expired Dec 1 members and tried single and batch emails to send invoices and nothing happened.
I also tried printing. it didnt work and then it did. 
Can you look into both functions. I should be able to print and email current and expired members with the only exception of monthly payment members.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 Please see below image for the selection are you trying with same selection? Please let me know if there is any change in selection.

_FYI: We are not generating invoice and email invoices for monthly subscriber. This check we added from the is from the beginning of software. Please let us know if any change required in this specific logic._

![image](https://user-images.githubusercontent.com/31076567/212044290-628f3ca3-6de5-4e18-b6b6-9a4fe0228048.png)

**Comment by kbt1** [comment]
you are correct, monthly payment members do not get emailed.

but there are 28 for Dec 1 expired and when i select all and click on email, nothing happens.
![image](https://user-images.githubusercontent.com/26387044/212082784-3a914dea-7086-47ba-b4a2-1265390bacc8.png)

the same thing happens with Jan 1, 34 expired members, i select all and nothing happens when i click email.
![image](https://user-images.githubusercontent.com/26387044/212083023-7426c6ea-7b6f-420d-bb96-0ec28dd73a5b.png)

**Comment by kbt1** [comment]
It seems the email function is broken. I even tried someone who expires Feb 1 and it wont work.
![image](https://user-images.githubusercontent.com/26387044/212084820-535f5cf4-241c-4f43-8897-e6ec50e1b217.png)

**Comment by SagarPC** [comment]
@kbt1 Ok, got that. Invoice print is working but email function not working.

Let us look into this.

**Comment by SagarPC** [comment]
@kbt1 Please check now email invoice function should work. Please see below image, we test with 12/01/2022 expiry date.

Please check and let us know if you are still facing any issue. 

![image](https://user-images.githubusercontent.com/31076567/212321683-e662106a-f966-4cbf-809d-7ad42977c53b.png)

**Comment by kbt1** [comment]
working again. thank you!
