### ISSUE TITLE
Online Training Ch 1 broken images

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#258]
I was reviewing Chapter 1 today and noticed Fig 1 & 2 were broken. I tried to fix then saved and went back to the main screen and came back in to find them broken again.  
![image](https://user-images.githubusercontent.com/26386841/220425993-d5caa13f-afc3-4ebf-afb9-6b555c1ffca8.png)

Can you help fix this? I'm not sure why those two keep breaking.

**Comment by SagarPC** [comment]
@amandagoyette  We are looking into this issue and will fix asap by today.

**Comment by SagarPC** [comment]
@amandagoyette We fixed the issue, can you please try now and let me know if you are still facing any issue.

Regards,

**Comment by amandagoyette** [comment]
Looks good thanks!
