### ISSUE TITLE
Prosis Pro Active Users Number Not Accurate

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#26]
@SagarPC 
The Quick Membership Count Report is not correct. If you look at the number:
Total Prosis Pro: 1363
Total Pro Web: 1220
Total Pro DT: 206
If you add 1220 + 206 = 1426, that's more than total of 1363.
![screen shot 2017-09-28 at 12 12 48 pm](https://user-images.githubusercontent.com/30122790/30985825-6443cd98-a446-11e7-92d5-ff5ff2e9ed9d.png)
Karen download a separate report (attached here), and her number is different from the Quick Membership Count
![screen shot 2017-09-28 at 12 16 02 pm](https://user-images.githubusercontent.com/30122790/30985985-e947f334-a446-11e7-9cd0-dc579fdcfc08.png)

1) This is what we need:
- Total Prosis Pro User
- Total Prosis Pro Web User
- Total Prosis Pro Desktop User
- Total Prosis &Prosis SA User

2) Find out why the numbers on these report don't match in the system and fix them ASAP.

[Prosis Pro Counts in MMS Spreadsheet.xlsx](https://github.com/stellaballa/AERA/files/1342043/Prosis.Pro.Counts.in.MMS.Spreadsheet.xlsx)

**Comment by SagarPC** [comment]
@stellaballa:

Quick report working on below rules that I confirm with Karen. It's showing company count not users count. 1363 is company count and 1390 is user count. There is many company having multiple users.

Please see below image for the reference where I confirm this implementation with Karen. Please let me know if any change required in this implementation.
 
https://github.com/omnitekinc/AERA_MSS_Clients/issues/175
![image](https://user-images.githubusercontent.com/31076567/31070611-9b727630-a77e-11e7-90e9-4cfd35d67578.png)

**Comment by kbt1** [comment]
What we are looking for in this Quick Count Report is:
Total # of Active Companies
Total # of Active Companies with ONLY Prosis Pro active logins
Total # of Active Companies with ONLY Prosis Pro Desktop license keys
Total # of Active Companies with BOTH Prosis Pro active and Desktop License keys
Total # of Companies with neither using old systems

let me know if you have any questions.

Here is a perfect example of how the counts can be off:
This member is marked as a Prosis Pro Desktop on the main page, which I cant edit.
![image](https://user-images.githubusercontent.com/26387044/31087494-dbeba5b8-a762-11e7-80a9-62b86be5ca76.png)
and if you go to the Prosis Pro tab, they are using the web
![image](https://user-images.githubusercontent.com/26387044/31087527-f5ef00a4-a762-11e7-9dc7-22affaf00b7d.png)

**Comment by SagarPC** [comment]
We have done with this change and uploaded on production. Please check and confirm our change. 

If any query please let me know.

**Comment by stellaballa** [comment]
@SagarPC Can you please provide URL for @kbt1 for the production site.

**Comment by SagarPC** [comment]
I sent you detail inside separate email.

**Comment by kbt1** [comment]
Sagar
can you resend the email you mention above, i dont have it.

Stella:
i am attaching a spreadsheet i pulled from the Export Tab.
Most of the users have a YES under Web or Desktop user or both but I have highlighted in YELLOW users that dont have anything marked.  Where do they fall in the user type count?

[Prosis Pro Current Users 10-4-17.xlsx](https://github.com/stellaballa/AERA/files/1362768/Prosis.Pro.Current.Users.10-4-17.xlsx)

**Comment by SagarPC** [comment]
@kbt1 

++++++++++++
Sagar
can you resend the email you mention above, i dont have it.
++++++++++++
**I sent that email to @stellaballa  only as she want live site login and credential.**

++++++++++++
i am attaching a spreadsheet i pulled from the Export Tab.
Most of the users have a YES under Web or Desktop user or both but I have highlighted in YELLOW users that dont have anything marked. Where do they fall in the user type count?
++++++++++++
**Those user listed under "Total # of Companies with neither using old systems".**

Please let us know if any other row required to separate out such users.

**Comment by kbt1** [comment]
This is the count i just pulled today and it says 2 for using old system

Prosis Pro Total   Companies Count | 1341
Prosis Pro Web Companies Count | 993
Prosis Pro Desktop Companies Count | 121
Prosis Pro Web and Desktop Companies   Count | 225
Total Companies Count Who Neither Using   **Old Systems | 2**

the spreadsheet i pulled has atleast 68 Companies with nothing marked so somewhere, wrong info is being pulled

**Comment by stellaballa** [comment]
@kbt1 The 68 companies that have nothing, could those be using the old system?

**Comment by kbt1** [comment]
That is what I am thinking but the counts dont match with the spreadsheet i pull out of the Export Tab.
I have also run into companys that are marked as desktop user but they dont have a software ID or license key issued. I think somehow the records are not marked correctly therefore pulling wrong data.

**Comment by stellaballa** [comment]
@kbt1 Can you share the Excel with us, and mark the incorrect data, we can update it in the system for you.

**Comment by kbt1** [comment]
Stella, i went through and marked all the highlighted records with notes. if you have any questions, let me know. this is a good start. I may go through all records and make sure they are accurate. I am thinking some of these records are wrong from pulling old license info into the new system and as people upgrade to Prosis Pro, I deleted old license info but the record doesnt show it.

There are check mark boxes on the main screen of MMS in each record for Prosis Pro Web and Prosis Pro Desktop,  maybe another one needs to be added for Old Prosis.

Each record needs to be accurate, if they have an active login for web, if they have a license issued for desktop or if neither, using old system.
We need correct counts and we need to be able to pull correct reports if we do desktop updates.

[Prosis Pro Users Highlighted and Marked 10-6-17.xlsx](https://github.com/stellaballa/AERA/files/1363764/Prosis.Pro.Users.Highlighted.and.Marked.10-6-17.xlsx)

**Comment by stellaballa** [comment]
@kbt1 Thanks Karen, will take a look and let you know if we have any questions.

**Comment by SagarPC** [comment]
@kbt1 : We have taken action as suggested and found few missing expired member in that file which I attached here with current status. Please review that file and let us know if any change required for those users.

[pending memebrno which not in client excel file.xlsx](https://github.com/stellaballa/AERA/files/1368275/pending.memebrno.which.not.in.client.excel.file.xlsx)

Also regarding multiple member# inside report, that report per user not per company. Please see below image there we can see like member# 915 having total 8 user and last column represent like that specific user having Prosis Web and/or Desktop.

![user wise flag](https://user-images.githubusercontent.com/31076567/31336008-972528ea-ad12-11e7-84f8-143477389559.png)

**Comment by kbt1** [comment]
Prosis Pro Total   Companies Count | 1341
Prosis Pro Web Companies Count | 992
Prosis Pro Desktop Companies Count | 82
Prosis Pro Web and Desktop Companies   Count | 222
Total Companies Count Who Neither Using   Old Systems | 45

these numbers look better. I will go over with Steve and see if he agrees before closing.
