### ISSUE TITLE
2 Reports Needed for MidYear Meeting

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#264]
Hi Sagar,

Can you pull 2 reports for me, date as of July 1, 2023.
Member Count by Country
Prosis Count by Country

here is what you have done for me:

[Prosis Pro Country Count 2022.xlsx](https://github.com/stellaballa/AERA/files/12040533/Prosis.Pro.Country.Count.2022.xlsx)
[Membership by Country Count 2022.xlsx](https://github.com/stellaballa/AERA/files/12040537/Membership.by.Country.Count.2022.xlsx)

Any questions, let me know.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 Please see attached file as you requested.

[Membership-by-Country-Count.2023.xlsx](https://github.com/stellaballa/AERA/files/12047013/Membership-by-Country-Count.2023.xlsx)
[Prosis-Pro-Country-Count-2023.xlsx](https://github.com/stellaballa/AERA/files/12047014/Prosis-Pro-Country-Count-2023.xlsx)

**Comment by kbt1** [comment]
Thank you!
