### ISSUE TITLE
PROSIS Password Issue

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#267]
Hi Sagar,

Member 2178 had a reminder to update his password. He updated it and it let him in, but when he goes to use the program it kicks him back to the update password screen. He's using Firefox and I've tried to duplicate the issue on my end using Chrome and Firefox with no luck. Anything you can do on your end? 

<img width="508" alt="image" src="https://github.com/stellaballa/AERA/assets/26386841/c28724e4-2a3e-4a1a-b54c-b0e4c9aef845">

**Comment by SagarPC** [comment]
@amandagoyette Please ask them to Sign-out once and try to do login again. 

![image](https://github.com/stellaballa/AERA/assets/31076567/43e9ee6f-c443-43bf-a00c-c5891040f46d)
