### ISSUE TITLE
Cylinder Drop Down - Prosis Pro

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#27]
We think we may be getting some of the custom data from the users in the "Cyl" drop down box in the search box. We would like to have the following list updated for the "Cyl" drop down box if this can be done. I have included a screen shot of what we currently are seeing. Any questions, let me know. 

L 1
L 2
L 3
L 4
L 5
L 6
L 8
H 1
H 2
H 4
H 6
V 2
V 4
V 5
V 6
V 8
V 10
V 12
V 16
V 18
V 20

![image](https://user-images.githubusercontent.com/26387391/31023834-bf6b57e2-a502-11e7-80f1-5d1047ba53cc.png)

**Comment by stellaballa** [comment]
@stevefox3781 will look into this.

**Comment by SagarPC** [comment]
We have resolved this issue and uploaded on stage and production as well. Please check and confirm.

**Comment by stevefox3781** [comment]
Looks good!
