### ISSUE TITLE
MMS-Dues-Not Responding Issue

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#271]
Hi Sagar
I have a regular dues batch and a monthly payment dues batch in the system.
![image](https://github.com/stellaballa/AERA/assets/26387044/e0ab54ce-e06e-4258-8723-9d998d8c18ec)
First i couldnt edit the batch name. 
I finally was able to edit. 
I tried posting:
![image](https://github.com/stellaballa/AERA/assets/26387044/5ab5e0ce-a809-40a4-be43-437a864ffc46)

It finally did post 1 batch. I cant do anything with the monthly batch. Might be getting too large?

I dont think this anything different then i do every month.

seems like its just locked and wont do anything.

could you look into this? 

Karen

**Comment by kbt1** [comment]
I was finally able to post. 
this happened a while ago and you did something in the backend so prevent this.
these are only going to get larger. let me know.

**Comment by SagarPC** [comment]
@kbt1 We are looking into this. 

1) Are you facing this issue in routine or just faces yesterday?
2) Please provide your time zone and duration when you faced this issue?
3) Please provide excel which you used for the Bulk entry.

We are thinking it's because of something happen on sever. However, please provide above detail to investigate more. We will try to reproduce same from our end.

**Comment by kbt1** [comment]
1. this just happened Feb 13th.
2. i was trying to rename and post between 3:30-4:00 pm CST.
3. attached is the spreadsheet i imported.
[2-13-2024 February Monthly Credit Card Batch.xlsx](https://github.com/stellaballa/AERA/files/14280238/2-13-2024.February.Monthly.Credit.Card.Batch.xlsx)

Amanda had VCS check the server and they didnt notice anything. It could have just been a glitch at the time.
i just want to make sure the batches arent getting too large for the import.

let me know what you think.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 Yes, we are looking this from our end.

**Comment by kbt1** [comment]
Sagar,
i have run into this issue again. I cant rename my batch. it just sits there and then i get "not responding."
the box opens to edit the batch details but it wont let me do anything. 
I have a 2nd dues batch and it locks that batch up too.
So both are locked up.
any ideas?

**Comment by SagarPC** [comment]
@kbt1 Last time we did review for this issue and faced slow data load speed on server. The same code and same data loading very fast on our server. 

Your earlier provided image related to "This page isn't responding" it's related to memory/cache issue in your browser. Sometime Edge creating such issue. 

Can you please try same thing with the Google Chrome and check the same things if you have any large batch to post? We can do this testing on stage using your computer. 

However today as your given time 3:30-4:00 pm CST we will do testing on stage server from our end to reproduce same case.

**Comment by kbt1** [comment]
Hi Sagar,
looks like its an Edge Browser issue. I cleared all my browser stuff and it still locked up.
I tried on Google Chrome (which i dont use much anymore) and it worked fine.
So I will do my monthly batches in Chrome and see how it goes.

thank you!
