### ISSUE TITLE
Hide Desktop Install in Prosis Pro Web

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#273]
Hi Sagar,

i dont know if this falls under our monthly maintenance, but we have a lot of members that go to My Account page in Web Prosis Pro and they see the "Get Your Prosis Pro Update" so they click on it not realizing its the desktop download. 
We are trying to get members off the desktop since we are not updating it anymore.
**if this doesnt fall under the monthly maintenance, please email Steve and get his approval before doing so.**

**Can you hide all this:**
GET YOUR PROSIS PRO UPDATE.
Step 1
Click the button to download the update of PROSIS PRO. Total file size 1729 MB.
Step 2
Double click on the PROSIS PRO UPDATE 9.0.0.exe to start setup of the software update.
Choose the proper location where you want the PROSIS PRO application to be saved. Please make sure to choose the same folder of prior installation.
Step 3
Please set up the folder for the “application shortcut”.
Step 4
Please select to create a shortcut icon of Prosis Pro application on desktop or it is o.k. to skip too.
Step 5
Please install the PROSIS PRO update.
Step 6
Please select Repair option and click on Next to repair “Microsoft visual Basic PowerPacks 10.0”.
Step 7
Once the installation is complete please launch PROSIS PRO.
Step 8
When you launch the updated software for the first time, it might take sometime to load data and setup your system.
Please refer to the document for a detailed, step by step installation guide with screen-grab for your reference.

Note : If you have any questions please contact AERA at 815-526-7600 or 888-326-2372 for assistance.

PROSIS PRO DESKTOP COMPUTER SPECS
PLEASE CHECK THE COMPUTERS SPECS REQUIRED:.
Step1
Check your computer to make sure it's running the following system
Windows 7 SP1 (x86 and x64)
Windows 8 (x86 and x64)
Windows 8.1 (x86 and x64)
Windows Server 2008 R2 SP1 (x64)
Windows Server 2012 (x64)
Windows Server 2012 R2 (x64)
Windows 10 (x86 and x64)
Windows 11 (x86 and x64)
Step2
Check your computer to make sure it's following system configuration.
1 GHz or faster processor.
1 GB of RAM.
5 GB of available hard disk space (x86) and (x64).
A USB drive, as appropriate, is required for update software database.
Pointing device: A Microsoft mouse or compatible pointing device is required.
Input device: A Microsoft keyboard is required for input a data.
Printer Color or Black-and-white.
Generate your license key
Please type in the Software ID that's been generated during the installation process and then click the Generate License button. Your software license key will show up. Enter your license key as it appears below in the Software License Key boxes.
Note: You can generate 1 license key on this website. If you have any questions please contact AERA at 815-526-7600 or 888-326-2372 for assistance.

**Comment by SagarPC** [comment]
@kbt1 

We are done with the changes. Please see below image for your reference.

https://prosispro.com/Settings.aspx
![image](https://github.com/stellaballa/AERA/assets/31076567/acf524f0-beae-40b8-9420-0801aa3d950a)

**Comment by kbt1** [comment]
perfect!
