### ISSUE TITLE
New Online Training Site-Testing

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#274]
Hi Sagar,

the link and login for the new online training site is the admin side. The admin side only allows edits.
you cant take any of the tests.

http://71.87.5.35/eduresponsive_PreLive/Login/Index 
UserName: karen
Password: 5jiVsFo

We need logins/site to actually be a student and take the tests.

**Comment by SagarPC** [comment]
@kbt1 You can add student and teacher from your admin login and use that login detail for the Student and Teacher login.

Please let me know if you have any other questions.

Regards,

**Comment by kbt1** [comment]
yes, i can add users.
i thought we were testing the chapters and questions?

**Comment by SagarPC** [comment]
I checked and found that you already created Student account. Please let me know if any there is any issue.

Regards,

**Comment by kbt1** [comment]
Hi Sagar,
Everything is good. If I login under the admin side and make simple changes, will you see it on your end?
There are some simple things like indenting and center or left justifying text. I can fix what I find if it will keep on your end.
let me know if this is ok.

**Comment by kbt1** [comment]
Nevermind on the above. We are creating a document for Steve to submit to you.
