### ISSUE TITLE
Need to update MMS-Renewal Emails

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#275]
Hi Sagar, 
we have changed our website and online store and need 2 links changed.
I beleive these are the correct ones:
Membership: https://aera.org/membership/renew/
Prosis: https://aera.org/prosis-pro/renew-prosis/

this is the current email with renew online links and they dont work.
![image](https://github.com/stellaballa/AERA/assets/26387044/81c1763d-8652-4dfb-ab66-8d90bb24c20c)

Page not found error:
![image](https://github.com/stellaballa/AERA/assets/26387044/5ce18b47-bb6a-4447-be3a-f9393ecd6e56)

can you correct and let me know when done.
Thank you!

**Comment by kbt1** [comment]
https://aera.org/membership/renew/
https://aera.org/prosis-pro/renew-prosis/

**Comment by SagarPC** [comment]
@kbt1 We are done with the live and stage upload. Please check and let us know if there is any issue.

Regards,

**Comment by kbt1** [comment]
thank you!
