### ISSUE TITLE
Error in MMS - Print Membership Certificate Label

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#277]
Sagar,

I got the following error printing a membership certificate label.

![image](https://github.com/stellaballa/AERA/assets/26387044/f0224042-0d0c-4c84-bbcd-cad77d0d1927)

let me know when fixed.

Thank you!

**Comment by SagarPC** [comment]
@kbt1 Please let us know which data you are adding. We tried and it's working for us.

**Comment by kbt1** [comment]
Monthly Report
Member Certificate
Print Mailing Label
![image](https://github.com/stellaballa/AERA/assets/26387044/53b63ac8-5da5-4110-b588-0b1788daef4f)
![image](https://github.com/stellaballa/AERA/assets/26387044/5ae51348-715a-4523-abdd-b565df120708)

this is the error when I print a mailing label. The certificate works just not the mailing label.

**Comment by SagarPC** [comment]
@kbt1 We checked your provided screenshot and notice you are adding Member Number in Date textbox. Please add Member# in correct textbox and it should work. We are adding validation from our end to avoid such confusion in future. 

![image](https://github.com/stellaballa/AERA/assets/31076567/1606ae72-9249-4b98-a505-0e0270d5ebbd)

**Comment by kbt1** [comment]
Sorry, my mistake!
