### ISSUE TITLE
Online Training, Login Letter-Print

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#278]
Sagar,

Can you make the login letter when printed with a larger font.
it prints very small and its hard to read.
![image](https://github.com/stellaballa/AERA/assets/26387044/932bddda-1c02-49ee-9c26-0e9179252a74)
Maybe a 12 or 14 font size?

**Comment by kbt1** [comment]
Also, can you remove the expired list from the New Online Training
![image](https://github.com/stellaballa/AERA/assets/26387044/55bc4fc6-ed9a-4309-b7fc-5b74e9055265)

**Comment by SagarPC** [comment]
@kbt1 I think you are looking into old EDU portal for the expired users. In new portal we don't have any expired users. We have 43 student in new EDU. Please see below image for your reference.

Also, for the font size we will increase and update you.

![2024-Aeraedu](https://github.com/stellaballa/AERA/assets/31076567/8d2ddc3a-9d35-4ca7-9baa-3272f55dcbc9)

**Comment by SagarPC** [comment]
Sorry, I just found expired in new EDU. We will remove all the Expired and inform your asap.

**Comment by SagarPC** [comment]
@kbt1  We are done with the remove expired users and increased font size for the login letter.

**Comment by kbt1** [comment]
both look good.
thank you!
