### ISSUE TITLE
Correction needed in Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#279]
Hi Sagar,

can you make a correction for me in a dues batch.

Batch 6-13-2024kt line 16 ID#44520 change to Prosis, all else is correct.

![image](https://github.com/stellaballa/AERA/assets/26387044/854afee2-30eb-4e2c-a202-3024359879ef)

Thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 Updated record as you requested. 

![image](https://github.com/stellaballa/AERA/assets/31076567/34c628b7-d575-4efa-953d-58671fde2e7d)

**Comment by kbt1** [comment]
thank you!
