### ISSUE TITLE
Prosis Pro Demo online

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#283]
Hi Sagar,

I havent seen any Prosis Demo's in a while. Can you make sure its working. Last new demo i saw was in May or June.
I tried to create a login, and got this error:
![image](https://github.com/user-attachments/assets/e4fe554b-428b-4e68-8616-329a5f740af6)

I usually get a report of demo people that go into the Prospect Tab in MMS. I cant remember if I have seen that either since May.
[Sign up User List _02-02-2024.xlsx](https://github.com/user-attachments/files/16502523/Sign.up.User.List._02-02-2024.xlsx)

let me know if you find anything out on this. 
Thank you!

**Comment by SagarPC** [comment]
@kbt1 There was something wrong with the demo application. I just re-upload all the code and database changes and it's looks working now.

Please try same from your end and let me know if you are still getting any error.

Regards,

**Comment by kbt1** [comment]
if it is simple, can you allow duplicate users/emails? i created a login a few years ago, my emails are both in the system and I can not create a new demo now. if it will cost for reprogramming, dont worry about it. 
otherwise, looks to be working again. thank you.

**Comment by SagarPC** [comment]
@kbt1  Please try to register with "karen@aera.org" email again. I removed your old demo account.

**Comment by kbt1** [comment]
Demo trial works. I clicked on an engine for specs and this is the error i got, i dont know if this is right or not.
![image](https://github.com/user-attachments/assets/033bd1f6-a1ff-471a-ba15-976dffe20163)

this is the engine i clicked on 
![image](https://github.com/user-attachments/assets/e3e8a808-3c73-4db7-b752-ca6c232b98ee)

i know there are only certain engines that allow specs.

**Comment by SagarPC** [comment]
@kbt1 It should work now. I fixed this issue on demo and tested other function.

**Comment by kbt1** [comment]
works perfect, thank you!
