### ISSUE TITLE
Correct a Dues Batch

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#285]
Hi Sagar, 

the wrong ID number was entered and posted in a dues monthly payment batch which i didnt catch.
can you please correct the ID#?
It should be **43510** NOT 45310.
![image](https://github.com/user-attachments/assets/229e0b8e-3511-4549-936e-2c1ae03efac4)

thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 We updated record as requested. 

![image](https://github.com/user-attachments/assets/978cf2fd-4c39-4d1f-9091-6eb2e53f4f15)

**Comment by kbt1** [comment]
i more correction i missed, can you make the Prosis, single user us.

thank you!

**Comment by SagarPC** [comment]
@kbt1 updated Prosis to Single User US.

![image](https://github.com/user-attachments/assets/cd643f8a-1258-420e-b6ef-5694afbc158e)
