### ISSUE TITLE
2024 Online Training

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#286]
Sagar,

we have a school that has 67 students signed up right now and maybe 30 more to come. on the admin side, i see all the students listed under the group. On the instructors side, you only see the first 50.  Can you please fix this. 

![image](https://github.com/user-attachments/assets/7c4dcd3a-9c1b-4d5d-b98e-2bb22fcdeb7b)  admin dashboard

![image](https://github.com/user-attachments/assets/c9352a82-e452-43f8-8470-e73fa3aa14bc)  instructor dashboard

login info to see:
Login: BC2024-25
password: vic2425

please let me know when this has been corrected. 

thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 ,

We fixed it and now it's showing all the valid student under this account. Please let me know if there is any other issue.

![image (14)](https://github.com/user-attachments/assets/ddcad792-27ac-45e9-a6f7-baabd2b9a291)

**Comment by kbt1** [comment]
looks good! thank you!
