### ISSUE TITLE
MMS - conference tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#3]
Under the Callies Regional Conference, attendee, I entered a confirmation letter. Later I edited it.
Now when i print and download it, to see before I actually email these out, there is a blank page at the beginning.

original word doc:
[Callies Regional Attendee Confirmation.docx](https://github.com/stellaballa/AERA/files/1240113/Callies.Regional.Attendee.Confirmation.docx)

Downloaded pdf from MMS:
[Callies Attendee Letter in MMS.pdf](https://github.com/stellaballa/AERA/files/1240110/Callies.Attendee.Letter.in.MMS.pdf)

Also, at the top of the confirmation letter, the system should pull Name and Company Name of who the letter is going to for both Attendee and Exhibitor.

**Comment by kbt1** [comment]
Have you been able to correct this?

**Comment by SagarPC** [comment]
@kbt1 : we are still looking into this issue as it's working fine with our local environment. That's why it's difficult to find cause but we are trying to find cause and will resolved asap.

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue and uploaded on production. Please refer attached pdf for the reference.

[conferenceInvoice_27_3.pdf](https://github.com/stellaballa/AERA/files/1262723/conferenceInvoice_27_3.pdf)

**Comment by kbt1** [comment]
Looks good.
