### ISSUE TITLE
MMS- Conference Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#30]
Under Conferences
Export Data
Instead of drop down box for "Attendee Type" can you make them check mark boxes like under attendee info.  _ Attendee  _Exhibitor _Non Mbr Exhibitor

Under "Attendee Info" can you add "Status" so we know if they are active or expired

**Comment by SagarPC** [comment]
We have done with this change and uploaded on production please check and confirm our change.

![30](https://user-images.githubusercontent.com/31076567/31125705-e25290c4-a866-11e7-82c2-f5d2b29b609b.png)

**Comment by kbt1** [comment]
This is not where i was talking about. You can put this back to the drop down box please.

**This is the change I need:
Under Conferences Tab
EXPORT DATA
Instead of drop down box for "Attendee Type" can you make them check mark boxes like under attendee info. _ Attendee _Exhibitor _Non Mbr Exhibitor

Under "Attendee Info" can you add "Status" so we know if they are active or expired**

**Comment by kbt1** [comment]
The change you made needs to be put back. I edited a record and its not keeping the change and now the record isnt showing attendee or exhibitor??

![image](https://user-images.githubusercontent.com/26387044/31129951-aed9aade-a81b-11e7-961c-74ddc31d8695.png)

this company should be an exhibitor and its not showing anything
![image](https://user-images.githubusercontent.com/26387044/31130021-d060f842-a81b-11e7-86b0-fb38cb66402f.png)

please let me know when fixed.

**Comment by kbt1** [comment]
The change I wanted was under the Conference Tab, Export Data.
Please be sure to revert back the registration page. I changed a registration and with the check mark boxes, it is NOT showing if they are an attendee or exhibitor now.
Please let me know if you have questions.

**Comment by SagarPC** [comment]
We have revert old changes and implemented function on export screen. Sorry for this inconvenience. Please check our change and let me know if any update required.

![image](https://user-images.githubusercontent.com/31076567/31172934-2ec1948e-a923-11e7-9676-80924e78ada5.png)

**Comment by kbt1** [comment]
However, the spreadsheet is wrong.
i pulled this from Conferences Export Tab
![image](https://user-images.githubusercontent.com/26387044/31176851-df364836-a8d9-11e7-8840-8e11d21163ae.png)
and got this
[example - Callies.xlsx](https://github.com/stellaballa/AERA/files/1355844/example.-.Callies.xlsx)
however, there should be this many:
REGISTERED 
Attendees: **63** 
Exhibitors: 24 
Non Member Exhibitor: 6 
Exhibitor Personnel Count: **53**     **totaling 116 people**

something is not being pulled correctly.  It looks like it is leaving out Non Members.

**Comment by SagarPC** [comment]
Sorry for this inconvenience. 
Please check again and let me know if any update required.

**Comment by kbt1** [comment]
looks good!
