### ISSUE TITLE
MMS- Conferences Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#31]
The Callies  conference is in the Past Tab and I didnt realize I cant edit or add people that register at the event.
Can you either add a Register button on this screen or an Edit button and I can edit the date so the conference will be in the current tab so I can add additional registrants.

![image](https://user-images.githubusercontent.com/26387044/31251997-668a00e6-a9e5-11e7-97ac-7cce3b634d88.png)

questions, let me know.

**Comment by stellaballa** [comment]
@kbt1 Questions:
1) Would you like to ability to edit past events? Correct?
2) Or the event is under Past Event even though it should be Upcoming?

**Comment by kbt1** [comment]
Yes, if I can edit the past events and change the date range of the event, then The event that is under Past Event can be changed to Upcoming so I can add additional people.

**Comment by stellaballa** [comment]
@kbt1 
Ok, just curious, if the event is in the past, why do you need to add people? Is it something you have to do after the event to add additional people who registered on site?

**Comment by kbt1** [comment]
Exactly.  For Example, the Callies regional which is today, is now in the Past Tab, however, Steve will bring back people that registered on site and I have to be able to add them next week.

**Comment by stellaballa** [comment]
@kbt1 Got it!
@SagarPC Here are 2 ways we can approach this:
1) Don't move the event to past event based on the date, add a "Close Event" button on the current event, once Karen complete all her update, she can close the event and it will move to past event. 
2) Make Past Event Editable. 

@SagarPC Please let us know which one of this option take more development time. 
@kbt1 Let us know which one you prefer.

**Comment by kbt1** [comment]
Now that I know this is how it works, i will make the end date a week later.
so maybe all that needs to be done right now is to make the Callies Event in the Upcoming Tab.
If you can just change the date and add a week to it, then monday i can go in and add the additional people. This might just be the easiest solution instead of making changes.

**Comment by stellaballa** [comment]
Thanks @kbt1 
@SagarPC please implement Karen's request.

**Comment by SagarPC** [comment]
@kbt1 : We have enabled all options for past conference tab. Please check our update and let me know if any change required in this.

**Comment by kbt1** [comment]
that should work fine. i will test monday.

**Comment by kbt1** [comment]
Everything worked fine BUT the spreadsheet is wrong, looks like it might be missing **non member** registrations. I am not sure.

Under Conference Tab
Export Data
Conference Title: Callies
Click on EXPORT

can you fix this ASAP, we need an accurate spreadsheet because registration fees are reimbursed to the company.
[Attendee History - missing non mbrs.xlsx](https://github.com/stellaballa/AERA/files/1369193/Attendee.History.-.missing.non.mbrs.xlsx)

**Comment by kbt1** [comment]
and if you refund/cancel someone, i am not sure it is updating the totals on the main page of # attending.

**Comment by SagarPC** [comment]
+++++++++++
missing non member registrations.
+++++++++++
Yes correct, there is issue with non member registration and that we resolved now. Please check and confirm.

+++++++++++
and if you refund/cancel someone, i am not sure it is updating the totals on the main page of # attending.
+++++++++++
=> resolved.

**Comment by kbt1** [comment]
looks good
