### ISSUE TITLE
Crankshaft Section - Prosis Pro 

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#34]
In the crankshaft section, we need to change the label on one of our specs to read "Thrust Width" instead of Main Journal Width. I have included a screen shot for reference. 

![thrust width](https://user-images.githubusercontent.com/26387391/31612815-aaca4cfc-b246-11e7-89e8-0096084049a8.jpg)

**Comment by SagarPC** [comment]
@stevefox3781 : We have uploaded this change on stage and production. Please verify and confirm our update.

**Comment by stevefox3781** [comment]
Great thank you!
