### ISSUE TITLE
MMS- Dues Bulk Batch for checks 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#35]
Hi Stella
I created a Bulk Dues Batch for checks, it named it 10-01-17 BulkEntry By KT Check-2 which is wrong, it should be named **10-1-17 BulkEntry By KT Check**. **This is NOT a 2nd batch.**
And, all the dates are being pulled wrong. start date 10/1/17 new date 11/1/17
The actual dates should be: **start date 11/1/17 new date 12/1/17.** 

There is a bulk batch for checks open and this needs to be fixed. Let me know if I need to delete it and redo it. I do not post this batch until the transactions clear the bank which usually takes 10 business days.
![image](https://user-images.githubusercontent.com/26387044/31736970-ca823084-b40b-11e7-969a-153dd172bb00.png)

**Comment by stellaballa** [comment]
@kbt1 Will look into this. Did this happen after we updated the Batch last week? Please let me know if this is a new bug.

**Comment by kbt1** [comment]
This happened after what was fixed with the credit card transactions last week needing 2 batches.
it has worked fine until now.

**Comment by kbt1** [comment]
I wanted to attach the Checking Bulk Transaction spreadsheet.
[Monthly Checking 10-17-17.xlsx](https://github.com/stellaballa/AERA/files/1398355/Monthly.Checking.10-17-17.xlsx)

**Comment by stellaballa** [comment]
@kbt1 ok, we are still looking into this, will send an update later today or tomorrow.

**Comment by kbt1** [comment]
thank you.

**Comment by kbt1** [comment]
Stella
I figured out what I did wrong, I didnt change the date on the spreadsheet so the dates were pulled wrong into the batch.  
I deleted the batch, fixed the spreadsheet and imported the batch back into dues and its fixed.

Sorry for the mistake.
