### ISSUE TITLE
Prosis Pro CMS

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#36]
The make **ARROW** is not showing up in CMS so we can edit any data. It shows up under the user version of the program, but not the CMS version. When we run a report out of CMS, it shows up in the report, just not an option under the Make dropdown.

**Comment by stellaballa** [comment]
@stevefox3781 We will get this fix. Can you tell us what browser you are using, just in case it's a browser issue.

**Comment by stevefox3781** [comment]
Sorry about that - I am using Chrome and Dave is probably using IE. He brought it to my attention. I looked using Chrome and did not see it either.

**Comment by SagarPC** [comment]
@stevefox3781  : Please let us know on which screen we need to look for this issue. It's inside engine specification screen?

http://www.prosispro.com/Admin/EngineSpec.aspx

Please let us know where we need to look for this issue we can fix.

**Comment by stevefox3781** [comment]
I have included two screen shots, one from CMS, top one, and one from the User version of Prosis Pro, bottom one. 

![arrow cms](https://user-images.githubusercontent.com/26387391/32739595-f73d9dc0-c865-11e7-83f9-b93206b743de.png)

![arrow user side](https://user-images.githubusercontent.com/26387391/32739596-f74c39b6-c865-11e7-88e5-8ee6ed2638ae.png)

 Pro. The make ARROW is not showing up on the CMS version, but is on the User version.

**Comment by SagarPC** [comment]
@stevefox3781  : Thanks for the detail information. 

We have taken action and now "Arrow" make on CMS as well. Please check and confirm our update.

**Comment by stevefox3781** [comment]
Good to go. Thanks!
