### ISSUE TITLE
AERA Desktop/Web (Prosis Pro) : Shop Counter Invoice Field Not Cleared

### ISSUE THREAD

**Issue by SagarPC** [stellaballa/AERA#37]
@kbt1, @stevefox3781, & @stellaballa, 

We can reproduce reported the problem by @stevefox3781 which related to "shop counter" invoice copying data from the previously created invoice, We have found same on "Prosis Pro" version as well. 

@kbt1 & @stevefox3781, Let us know if you have anything? I will analysis on this and update you here about how much time I need. 

<img width="868" alt="aeraprosispro" src="https://user-images.githubusercontent.com/31076567/32573989-b31f0258-c484-11e7-80bc-7b405499dd5d.png">
<img width="568" alt="aeradesktop" src="https://user-images.githubusercontent.com/31076567/32573990-b337ec64-c484-11e7-8542-7060c280f3b8.png">

Thanks,
Sagar

**Comment by stellaballa** [comment]
@SagarPC this is a bug, please fix.

**Comment by SagarPC** [comment]
@stevefox3781 : It's resolved with version 6.0 in desktop and also we resolved same on production as well. all Tax should be filled by default as per current logic. It's showing from below screen where user can make setting for the default tax from that screen. Please let us know if any change required in this logic.

![image](https://user-images.githubusercontent.com/31076567/35425966-5734f4f4-0285-11e8-925e-50ffce73cf05.png)

**Comment by stevefox3781** [comment]
That all sounds good.
