### ISSUE TITLE
Create Stage Environment AERA edu And Update Data

### ISSUE THREAD

**Issue by SagarPC** [stellaballa/AERA#39]
Need to create new staging environment for AERA edu, We need to update data based on below email discussion

**Mail SUBJECT:** RE: Prosis Pro & Online Training
Online Training 
Chapter Move – We need to move Chapters 10 & 13 to be moved after the cylinder head exam along with the questions related to those chapters. The questions for Chapter 10 & 13 would also need to be rmoved from the Cylinder Head exam and be placed in the Engine Machinist Final Exam. Those two chapters and questions deal with the cylinder block. We are looking at having a Cylinder Head Exam & Engine Machinist Exam and we need to have some chapters moved in order for this to work.
=> I am ready with the update script for this change, please let me know when I can do that update because when I update all the chapters sequence will be change as requested suddenly.

**Comment by SagarPC** [comment]
@stellaballa : I have done with stage setup, however we need AERA to map below domain with "71.13.159.202" IP to execute stage on browser.

Please do mapping in DNS for 
"stage.aeraedu.com" with IP "71.13.159.202"
"stageapi.aeraedu.com" with "71.13.159.202"

**Comment by stellaballa** [comment]
@SagarPC can you provide the staging site URL in IP address so we can take a look. And I will ask them to point the domain.

**Comment by SagarPC** [comment]
@stellaballa :

Please see my previous comment. I have already provided test domain and IP that need to map. Please let me know if any other information you need.

++++++++++++++++++++++
@stellaballa : I have done with stage setup, however we need AERA to map below domain with "71.13.159.202" IP to execute stage on browser.

Please do mapping in DNS for
"stage.aeraedu.com" with IP "71.13.159.202"
"stageapi.aeraedu.com" with "71.13.159.202"
++++++++++++++++++++++

**Comment by SagarPC** [comment]
@stevefox3781  : stage is now working. Please refer below URL to check our example order related change. Please verify and confirm our change. So we can move same to live.

http://stage.aeraedu.com/
