### ISSUE TITLE
Desktop Issue

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#40]
Member tried to Update Database and received an error message and was instructed to send a copy of the error log file. His program has stopped working cannot search for any specifications there are no engines in data base. He is on Windows 10 and database version 06.04.2016. Below is the log he forwarded to me. If you can, please provide a suggestion on how to fix this problem. 

> The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.

**Comment by SagarPC** [comment]
@stevefox3781 : Please inform that user check "[prosis pro installed path]\temp" folder. There will be few files that we need first as it's backup of that users system. Also inform that user to keep those all file on some where as safe place so whenever we need they can provide us to restore they system. 

*[prosis pro installed path] = C:\Program Files\PROSIS_PRO

We also need to know like which script they used to update database.

Please provide above information to do more investigation.

**Comment by SagarPC** [comment]
@stevefox3781  : I have updated my previous comment for the temp folder path. please consider that.

**Comment by stevefox3781** [comment]
Do we know what files need to be kept? I am calling the member back soon and he will probably ask me.

**Comment by stevefox3781** [comment]
From the desktop is where he updated. 

![update desktop](https://user-images.githubusercontent.com/26387391/32856264-ede12346-ca09-11e7-896c-4b27abed886b.png)

**Comment by SagarPC** [comment]
We need all files under below folder and inform user to keep same.

[Prosis Pro installed path]\temp

*[prosis pro installed path] = C:\Program Files\PROSIS_PRO\temp

**Comment by stevefox3781** [comment]
I have sent the member the new 6.0 file and told him to uninstall the old one and then install the new file and see what happens. Hopefully that will fix the issue he had. I will leave this open till I hear back from them member.

**Comment by stevefox3781** [comment]
Member got the file and installed the program and everything seems to be working just fine.
