### ISSUE TITLE
Membership – Attached PDF showed up on a different ticket

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#41]
I was doing some testing on 915 and attached a file, but I didn’t save it, and now it’s showing up on member 27104?

Chuck was attaching a file to a tech call (member 27104) and when he did, the Lares-Propasl attached to the call as well. The proposal is something for Parts Connect to another possible client. Chuck was planning on leaving it in the call so that you can see it, but when he saved the call, it disappeared.

**Comment by SagarPC** [comment]
@stellaballa  : We found cause and working on this. We will prevent this case and upload asap.

**Comment by SagarPC** [comment]
@stellaballa : We have resolved this issue and upload on stage and production.

**Comment by stevefox3781** [comment]
Thank you
