### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#42]
Stella
After I add a new member and save it. When i click on Add Prosis Pro and select 30 Day Trial and enter the start and end dates and click save, it only saves the end date. I have to click on edit and reselect the Prosis 30 day trial and the start date.   This was working perfectly until this week.

**Comment by SagarPC** [comment]
We found cause and fixing this issue. Once done will upload on stage and production.

**Comment by SagarPC** [comment]
We have resolved this issue on stage and production.

**Comment by kbt1** [comment]
good to go
