### ISSUE TITLE
URGENT!!!! 

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#43]
Have had a couple of calls this morning that when users search for an engine and click on the engine, it takes them back to the dashboard. Have tried it in Chrome & IE, same results. Dave says that it is not working properly in CMS either. Please look into this ASAP.

**Comment by SagarPC** [comment]
@stevefox3781 : I am looking into this. Let me check.

**Comment by SagarPC** [comment]
@stevefox3781  : I have checked and there is issue with server IIS. I have resolved that.

**Comment by stevefox3781** [comment]
Great thank you - I tested and working - appreciate the quick response.
