### ISSUE TITLE
Membership System - Conferences Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#44]
Under the AERA VIP Party, i deleted an additional attendee and the total number did not change.
can you make sure this is being calculated correctly or deducted when someone is deleted.

![image](https://user-images.githubusercontent.com/26387044/33499132-5b38613e-d699-11e7-8378-aefcef2fad40.png)

thank you.

**Comment by stellaballa** [comment]
@kbt1 we will look into this

**Comment by SagarPC** [comment]
We found cause of this issue and working on solution. We will upload this correction on production asap.

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue on stage and production. Please verify and confirm our update.

**Comment by kbt1** [comment]
looks good.
thanks!
