### ISSUE TITLE
Saving PDF Files - Title of File

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#47]
Recently, last day or two, when saving a file to send to someone the file name has changed. It used to give the engine information and now it just gives says **"enginespecification_1544"** as an example. Before it would save as **"ISUZU-C240-1-3-2018".** We like the old format better as we did not have to change the file name.

**Comment by SagarPC** [comment]
We addressed this issue on live. Please check and let us know if any query.

**Comment by stevefox3781** [comment]
Seems to be working fine. 

Thank you!
