### ISSUE TITLE
Nissan Engine Not Showing UP

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#48]
There is an engine that will not come up when searched by make and liter size (3.8). We knew it was in there and had a call from a member late last night, she couldn’t find it either. This AM we looked at the GT-R and low an behold, there it is.

It wouldn’t come up in CMS by Liter either, found it by model and even updated years and republished, still doesn’t come up by liter.

![nissan](https://user-images.githubusercontent.com/26387391/34620055-ccd50d3e-f209-11e7-811a-053f099abbb4.png)

**Comment by SagarPC** [comment]
@stevefox3781  : We are looking into this issue.

**Comment by SagarPC** [comment]
@stevefox3781 : We resolved this issue on live. can you please check and confirm?

![image](https://user-images.githubusercontent.com/31076567/34671222-b1e052ca-f49f-11e7-83fd-0af534b1e4ad.png)

**Comment by stevefox3781** [comment]
Working great!

Thank you.
