### ISSUE TITLE
PROSIS PRO - Uploading PDF Files

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#5]
Getting the following error when uploading a PDF file in CMS under the Notes/Process tabs.

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by SagarPC** [comment]
@stevefox3781  : I have tried with 5 mb file and it's uploaded successfully. Please let me know which file you want to upload and under which engine so I can try that file from my end.

**Comment by stevefox3781** [comment]
This is the engine: 

Make FORD     Model EXPLORER      Year 2002-2005     VIN W      Liter 4.6      CID 281     Engine Code MOD-SOHC     Cyl V 8     VLV/CYL

Here is the file. 
[Main Bearing Cap Installation Procedure.pdf](https://github.com/stellaballa/AERA/files/1251881/Main.Bearing.Cap.Installation.Procedure.pdf)

I had another person try it here and they were having the same issue yesterday. 

I must admit I may not have explained it all that good. I can upload the file no problem, but when I click on it to open, that is when I am getting the error. Sorry for the confusion.

**Comment by SagarPC** [comment]
Please refer below URL. I have uploaded pdf file without taking any special action. Just goes to Notes/Process tab and upload PDF file with name.

http://www.prosispro.com/Admin/EngineSpecificationDetails.aspx?mode=edit&id=4831

**Comment by stevefox3781** [comment]
Thank you! I am not sure what was going on, but we will try another file for another engine and see if that works. I will leave this open until we try it and respond here either way.

**Comment by stellaballa** [comment]
@stevefox3781 Can you let us know what browser you are using? That might be the cause of the problem.

**Comment by stevefox3781** [comment]
I am using Chrome

**Comment by SagarPC** [comment]
@stevefox3781 : We have uploaded that file using Chrome and we not faced any issue. Please try from your end and let us know if still there is any issue.

**Comment by stellaballa** [comment]
@stevefox3781 Let me know if you are still having any problem, maybe it's the engine, if you give us more details, we can look into it.
