### ISSUE TITLE
See TB 705 Link to wrong TB

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#50]
Under Cummins 14.0L 855 CID NT Series (Engine Model) in the block section, when you click the SEE TB 705 link, it goes to TB 2705 instead. I removed the wording from the engine in CMS, saved it and added back in - same problem. Can you take a look at htis for us? This TB link may be in other 855 Cummins engines - I did not check them all. 

![image](https://user-images.githubusercontent.com/26387391/34996268-b5e35a70-fa9e-11e7-85f3-410d07ce2a89.png)

![image](https://user-images.githubusercontent.com/26387391/34996226-8de98184-fa9e-11e7-829d-1b8069d89c82.png)

**Comment by stellaballa** [comment]
@stevefox3781  we will look into this and give you and update asap

**Comment by SagarPC** [comment]
We resolved this issue on live. Please check and confirm our update.

**Comment by stevefox3781** [comment]
Looks good!

Thank you
