### ISSUE TITLE
Membership# Search inside Tech Que

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#51]
@stevefox3781 would like to add a search function under Tech Que incase the member doesn't know his member ID.

1) Add Search box on the pop-up window. 
2) Add a Search Result page, AERA click on the member to start a Tech Que ticket. 

@stevefox3781 can you take a look at the screen to make sure this is correct. 
@SagarPC we will add this function with the maintenance hours. 

![tq-member-result0118](https://user-images.githubusercontent.com/30122790/35010595-38464d88-fab8-11e7-8a47-8c39565307a0.jpg)
![tq-memeber-search0118](https://user-images.githubusercontent.com/30122790/35010596-385acb3c-fab8-11e7-954a-4128b39e0499.jpg)

**Comment by stevefox3781** [comment]
Stella/Sagar - the second option (screen shot) is what we are looking for. When you click on create tech call, the box will open and you have the ability to search by Member Number or Company Name, Phone, Email. If multiple company names appear, for instance Arnold Motor Supply, I would assume we would get the option to choose which one and create a tech call?

Any questions, let me know.

**Comment by stellaballa** [comment]
@stevefox3781 You are correct, the 2nd screen is to show the search results. The search result page will be the 2nd step whether there are multiple results or just 1, it would be very difficult to implement the system to by pass this page if there's only 1 result.

**Comment by SagarPC** [comment]
@stevefox3781 : We have uploaded this change in stage. Please confirm update so we can move same on live.

http://71.13.159.202/aeramms_stage/techcallqueuelist.aspx

**Comment by stevefox3781** [comment]
Looks and works great! I give it the OK to publish live. 

Thank you,

**Comment by SagarPC** [comment]
@stevefox3781 : We have uploaded same on live. Please confirm our update.

http://71.13.159.202/aeramms/techcallqueuelist.aspx

**Comment by stevefox3781** [comment]
Great - thank you. Looks good.
