### ISSUE TITLE
MMS-emailing invoice

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#52]
i am getting this message when i select a member to email an invoice to. they expired 1/1/17 but i am not sure why this happens.
![image](https://user-images.githubusercontent.com/26387044/35050826-533d5daa-fb69-11e7-9c73-5eaa6dbf516f.png)

let me know.

Thanks

**Comment by SagarPC** [comment]
Please see below there where we stop exporting invoice for those member who having expiry older than 6 month. You just need to edit and update expiry for that member 6 or less month older and then you can able to send email to that member.
 
https://github.com/stellaballa/AERA/issues/32#issuecomment-335151650

Please let me know if any change required in this logic.

**Comment by kbt1** [comment]
ok. thank you.
