### ISSUE TITLE
Specification Request

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#53]
This week we have had a couple of members send in a "Specification Request" and we get it 4-5 times. This morning we had one that came in 5 times. When the first one came through I did not think much of it, but when the one this morning came through 5 times, I better check to see if it is something on our end. Chuck called the member back from this morning and the member stated the following: "it keeps popping back up after he hits send, that he must enter a valid email address. He said he gave up after the 5th time." Chuck told him we did get all 5.

![image](https://user-images.githubusercontent.com/26387391/35099972-a3bb727e-fc1f-11e7-809c-fccfaaf0ba29.png)

**Comment by stellaballa** [comment]
Thanks @stevefox3781 
@SagarPC please take a look and fix asap.

**Comment by SagarPC** [comment]
@stellaballa  : I tried same thing from my end and it's working fine for me. I am getting only one notification email and one as admin email. I checked code as well to be sure and it's properly executed.

http://www.prosispro.com/SpecificationRequest.aspx

can you please try once from your end to be sure?

**Comment by stevefox3781** [comment]
It worked fine on my end as well. I will keep this open for a week and see if we get anymore instances and if not will close the ticket.

**Comment by stevefox3781** [comment]
I think the majority of the issues are from the users hitting send multiple times. If this issue comes up again, will create another ticket to look into further. At this time, the request is working correctly.
