### ISSUE TITLE
Engine Search

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#54]
Since the udpate, when you click on the RED box "NEW ENGINE SEARCH" it reverts back to the old search options with the vehicle type. Can we get that removed so it is consistent with the Dashboard? The first screen shot is the Dashboard and the second is the New Engine Search

![dashboard](https://user-images.githubusercontent.com/26387391/35106451-dc811776-fc33-11e7-8b00-344abb81c9ac.png)

![new engine search](https://user-images.githubusercontent.com/26387391/35106452-dc96b914-fc33-11e7-9567-3f1ece6aa03d.png)

**Comment by stellaballa** [comment]
@SagarPC can you please update this.

**Comment by SagarPC** [comment]
@stevefox3781 : We done with this update and uploaded on production. Please confirm our update.

**Comment by stevefox3781** [comment]
Good to go. 

Thank you!
