### ISSUE TITLE
Spec Request Email Response - ASAP

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#55]
When users get the email response, it says Alldata instead of AERA. Please change ASAP to AERA on the locations that say Alldata. On the second image, remove the part in BLUE and the last bullet point should say "Call AERA Technical Services at 888-326-2372 or 815-526-7600."

![image](https://user-images.githubusercontent.com/26387391/35157457-a25b0be4-fcf9-11e7-8f47-9934de5afb07.png)

![image](https://user-images.githubusercontent.com/26387391/35157526-dcf93d2a-fcf9-11e7-9ec7-eaa789303037.png)

**Comment by stellaballa** [comment]
@SagarPC please update this ASAP.
Can you do a search on the site to see where else does it mention ALLDATA, and share with me. 
Thanks, Stella

**Comment by SagarPC** [comment]
@stevefox3781 : We have updated text as suggested. Please confirm our update.

**Comment by stevefox3781** [comment]
Good to go. 

Thank you
