### ISSUE TITLE
Spanish Translation - Make

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#56]
One of our former directors is getting some calls from the Spanish speaking members using Prosis Pro that the word tranlsation make in SPanish is wrong. The word “make” in Spanish as in vehicle make is “**fabricante**” we have it right now as “hacer” which is like I want to “make” pancakes. Can this be updated to the correct translation? We think it was correct at one time; not sure if Google updated something and it changed or what.

Thank you, 
Steve

**Comment by stellaballa** [comment]
@stevefox3781 Is this on Prosis Pro Online or the Software?

**Comment by stevefox3781** [comment]
Online

**Comment by stellaballa** [comment]
@SagarPC Please make this correction.

**Comment by SagarPC** [comment]
@stevefox3781 : We have taken action on production and updated with "fabricante". Please confirm our update.

**Comment by stevefox3781** [comment]
Looks good. 

Thank you!
