### ISSUE TITLE
Print Screen Mercedes Benz OM642 - Block & Crank Section

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#57]
When we look up the (Make) Mercedes Benz  (VIN ) D (Engine Model) OM642, when we look at the crankshaft and block specs, they look normal on the screen, but when we go to print them, the print screen shows additional information that seems to have been added by a member as it is in blue. I have included a couple of screen shots for review. First one is crankshaft section adn the second one is the block section. Here is the link to the engine - http://prosispro.com/EngineSpecificationDetails.aspx?eid=10244

![image](https://user-images.githubusercontent.com/26387391/35284480-8db81ffe-0020-11e8-9afe-bbd6570e7f22.png)

![image](https://user-images.githubusercontent.com/26387391/35284503-9aabce36-0020-11e8-9213-a93df19e7f9e.png)

**Comment by stellaballa** [comment]
@SagarPC  please look into it

**Comment by SagarPC** [comment]
@stellaballa : We looked into this issue and found cause. We will upload this fixes on production by tomorrow after testing.

**Comment by stevefox3781** [comment]
We have also found it in a LandRover 2010-13 5.0L engine so it may be throughout the program. Just an FYI.

**Comment by SagarPC** [comment]
@stevefox3781 : We have resolved this issue on production. Please confirm our update.

**Comment by stevefox3781** [comment]
Seems to be working fine and looks correct. 

Thank you
