### ISSUE TITLE
Prosis Pro Desktop -  school installation

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#58]
Hi Stella
I am trying to help a school get Prosis Pro Desktop installed on 25 machines. The web version is not an option, the school locks the internet.  Is there anything that can be done to issue a school 1 license for multiple machines? 1 license would make it easier for schools.    this is the email i got from the school member and maybe there are some options? Let me know. 
Thank you!

Karen, 

It sounds like your flash drive will generate a unique software ID for each computer. Correct? 
It is a major undertaking for our IT people to come and update our machines. The College installs a “Centurion” software on our student use computers that prevents anyone from installing or changing the software on each machine. This also protects our computers from all viruses and infections.
Every time one of our computers is powered down, the software reverts to the configuration it used on startup. To permanently install any new software, the IT people have to unlock the Centurion software, then install the new application, then email you and wait for a key for each machine before they can lock the computer back down. We have 25 or so machines that will each need the new software version. 

I won’t say it can’t be done, but my IT people won’t like me much either.  
I wonder if there might be a better solution that fits our situation.

**Comment by stellaballa** [comment]
@kbt1 Let me review with @SagarPC and get back to you.

**Comment by kbt1** [comment]
Any update on this?

**Comment by stellaballa** [comment]
@kbt1  Let me check.

**Comment by SagarPC** [comment]
@stellaballa : I have checked with the system and currently there is no way like 1 license work for more number of software.

Please let me know if there is requirement to implement such new function in windows app. We can provide such function to generate master license, that license bypass software ID check.

**Comment by stevefox3781** [comment]
Hi Stella, 

Would you be able to tell me the time and cost to do something like this. Also, would there then be two types of USB's that we would need to mail out; one for regular users and one for the schools? Once you have done some research, maybe we set up a conference call to discuss. 

Thanks, 
Steve

**Comment by stellaballa** [comment]
Steve, yes let me discuss this with the team and figure out the cost and effort to create this type of system for Prosis pro desktop
