### ISSUE TITLE
MMS 

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#6]
I emailed Dues and Prosis invoices in a batch today and a reply i got had the wrong Total Amount Due

ID#11322 paid membership already and Prosis is due 9/1/17
If you select their record to Print or Email the invoice, it is correct. But when selected in a Batch of multiple emails, it prints out wrong in the email text. (See Below)

![image](https://user-images.githubusercontent.com/26387044/29729893-a73314c8-89a3-11e7-9536-ac229d525877.png)

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue and uploaded on production. Please verify and confirm.

**Comment by kbt1** [comment]
looks corrected.
