### ISSUE TITLE
Prosis Pro & CMS Resetting

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#60]
It seems that CMS & Prosis Pro are what I will call resetting after a period of time. Mary who does some data input for us sent over the following information - "I seem to have to log back in to CMS about every 5-10 minutes.  I’ll be typing along just fine, and then it kicks me out and I lose all that I haven’t saved. " In Prosis Pro, it seems to reset if you have not used it for a little bit where if you hit a drop down and click Acura for instance, it looks like it is searching and you have to search for the make Acura again. 

Hope this makes sense if not, let me know.

**Comment by stevefox3781** [comment]
Was told the problem started happening today.

**Comment by SagarPC** [comment]
@stevefox3781 : I just updated server setting for Prosis Pro. Please keep me update on your experience. You need to reload page once. Actually it issue something related to setting or Server update I am trying to identify. 

Please reload page once before saving anything as I update server setting just now.

**Comment by stevefox3781** [comment]
Mary, who enters specs into prosis pro for us, sent me this email this morning - I’ve been working since 8:15am in CMS and have had to log in 3 times.  This is not fun.

**Comment by SagarPC** [comment]
@stevefox3781: I am login into system since from last 10 hours and it's continues working for me. actually I keep watch in this since from last night to be sure about issue. 

Please let me know if Mary got any error on screen and because of that they need to do login again. I don't think system automatically ask for login until there is error or invalid inputs.

I am looking into this.

**Comment by stevefox3781** [comment]
No error messages, just brings you to log-in screen and whatever you were adding is gone, unless you save every entry, and then edit again.

**Comment by stellaballa** [comment]
@stevefox3781 Can Mary provide more information? Does any of the tech have the same problem. If nobody has the same issue, it might have to do with her browser setting or internet connection, but I am not sure. @SagarPC can you check Mary's account log? I believe her email is mary@aera.org.

**Comment by stevefox3781** [comment]
Dave told me he was having that issue yesterday, but has not tried today. He is using Chrome and Mary is using Explorer.

**Comment by stellaballa** [comment]
@stevefox3781 Does this issue only happen on the CMS? Did any member call about this problem? 
@SagarPC there might be a time out on the CMS login, maybe when AERA is typing in the content, the site automatically logout because it is not having any activities.

**Comment by stevefox3781** [comment]
I have not heard of any member having this issue. I am in Prosis Pro all day and never get logged out. I just opened the CMS so let me see what happens.
