### ISSUE TITLE
Prosis Pro Uploading PDF Files

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#61]
I tried to upload a PDF file to the Notes/Process this morning and when I do, I am getting error "**404 - File or directory not found. The resource you are looking for might have been removed, had its name changed or is temporarily unavailable.**" We are printing a PDF file from another program, going in and making changes (deleting information not needed), saving as a PDF file in a folder on my desktop and then trying to upload to Prosis Pro. 

I emailed the PDF file to another tech person and had them try to upload the file as well with the same result. I am using Chrome as my browser as was the other tech and I also tried it in Microsoft Edge with the same results. 

I have attached the file as well as picture of the engine we are trying to upload the file in. I had this issue before and looked back at what the problem was, but it looked like Sager was able to upload with no problem (issue #5). If you can look into this and let us know what we are doing wrong, we would appreciate it. 

[Balance Shaft Drive Chain, Removing and Installing.pdf](https://github.com/stellaballa/AERA/files/1871979/Balance.Shaft.Drive.Chain.Removing.and.Installing.pdf)

![image](https://user-images.githubusercontent.com/26387391/38256164-435c79ac-3723-11e8-8fb2-a1da870f5c2e.png)

**Comment by stellaballa** [comment]
@stevefox3781  we will look into this

**Comment by SagarPC** [comment]
@stevefox3781: we found cause of this issue and it's because of too long file name. We now allowed 500 character in file name so it's working.

We upload this fix on live so you can upload file and verify.

**Comment by stevefox3781** [comment]
Seems to be working. I had to rename the PDF file, but after that worked fine. 

Thank you!
