### ISSUE TITLE
Advanced Search - Bore Size & Rod

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#62]
It looks like PROSIS is having an issue in the search fields for both block and connecting rod.

If you try and do an 4.00 “inch” search in either block or a 2.225 “inch” search rod big end nothing happens. If you do the “MM” look up it works fine.

Casting number seems to work fine as well.

I have tried it on 2 different browsers and two different computers as well as Dave tried it with the same result.

**Comment by stellaballa** [comment]
@stevefox3781  will look into this.

**Comment by SagarPC** [comment]
We checked with the admin + user login and it's working for us. Please see below image for reference.

We need more information like below.

1) user login detail where you are facing this issue.
2) field name with search value
3) which engine expecting in result based on value searched in step 2.

http://www.prosispro.com/Admin/EngineSpec.aspx

<img width="759" alt="bore center to center" src="https://user-images.githubusercontent.com/31076567/38858795-3c971bc2-424a-11e8-960e-67d0ae920e30.png">
<img width="764" alt="rod_big end dia" src="https://user-images.githubusercontent.com/31076567/38858796-3cd6ebf8-424a-11e8-9fc0-0a601df8038f.png">
<img width="758" alt="rod_small end dia" src="https://user-images.githubusercontent.com/31076567/38858798-3d16554a-424a-11e8-91a9-6134ac5c130a.png">

**Comment by SagarPC** [comment]
@stevefox3781 : Please let me know if any feedback on my last comment.

**Comment by stevefox3781** [comment]
Seems to be working fine from what I am finding.
