### ISSUE TITLE
Custom Training - Export Data

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#63]
In the Export Data tab in the Tech Queue, when we select Custom Training, we get no results. The screen seems to flash the results, but then comes back with "no records found to export". Selected other options and get the same results. 

Please look into this and if you have any questions, please let me know.

**Comment by SagarPC** [comment]
@stevefox3781 : We are looking into this.

**Comment by SagarPC** [comment]
@stevefox3781 : We looked into this and it's working fine now. Please verify update.

**Comment by stevefox3781** [comment]
Seems to be working fine.
