### ISSUE TITLE
Online Certification - Final Exam Passed Notifications

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#65]
Stella and Sagar

I occasionally go through my spreadsheet of Online Certification Registrants to see their progress. (Not SamTech)
I just found 2 people that passed 5/4 and 5/5 and I DID NOT get notification. (Leo W Jensen and Skylar B Albright-Matson, both from Lake Area Tech.
Can this be linked to the MMS that I am not getting emails either?
Please look into. Is there a way for you to check and tell me who passed Final Exams on 5-4 to now?

**Comment by stellaballa** [comment]
@kbt1 @SagarPC Let's do a full test on all email notification to make sure they are all working properly.

**Comment by kbt1** [comment]
please let me know when you test so i know to let you know if I recvd it or not.

**Comment by SagarPC** [comment]
@kbt1 & @stellaballa : all notification system working properly, here issue with "___@aera.org", which not accepting email from "noreply@aera.org". I don't know why but there is some security setting change done for that email domain or else.

see below image I send below email for testing please see I received email but I think Karen should not received that one. If this is the case then there is some security policy change done under "___@aera.org" domain. There is no issue with the code.

![image](https://user-images.githubusercontent.com/31076567/39739583-4a8f533c-52af-11e8-952a-f8d35b00045d.png)

I checked with the database and found only those 2 student passed exam on 5/4 and 5/5.

2018-05-04	Leo W	Jensen
2018-05-05	Skylar B.	Albright-Matson


Regards,

**Comment by kbt1** [comment]
I will have VCS look into the email issue.

**Comment by kbt1** [comment]
I did not receive notification on that. I am going to have VCS look into this.
Is this why I am not getting Product Order Forms emailed from MMS also?

**Comment by SagarPC** [comment]
@kbt1 : both having same issue.

Please see below sample page we created for you to test, you can send one email on your "karen@aera.org" account and another on gmail or any other account. I am sure gmail or other account will received that email but "karen@aera.org" will not. It's using same function and code to send email. So the system working fine but "___@aera.org" account not accepting email.

Please do one test from your end and let me know your feedback

http://71.13.159.202/aeramms/sendemail.aspx

**Comment by SagarPC** [comment]
http://71.13.159.202/aeramms/sendemail.aspx

![image](https://user-images.githubusercontent.com/31076567/39758553-ce69d306-52ed-11e8-90ce-4d32505553f5.png)

**Comment by kbt1** [comment]
I did NOT get the aera.org email test
I DID get the gmail.com email test
Our computer company must have changed security settings, we will have them look into this.

**Comment by kbt1** [comment]
Sagar
Can you set email for Certification to go to 2 emails?
ktendering@gmail.com and karen@aera.org???
i found another person that passed the final exam and i didnt get notification.
Until this is fixed, having it go to 2 emails would help.  Let me know as soon as you can.

**Comment by SagarPC** [comment]
@kbt1 : I have updated email from "karen@aera.org" to "ktendering@gmail.com" for now. I will revert this to "karen@aera.org", once it's start working.

**Comment by kbt1** [comment]
thank you!

**Comment by kbt1** [comment]
i tried a product order form in MMS and I also tried to get notification from Online Certification.
Doesnt seem to be working. 
The product order form still has karen@aera.org.
it needs to be ktendering@gmail.com

![image](https://user-images.githubusercontent.com/26387044/39780091-d7a7a3ac-52d0-11e8-8d65-4afce6a22346.png)

**Comment by kbt1** [comment]
when i change both to and reply to boxes with my ktendering@gmail.com, i get the email
![image](https://user-images.githubusercontent.com/26387044/39780254-542ae4de-52d1-11e8-8f43-d37c20b35cbd.png)

**Comment by SagarPC** [comment]
@kbt1 : Yes here is same issue like "___@aera.org" email address not accepting email from the system might be there some update for security/policy to receive email.

**Comment by kbt1** [comment]
I am getting notification from Online Certification on students completing the course.
Once we get my email issue settled, we will let you know.

**Comment by kbt1** [comment]
All seems to be working well. I am getting Product Order Forms to Karen@aera.org and Certification Completion emails to my gmail.
