### ISSUE TITLE
Phone & Fax Numbers

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#66]
In the Management system, can we color code the phone and fax numbers for ease of recognition. We have had an issue where we were faxing to the phone number and the member was not real happy with us. I suggest making the phone number GREEN and the fax number RED. Also if you can bold the box name in those colors as well. 

![image](https://user-images.githubusercontent.com/26387391/39782051-a5fbbe5a-52d6-11e8-82b3-146e44b2e20f.png)

Any questions, let me know.

**Comment by SagarPC** [comment]
We done with this change and uploaded on production. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/39807174-3ee60874-5399-11e8-98f6-e62c69d319fc.png)

**Comment by stevefox3781** [comment]
Looks great - Thank you!!!!!
