### ISSUE TITLE
MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#67]
Stella
Is there a way that the MMS WOULD NOT print or email any invoices with records that have something selected in the "Mail Code" box. I have taken a couple calls from members getting invoices for their deceased spouse and it would make it easier if nothing was pulled from these records.

Let me know.

**Comment by anthonypartsconnect** [comment]
@kbt1 
We need a little more background.  Can you please provide an example of this? 
Initial thinking is that for these accounts, it appears the contact person on the account is the issue. 
Maybe there's a different workaround that we can discuss if we understand the invoice trigger/mechanism in more detail. 

Thank you - anthony

**Comment by kbt1** [comment]
Any record with something in the "Mail Code" box should not have any invoices pulled whether the account is marked deceased or out of business.
example:
![image](https://user-images.githubusercontent.com/26387044/40178323-c553846e-59a6-11e8-8517-c061c409009b.png)
![image](https://user-images.githubusercontent.com/26387044/40178351-dee790dc-59a6-11e8-8097-773bf8d4d314.png)
if this is possible to fix, if not, i will do a work around.

**Comment by anthonypartsconnect** [comment]
Hello Karen,

Understanding the situation better, the way we can avoid these emails is to
look at Mail Code, and make sure we are not sending notifications/invoices
to accounts with "Mail Code" equaling "out of business" or "deceased."

Does that seem like the correct fix?  If so, we can have our tech guy
switch the notification for those groups and the problem should be
resolved.

Last, besides the two groups mentioned above, any other "mail code" groups
we should not be sending notifications to?


Thanks.



*Anthony Soto*, Project Manager
Parts Connect, Inc.
5792 W Jefferson Blvd,
<https://maps.google.com/?q=5792+W+Jefferson+Blvd,%C2%A0+Los+Angeles,+CA+90016&entry=gmail&source=g>Los
Angeles, CA 90016
<https://maps.google.com/?q=5792+W+Jefferson+Blvd,%C2%A0+Los+Angeles,+CA+90016&entry=gmail&source=g>
T. 310.686.7769  |  anthony@partsconnect.us <stella@partsconnect.us>  |
www.partsconnect.us

**Comment by kbt1** [comment]
Can you do something like "If "mail code" is null, print or email.
Really, any selection in the mail code box should not be emailed or printed an invoice.

**Comment by anthonypartsconnect** [comment]
Yes, I think we can accomplish this. Can we jump on a quick phone call so I
can better understand your thoughts.

Thanks!  Anthony

**Comment by kbt1** [comment]
just taking lunch, can you call at 1pm?

**Comment by anthonypartsconnect** [comment]
I have a call at that time lasting only a half hour, but can reach out at
1:30 your time if that works? I'll call on this number. *Ph. 888-326-2372*
Thanks! - Anthony

**Comment by kbt1** [comment]
that is perfect

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Hello Sagar, after a brief conversation with Karen, can we update the following. 

If there is any input for "mail code", these accounts should not be receiving any notices (email or print).  Understanding the current situation, these accounts which have an input for "mail code" are currently experiencing:  

1)receiving automatic email updates
2)AERA system is triggered to print an invoice

So, is it in our control to turn of these mechanisms within their system?

Thanks!  - Anthony

**Comment by anthonypartsconnect** [comment]
@kbt1 
We are confirmed to change the email/invoices for those accounts with "mail code" input. 
Nothing will change for those accounts that do not have a "mail code" input. 
The team is correcting this and it will be completed by 5/23.  
Thanks - Anthony

**Comment by kbt1** [comment]
perfect, thank you!

**Comment by anthonypartsconnect** [comment]
Of course. I will touch bases with you the day of.

**Comment by anthonypartsconnect** [comment]
Hello Karen, 
The update is completed on our end.  Please let us know if you have any questions.  Email notifications and Invoice printing will no longer be performed for accounts that have a "mail code" input. 
Thanks.  - Anthony

**Comment by kbt1** [comment]
I just checked and Printing and Emailing is still working.
Mbr #44246 is marked "Out of Business"
![image](https://user-images.githubusercontent.com/26387044/40377599-e0495596-5db6-11e8-965f-bc60353844f9.png)

![image](https://user-images.githubusercontent.com/26387044/40377475-a178dd28-5db6-11e8-8b12-4d30b1e1c303.png)

I select their record and click print and it prints
![image](https://user-images.githubusercontent.com/26387044/40377498-ab254866-5db6-11e8-9ed3-ffdc334da5fb.png)

i select email and it emails.
![image](https://user-images.githubusercontent.com/26387044/40377523-b5aefb60-5db6-11e8-8ce9-64074153f256.png)

**Comment by anthonypartsconnect** [comment]
Hello Karen, 

Apologies on my end.  I miscommunicated.  The update is on the stage site, not the live site just yet.  

Log in to check with the following credentials:
http://71.13.159.202/aeramms_stage/login.aspx
UserName: sagar@partsconnect.us
Password: sA@12345678

I tested again with MBR #44246 and when you click "print invoice" or "mail invoice" then error messages will appear. 

If this looks good to you please let us know and and we can update to live.

**Comment by kbt1** [comment]
No problem!

Karen Tendering
AERA Membership/Contract Services

Ph. 888-326-2372
Fax 888-329-2372

**Comment by anthonypartsconnect** [comment]
Hi Karen, 
So please let me know when everything looks good on staging site so we can then update on live site. 
Thanks! - Anthony

**Comment by kbt1** [comment]
Works good, you can update to live site.

Karen

**Comment by anthonypartsconnect** [comment]
Thank you Karen. I will let Sagar know to update live and will give you confirmation (probably tomorrow morning) that it is all set. 
Anthony

**Comment by anthonypartsconnect** [comment]
Hello Karen, 
The update went live. Please let us know if you have any questions. 
Thank you!
Anthony

**Comment by kbt1** [comment]
i checked this morning and it works good.

thank you

**Comment by anthonypartsconnect** [comment]
Great! Thank you for your patience.
