### ISSUE TITLE
MMS - Prosis Pro User

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#68]
Stella
In the list of expired June 1st Prosis Users I pulled, there is 1 company I cannot pull up because they have a prospect code. They are a Prosis User without Membership. I cant find them anywhere and I need their user name and password so I can add them back in unless you can go in and change the PF code to AC.
Let me know. I have attached the list and the yellow highlighted company is the one I cant find, Regal Automotive.

[Prosis Monthly Call Report-June.xlsx](https://github.com/stellaballa/AERA/files/2080665/Prosis.Monthly.Call.Report-June.xlsx)

thank you
Karen

**Comment by anthonypartsconnect** [comment]
Hi Sagar, can you have a look at Karen's issue. 

Karen we are looking into it. Thanks -- Anthony

**Comment by SagarPC** [comment]
@kbt1 : We updated class type of this user and now it's shown under Expired tab of Membership. Please refer below screen.

![image](https://user-images.githubusercontent.com/31076567/41160461-71da9350-6b4d-11e8-961a-88327e7cab46.png)

**Comment by kbt1** [comment]
That is perfect!  Thank you so much!!!!

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.
