### ISSUE TITLE
Prosis Pro Desktop User

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#69]
@SagarPC 
AERA has a prosis pro desktop user that cannot install latest version due to .netframeworks V4.5.  It is asking him to go to web to install but he does not have internet access to install.  Can we download it for him and send him a flash drive?  First, we should understand better how .netframeworks V4.5 works.

**Comment by SagarPC** [comment]
@anthonypartsconnect : Please ask client to collect below information from the customer.

1) OS (Window 7/ Windows 8/ Windows 10)
2) Which Prosis Pro version they installed previously?
3) Which Prosis Pro version they try to install now?

**Comment by anthonypartsconnect** [comment]
Thank you Sagar, sent this in an email to Steve.

**Comment by anthonypartsconnect** [comment]
@Sagar, Steve provided the feedback to your questions. 
1.Windows 7
2. Version 5
3. Version 6

**Comment by SagarPC** [comment]
@anthonypartsconnect : We are looking into this by installing Windows 7 on our one of the machine and trying to reproduce this issue.

**Comment by anthonypartsconnect** [comment]
Great, thank you @SagarPC

**Comment by SagarPC** [comment]
@anthonypartsconnect : We looked into this issue and notice there is some conflicted between our setup and client installed software. I suggest to remove 1 of the conflicted software from client and re-run "Version 6" of Prosis Pro Desktop.

1) Please download instruction document from below link and ask client to follow this step to uninstall that conflicted software from they machine first.
[desktop_user_issue.docx](https://github.com/stellaballa/AERA/files/2154483/desktop_user_issue.docx)

2) Once uninstall process done, ask them to re-run "ProsisPRO_6.0.0.exe".

above 2 action will resolve client issue.

Regards,

**Comment by anthonypartsconnect** [comment]
Thank you Sagar, I am sharing with client now.
