### ISSUE TITLE
MMS - Invoicing

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#7]
We have approved a few 6 month renewals for Membership and Prosis. I tried to print an invoice and it wont allow it.
here is the record:
![image](https://user-images.githubusercontent.com/26387044/29782558-a96d1cb6-8be2-11e7-94a5-84dbd37444a5.png)
When i click on print invoice, this is the message i get
![image](https://user-images.githubusercontent.com/26387044/29782579-c02fbf58-8be2-11e7-9448-e72cc53b67c3.png)
if I select email invoice, this is the message i get
![image](https://user-images.githubusercontent.com/26387044/29782597-d012a002-8be2-11e7-8913-4466ac6f3371.png)

We do not invoice monthly payment plans but I do need to be able to set an account at 6 month payment plan and be able to print or email the invoice.

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue and uploaded on production. Please verify and confirm.

**Comment by kbt1** [comment]
works good.
