### ISSUE TITLE
HIGH PRIORITY: Authy Needs to be disabled for AERA Prosis Pro

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#70]
Hello Sagar,

Stella shared email with you, but to recap:

We need to disable Authy for Prosis Pro. These members below have it enabled. One member in particular cannot access his account. Chad, Washington Auto Parts (19512). Email @ carquestnewark@gmail.com.

1887 – Northeast Automotive Parts Inc
6792 – Automotive Machine Inc
**19512 – Washington Auto Parts**
17375 – Hypercision Automotive Inc
33107 – Jobbers Warehouse Supply Inc
42701 – K & W Truck Repair

Once you have disabled authy and this user (Chad - 19512 Washington Auto Parts) can get in, can you send an email to Chad.  I have provided the email address above. 

Thanks.

Anthony

**Comment by SagarPC** [comment]
@anthonypartsconnect : I disabled Authy for Prosis Pro.

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.

*Anthony Soto*, Project Manager
Parts Connect, Inc.
5792 W Jefferson Blvd,
<https://maps.google.com/?q=5792+W+Jefferson+Blvd,%C2%A0+Los+Angeles,+CA+90016&entry=gmail&source=g>Los
Angeles, CA 90016
<https://maps.google.com/?q=5792+W+Jefferson+Blvd,%C2%A0+Los+Angeles,+CA+90016&entry=gmail&source=g>
T. 310.686.7769  |  anthony@partsconnect.us <stella@partsconnect.us>  |
www.partsconnect.us
