### ISSUE TITLE
MMS System Updates: MMS Dues Batch 8/24/18SF

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#71]
@SagarPC  

For the batch provided, in the backend can you change the member id # 3795 to 2795.  It was labeled wrong on their end but they don't want to restart the whole batch of information, and currently editing could erase the records tied to each transaction. 
![aera member id correction needed](https://user-images.githubusercontent.com/39140696/44693596-025a1900-aa1e-11e8-9aeb-ae20dd863960.png)

**Comment by SagarPC** [comment]
It's updated. Please send an update to the client.

![image](https://user-images.githubusercontent.com/31076567/44702344-9e346500-aab0-11e8-8eee-90fdc9d346b2.png)

**Comment by anthonypartsconnect** [comment]
Thanks Sagar.

**Comment by anthonypartsconnect** [comment]
Client said it looks good.  Thanks Sagar.
