### ISSUE TITLE
Membership Management System -Tech Queue Caller 

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#72]
@ Sagar

Following the email thread between you, Stella and Steve at AERA, Stella asked to make the following change in the system. 

"Instead of showing Tech 1 and Tech 2, can we put the name in there? Sorry, I know I told you to put in Tech 1 & 2 but it turns out the name is more important. "

Thank you Sagar.

**Comment by SagarPC** [comment]
We are now showing name instead of Tech 1 and Tech 2. Please let us know if any other change required.

**Comment by stellaballa** [comment]
<img width="768" alt="screen shot 2018-09-09 at 9 49 23 pm" src="https://user-images.githubusercontent.com/30122790/45276998-487d9680-b47a-11e8-92e0-9074b7dbe3f9.png">
Why is Steve name at the bottom? Shouldn't "Other" be the last option?

**Comment by SagarPC** [comment]
We changed the order sequence. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/45297882-5e479600-b524-11e8-9c30-a8a2d921ef83.png)

**Comment by anthonypartsconnect** [comment]
Sagar, Client says we are okay for now.  Thank you for helping on this.
