### ISSUE TITLE
AERA MMS Dues Processing Edit Required

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#73]
@SagarPC 
Client has another edit needed on a closed batch.  
Please update 9-7-18kt entry #4 highlighted in attachment. They listed "reg type" as "membership" and it should be "Prosis Pro". 
Thanks - Anthony 
![dues processing edit](https://user-images.githubusercontent.com/39140696/45401217-7ee71d00-b604-11e8-89d7-03beca5bec61.png)

**Comment by SagarPC** [comment]
@anthonypartsconnect : I have updated the highlighted record.

![image](https://user-images.githubusercontent.com/31076567/45404670-80a0f700-b67d-11e8-9083-2be33306c5f8.png)

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.
