### ISSUE TITLE
Bug on AERA Demo Signup

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#75]
@SagarPC 
When client tried signing up for the Demo to test issue in link below (email smtp), they keep getting the attached/message.
https://github.com/stellaballa/AERA/issues/74 
 
Please have a look.  I will create a ticket for VCS too. 

<img width="1038" alt="screen shot 2018-09-19 at 4 21 34 pm" src="https://user-images.githubusercontent.com/39140696/45787050-2200ed80-bc28-11e8-92d8-4017cab8d24c.png">

Please have look. Thank, Anthony

**Comment by SagarPC** [comment]
@anthonypartsconnect : I looked into this issue and make it resolved. There is one setting missing on the server for the Demo program and now it's done.

I checked and email sending function working properly.

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.
