### ISSUE TITLE
Clean Up Prospect List

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#76]
@SagarPC 
![image001 3](https://user-images.githubusercontent.com/39140696/45831821-2aebd080-bcb5-11e8-9800-2396b2194ffd.png)

Can you please remove all the testing records AERA did from the Prospect tab (See attachment - all records highlighted in blue).
Thanks!--Anthony

**Comment by SagarPC** [comment]
@anthonypartsconnect :  We removed all highlighted user from the Prospect tab.

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.
