### ISSUE TITLE
Website Performance

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#77]
@SagarPC 

AERA informed us that both Prosis Pro and MMS were very slow this morning.  
VCS says there is nothing showing a server space issue.  Can you look into the performance?
Thanks - Anthony 

Here is original email from AERA:
_I am checking to see if there is any work being done to the Prosis Pro or MMS websites that would affect performance. This morning it seemed to be very slow in response when searching within Prosis Pro and even queuing a tech call in MMS. I have checked with Cody at VCS and he did look at the servers and there was nothing alarming to think it was a server space issue.  I know there was some work being done in regards to demo users this morning I believe and just want to see if that would have any effect on the other websites._

**Comment by SagarPC** [comment]
@anthonypartsconnect 
I looked into this issue and notice Shadow Backup process affecting server speed. I looked into the server log an found below things. 

Shadow Backup process started at 6:01 PM Central Time (CT).
![shadow_backup_working](https://user-images.githubusercontent.com/31076567/45870525-b7c38680-bda8-11e8-9d84-66bf7529dc9a.png)

SQL facing issue with backup at 6:08 PM Central Time (CT) and onward.
![error_in_sql_for_backup](https://user-images.githubusercontent.com/31076567/45870522-b72af000-bda8-11e8-882c-bc5ffe924624.png)

We not installed this Shadow Backup scheduler on the server so we need to ask AERA about this program.
