### ISSUE TITLE
CMS Prosis Pro -- Report on Pixel Banner

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#78]
@SagarPC 

Sagar, Client shared this note with us this morning, can you look into it and have it corrected very soon for Steve?  He needs to have the reports available for an executive board meeting coming up. 

Email from Steve: 

"HI Stella,
I am trying to run the report on the “Pixel Banner” which shows the number of impressions, clicks etc. for our Board meeting that we are having next week. I am going to Export Data within CMS and on the far right, clicking the button named “Pixel Banner” I think we started the program back in April so I picked the dates of 5/1/18 to 9/30/18. When I go to export the report, I am getting the following error message:

![image001 4](https://user-images.githubusercontent.com/39140696/46309685-e80de080-c571-11e8-8cb0-b91b842b34b9.png)

Can you please look into this and see what the issue is so I can run the report? I tried it on Chrome & Edge, same result.

Thank you,
Steve Fox

**Comment by SagarPC** [comment]
@anthonypartsconnect: We fixed this issue and now it's working fine on Live. Please ask the client to check our update.

**Comment by anthonypartsconnect** [comment]
Sagar, I let Steve know by email that you resolved the issue. 
Thanks
