### ISSUE TITLE
MMS Dues Batch Correction - 10-10-18kt Monthly Credit Cards 

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#79]
@SagarPC 

Can you please change IDs for a couple of entries in dues batch 10-10-18kt Monthly Credit Cards.
Please change the 2 entries from ID#39759 to ID#39789 please.  They are both highlighted in screenshot.  

 
![image001 5](https://user-images.githubusercontent.com/39140696/46886719-8ae71a00-ce10-11e8-991d-e1043a1616d0.png)

**Comment by SagarPC** [comment]
@anthonypartsconnect : I have updated member number for the batch "10-10-18kt Monthly Credit Cards" as requested.

Please send an update to the client.

**Comment by anthonypartsconnect** [comment]
Thanks Sagar!
