### ISSUE TITLE
MMS and Prosis Pro Security 

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#80]
@SagarPC 

Steve noticed security was missing from a few of their addresses.   First example below is from MMS and the second from Prosis Pro. From what he explained is also showing up on the Online Training as well.

Steve is starting with us and then will reach out to VCS if needed. 

<img width="487" alt="screen shot 2018-10-22 at 12 56 00 pm" src="https://user-images.githubusercontent.com/39140696/47315586-e0ce7580-d5f9-11e8-81ea-081f38005811.png">

Thanks. Anthony

**Comment by SagarPC** [comment]
@anthonypartsconnect :

We only got the SSL for the "Prosis Pro" https://www.prosispro.com/

We need SSL for the below website as well.

AERA EDU
http://www.aeraedu.com/
http://api.aeraedu.com

AERA MMS
Currently, it's working with the IP.  It's better to purchase domain first and then SSL for that domain.
http://71.13.159.202/aeramms/login.aspx

**Comment by stellaballa** [comment]
@SagarPC  
for prosispro.com please redirect all http tp https ASAP.
Stella

![screen shot 2018-10-23 at 9 32 43 am](https://user-images.githubusercontent.com/30122790/47376333-2e54ec00-d6a7-11e8-87db-94d255b2b4aa.png)

**Comment by anthonypartsconnect** [comment]
Sagar, 

1) Prosis Pro
so we need to redirect prosispro to https: https://www.prosispro.com/. Per Stella's comment.  

2) AERA EDU
We will request ssl for the following and Cc you on communication to AERA and VCS. 
AERA EDU
http://www.aeraedu.com/
http://api.aeraedu.com

3) MMS
Stella informed AERA They need to purchase domain first and then SSL for that domain. 


<img width="1391" alt="screen shot 2018-10-23 at 9 37 48 am" src="https://user-images.githubusercontent.com/39140696/47376407-66f4c580-d6a7-11e8-8876-0be217b5f056.png">

**Comment by SagarPC** [comment]
Prosis Pro
so we need to redirect prosispro to https: https://www.prosispro.com/. Per Stella's comment.
=> It's done.
