### ISSUE TITLE
Tutorial Videos Link Not working

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#81]
HI Stella,

 **@SagarPC** 
Client is having some issues in loading the tutorial videos and has included a few screen shots of his computer and the messages he is getting. Before, client did not think he had to go to YouTube to watch the videos, they would just open up and play.  

**First attachment is on Chrome:**
<img width="504" alt="screen shot 2018-10-22 at 1 03 14 pm" src="https://user-images.githubusercontent.com/39140696/47316012-ed070280-d5fa-11e8-861d-f7606249011b.png">

Second attachment is on Explorer/Edge.
<img width="592" alt="screen shot 2018-10-22 at 1 03 21 pm" src="https://user-images.githubusercontent.com/39140696/47316058-0c059480-d5fb-11e8-80a6-a4e3801b808c.png">

**Then, this last error appeared when client tried to download them.** 
<img width="849" alt="screen shot 2018-10-22 at 1 03 35 pm" src="https://user-images.githubusercontent.com/39140696/47316066-14f66600-d5fb-11e8-9fd6-6ce35811eef8.png">

Thanks!!

**Comment by SagarPC** [comment]
@anthonypartsconnect : 

We fixed the issue related to Google Chrom and FireFox. Now it's working fine on live. Please check and confirm our update.

https://prosispro.com/tutorials.aspx

**Comment by anthonypartsconnect** [comment]
Thanks Sagar.  Steve confirmed the vid tutorials are working fine on chrome and firefox.  Did you address the third part, which was the youtube download. Thanks.

**Comment by SagarPC** [comment]
@anthonypartsconnect : there is no download function available on Prosis pro. Please do log-in and check if you could see the download function. There is only watch online option.
