### ISSUE TITLE
MMS- Conference Tab "Delete All Attendees" Button Does Not Work

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERA#82]
@SagarPC Sagar, 
Client informed us that the "Delete All Attendees" under conference section of MMS does not work.  
Can you look into this please.  

Thank you. 

![image001 7](https://user-images.githubusercontent.com/39140696/48373619-32a57100-e677-11e8-8f19-463542e08808.png)

**Comment by SagarPC** [comment]
@anthonypartsconnect: It's uploaded on stage and working fine. Please check and confirm so we can move same on live.

**Comment by stellaballa** [comment]
@SagarPC this is working on staging, please move code to live site and test.
