### ISSUE TITLE
Printing Spec

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#84]
When we print out of Prosis Pro notes page, Dave had one that did not print the wording, just the heading. Looks like if there is a pdf attachment, the note doesn't get printed. 
![image001 png 01d49867 dcb1a4b0](https://user-images.githubusercontent.com/30122790/50530683-d1b1eb00-0ab4-11e9-9b87-c39573610d75.png)

**Comment by SagarPC** [comment]
@stellaballa I print our same application form the production and getting attached PDF file on print. Please suggest which change required in this.

[CATERPILLAR-C15-12-31-2018-288.pdf](https://github.com/stellaballa/AERA/files/2718271/CATERPILLAR-C15-12-31-2018-288.pdf)

**Comment by stellaballa** [comment]
@stevefox3781 Can you give us more information on Dave's computer and browser?

**Comment by stevefox3781** [comment]
@stellaballa - I had Dave try it again as did I with a engine with notes and a PDF file in the Notes/Process tab and seems to be working fine. 

Sorry for the delay in getting back to you on this, slipped my mind from the holiday.

**Comment by stellaballa** [comment]
Thanks @stevefox3781  I will close this for now.
