### ISSUE TITLE
Adding Diagram To TB

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#85]
Dave was trying to add a diagram to a technical bulletin and is getting the following error message. He is using IE on Windows 10. I tried it on my screen and the same error came up. The TB number is 2240 and I have also attatched the diagram we are trying to add.

Any questions, let me know. 

![error message](https://user-images.githubusercontent.com/26387391/50844283-0e40da80-1330-11e9-9d94-212775ffa19b.jpg)

![tb2240](https://user-images.githubusercontent.com/26387391/50844375-39c3c500-1330-11e9-89dd-616eb227f4b0.jpg)

**Comment by SagarPC** [comment]
It's resolved on stage and doing testing on stage. We will update on live asap.

**Comment by SagarPC** [comment]
We fixed this access issue on live, please confirm our update.

**Comment by stellaballa** [comment]
@stevefox3781  please check

**Comment by stevefox3781** [comment]
All looks good.
