### ISSUE TITLE
Notes format changes after adding PDF File

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#86]
Dave added a PDF file to the Notes/Process tab and the format of the note changed on the user side, but not on the CMS side. The CMS side is how the note should look on the user side. I have included a screen shot of both. 

Any questions, let me know. 

![cms screen shot](https://user-images.githubusercontent.com/26387391/50844588-a4750080-1330-11e9-8cec-00d058119892.jpg)

![pp screen shot](https://user-images.githubusercontent.com/26387391/50844617-b787d080-1330-11e9-99d6-7edbb6ef4924.jpg)

**Comment by SagarPC** [comment]
We fixed the format issue on live. Please confirm our update.

**Comment by stellaballa** [comment]
@stevefox3781 please check.

**Comment by stevefox3781** [comment]
Looks good.
