### ISSUE TITLE
Engine Not Showing Up

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#87]
Under Toyota if you look up under engine code a 1JZGTE, the engine does not show up - see figure below. If you take that out of the search criteria and look up a Toyota 2.5L engine, the engine shows up. Can you please look into why the engine is not showing up if you look under the engine code. 

Any questions, let me know. 

![image](https://user-images.githubusercontent.com/26387391/53019937-80bad500-341b-11e9-9540-b999a7027f00.png)

![image](https://user-images.githubusercontent.com/26387391/53019992-9cbe7680-341b-11e9-8894-f618d44c33bc.png)

**Comment by SagarPC** [comment]
@stevefox3781  We fixed this issue and now search with "Engine Code" is working fine for "1JZGTE" code.

Currently, there is 2 engine with the same detail, please look into this.

![image](https://user-images.githubusercontent.com/31076567/53092553-100ada00-353b-11e9-8e3b-eced63a7e5b4.png)

**Comment by stevefox3781** [comment]
It is working -- thank you. Could you please delete one of them, it looks like someone copied the engine trying to make it show up.

**Comment by SagarPC** [comment]
@stevefox3781 removed one engine.

**Comment by stevefox3781** [comment]
Thank you!!!!
