### ISSUE TITLE
MMS-adding account to Prosis Pro

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#88]
Add Accounts works good however, the number of accounts you add should be limited:
if 30 day trial or single user - 1 login to account
Multi - 2-10
Enterprise - 11+

if you try to add account and they have reached their limit, a box should come up saying
"User has exceeded Login Limit"

as you can see, i am a single user and have added 3 logins now.
![image](https://user-images.githubusercontent.com/26387044/55182070-fde41300-515a-11e9-89d1-6ba3a0995440.png)

**Comment by SagarPC** [comment]
@kbt1 We added a limit to create a number of Prosis Pro user based on account type as requested and uploaded on stage.

**Comment by kbt1** [comment]
works good.
