### ISSUE TITLE
Tech Call - Online Training

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#89]
Going over the changes to the Tech Call system, we noticed that Online Training was not added after timing. 

![image](https://user-images.githubusercontent.com/26387391/55722615-638e9580-59cc-11e9-9b53-b137057fa3a9.png)

**Comment by SagarPC** [comment]
@stevefox3781  We added "Online Training" under "Tech Call" dropdown list. Please see below image. 

![1114045642148248 lsYXEmRRnHYV0rL8KlPt_height640](https://user-images.githubusercontent.com/31076567/55724918-0c1f1280-5a2a-11e9-8c60-df6d975afa23.png)

Please let us know if we need to remove from "Tech Call" and add under "Section".

**Comment by stevefox3781** [comment]
Oops!!! Sorry about that, did not look in that location. my bad.
