### ISSUE TITLE
Prosis Pro

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#9]
Hi Stella
Steve said you had fixed the error message "You are already logged in" if
they lose internet or close the browser and dont "Log Out"
It doesnt seem to be working, I have gotten 4 calls in 2 days regarding this issue.

**Comment by stellaballa** [comment]
Thanks Karen, I will look into it.

**Comment by SagarPC** [comment]
We have looked into this and notice this issue exist with IE and FireFox browser it was working fine with Chrome.

We have taken action and resolved this issue in all browser like IE, Chrome, FireFox.

So now when user close the browser it will be automatically considered as logout user. This automatic process will take minimum 0.5 min to logout user.

**Comment by kbt1** [comment]
Thank you.

**Comment by kbt1** [comment]
Hi Stella
I have had a few calls from members stating they are still getting locked out of Prosis.
the member i just spoke to has gotten locked out 3 times in the past week and he is using Firefox.
Not sure the reset function is working that has been implemented.

**Comment by stellaballa** [comment]
@kbt1 We will look into it. Did this member just got locked out this morning?

**Comment by kbt1** [comment]
yes he got locked out this morning and yesterday
this is a member that i have told to click on sign out and he doesnt want to listen to me and closes the browser. he complains about this all the time.

**Comment by stellaballa** [comment]
@kbt1 Can you give us his login information, we will look into it. If it's only this member having the issue, the problem could be on his side. But please let us know if there are other members calling about the same thing today.

**Comment by kbt1** [comment]
User name: Billk
Password: 84Riviera
Using Fire Fox


keep in mind, he is probably logged in right now. 
i had 2 other members say they were locked out today but that could have been from the weekend.
I will keep track if more calls come in.

**Comment by kbt1** [comment]
Hi Stella
I have had 3 calls from members that were last logged in on 8-6-17 and they sign out and today they are locked out.

**Comment by stellaballa** [comment]
@SagarPC Can we look into all the users who hasn't been login since we did this update, and reset their account? Do you think this could solve the problem?

**Comment by kbt1** [comment]
That could be a good start.

**Comment by kbt1** [comment]
Stella
just spoke to a member that clicks on sign out and he was in yesterday and locked out today.
i reset his account and he can get back in again.

**Comment by stellaballa** [comment]
@kbt1 can you give me this member account info?

**Comment by kbt1** [comment]
Login: meadeautomotive
Password: 3159237700
i think he is using IE browser.

**Comment by kbt1** [comment]
another user, he logged in today, let the computer sit idle for 5 minutes and when he went back to use Prosis Pro, it had signed him out and he was locked out. I just reset his account.
Login: stampsauto
Password: 91mustang

**Comment by stellaballa** [comment]
thanks @kbt1 
We will look into it over the weekend.

**Comment by kbt1** [comment]
any info on this issue? I came in monday morning with 4 emails from members that were locked out over the weekend.

**Comment by SagarPC** [comment]
@kbt1 : We have looked in more detail over weekend but did not get any cause but I have one thought as below. 

if the member gets the message "You are already logged in". We can show one button and they have to click on it and it resets their account. This process will reset they account from they end and user can able to continue. 

Please let us know if we can go with this process.

**Comment by kbt1** [comment]
Yes, I believe if you add the "Logout" button when they get that message, it will help.

when they get the message, "You are already logged in", a new message should pop up saying 
Click on "Logout" to reset your account.

**Comment by SagarPC** [comment]
@kbt1 : We have added function to reset account and that message will show-up when you will get "You are already logged in" message. 

Please see below image for reference.

![resetaccount](https://user-images.githubusercontent.com/31076567/30321590-40a28f56-97d4-11e7-8306-1c0748968cfd.png)

**Comment by kbt1** [comment]
i will let you know if this works.

**Comment by kbt1** [comment]
Reset your account WORKS!!!!!! 
Can you add the following because a member wasnt sure what to do:
"You have already logged in, please click on Reset your account"

**Comment by SagarPC** [comment]
We have done with this suggested change and uploaded on production.

Please refer below image.
![resetaccount_new message_1](https://user-images.githubusercontent.com/31076567/30378789-ff247b78-98b1-11e7-970c-61b4e27797fa.png)

**Comment by kbt1** [comment]
Looks good.
