### ISSUE TITLE
Tech Bulletin Editor

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#90]
Is it possible that when we copy an paste a tech bulletin from Word that it copies the images in the tech bulletin or do we need to add the images separately. If you need more clarification on this let me know.

**Comment by stellaballa** [comment]
@stevefox3781  we can't copy paste images from a word doc to a web editor. Unless the image is an URL and it's hosting somewhere already. Let me know if this answer your question.

**Comment by stevefox3781** [comment]
OK thanks for the explanation. That is what I was thinking but I was asked to check.
