### ISSUE TITLE
Editing Tech Bulletin

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#91]
This may be something different but we did find this in the CMS. When you go to edit a current tech bulletin, we did not see an spot to select the "Catagory" for the TB. Maybe we missed it and if so please let us know where that is.

**Comment by stellaballa** [comment]
Hi @stevefox3781  the "category" is only available when you create a new bulletin, once the bulletin has been created, you can't change the category. Let us know if you want to add the ability to edit the category.

**Comment by SagarPC** [comment]
@stevefox3781  We added function to edit category in CMS.

![image](https://user-images.githubusercontent.com/31076567/55804140-5e7b3480-5af9-11e9-866d-da5be1cff025.png)

**Comment by stevefox3781** [comment]
Looks good.
