### ISSUE TITLE
Remove Column in Tech Bulletin List

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#93]
The column to the far left can be removed - the number listing 1-13 is the one I am referring to. We just need the TB number and the title to be listed. 

[TB Title List.pdf](https://github.com/stellaballa/AERA/files/3054205/TB.Title.List.pdf)

**Comment by SagarPC** [comment]
We updated logic to display TB# and remove the sequence number column. Please see below image

![image](https://user-images.githubusercontent.com/31076567/55804509-07299400-5afa-11e9-977c-785c5ea89cd2.png)

**Comment by stevefox3781** [comment]
Looks good to me.
