### ISSUE TITLE
MMS Login Issue

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERA#94]
I have an AERA lap top with a Windows 7 professional -  64 bit operating system and it is the only computer that won't allow me to login into MMS. I have had Mark from VCS log into my computer to try and fix it and he has been unsuccessful. I have attached a screen shot of the error screen that I get when trying to login. I have also tried both Chrome and IE browsers with the same result.

![Screenshot_1](https://user-images.githubusercontent.com/26470619/56148596-43cd1380-5f70-11e9-87e7-96dceca23e41.png)

Thanks
Rob

**Comment by stevefox3781** [comment]
This is the repsonse from Stella: I think Rob’s issue is because the IP restriction that VCS put in after the security bridge. He will have to let them know his IP, I assume he is working out of Canada, maybe they didn’t have the info? Steve will start a ticket with VCS regarding this.

**Comment by stevefox3781** [comment]
This issue has been resolved. It seems as the link Rob was working with was broken. Emailed a new link and works just fine.
