### ISSUE TITLE
Update Wording on Invoices

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#96]
I have made some changes to the invoice wording. The document is attached. At the top of each page is what the invoice is.
Anything Highlighted Yellow are changes. Do not highlight on the actual invoice.
There are some items I have in Red Print, please keep them in Red.
If you have any questions, let me know. When done, I can look them over before they go live.

Thanks!
karen
[Update Wording for MMS Invoicing.docx](https://github.com/stellaballa/AERA/files/3112870/Update.Wording.for.MMS.Invoicing.docx)

**Comment by SagarPC** [comment]
@kbt1 We updated wording on Invoices as you suggested.

**Comment by kbt1** [comment]
can you make this a Red Bold Font anywhere it is listed.
 **Please be sure to mail payment to current address**
everything else looks good.

**Comment by SagarPC** [comment]
@kbt1  updated as you requested. please refer below image

![image](https://user-images.githubusercontent.com/31076567/56743154-ace43080-6793-11e9-9fa1-eb78fac8cd73.png)

**Comment by kbt1** [comment]
that is perfect.
thank you!

add it to the live program so its easier to see if there are any issues but it all looks good.

**Comment by SagarPC** [comment]
@kbt1  We already uploaded this to the live. Please check and confirm our update on live.

**Comment by kbt1** [comment]
looks good!
