### ISSUE TITLE
Specification Request Emails Not Showing Up

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#97]
We just received 5 emails for Specification Request from the same member (15811) with email address alfred.castillo@advance-auto.com and none of them showed up in the Specification Request Data. Can someone look into this for us please. If you need the emails I can forward them to you. I have attached what info I could below. Also they sent it 5 times so wondering if the reply may not be working properly also. The techs really like this feature!!!

From	Subject	Received	Size	Categories	
alfred.castillo@advance-auto.com	Engine Specification Request	11:56 AM	62 KB		
From	Subject	Received	Size	Categories	
alfred.castillo@advance-auto.com	Engine Specification Request	11:58 AM	62 KB		
From	Subject	Received	Size	Categories	
alfred.castillo@advance-auto.com	Engine Specification Request	11:59 AM	62 KB	
From	Subject	Received	Size	Categories	
alfred.castillo@advance-auto.com	Engine Specification Request	11:59 AM	62 KB	
From	Subject	Received	Size	Categories	
alfred.castillo@advance-auto.com	Engine Specification Request	11:59 AM	62 KB

**Comment by stellaballa** [comment]
@stevefox3781  we will look into this. @SagarPC

**Comment by SagarPC** [comment]
@stevefox3781  I tried with my Prosis Pro login and send a blank request without fill other information and it's submitted, because we only required email and first name to submit a request.

I checked inside AERA MMS under "Engine Spec." tab to confirm my submitted request and it's working.

![image](https://user-images.githubusercontent.com/31076567/56958149-1b940600-6b67-11e9-9729-f2587db4b358.png)

**Comment by stevefox3781** [comment]
@SagarPC Sounds good. Thank you for looking into this. We did have another request this morning and I checked and was in there along with yours. 

Also can we clear out all the ones in the Engine Request Data tab? I think we need to start fresh and I did not see a place for us to delete them on our end. 

Thank you,

**Comment by SagarPC** [comment]
@stevefox3781  I removed that testing record.

**Comment by stevefox3781** [comment]
Got a specification request just now this that is going in the Engine Request Data tab when it should be in the Specification Request Data tab. I think there is some confusion on the user end. Instead of hitting the specification request in the top right hand corner to get information, they are clicking on the Request for Engine red button. For now can we have both of those locations (spec & engine request) go to the Specification Request Data? 

![image](https://user-images.githubusercontent.com/26387391/56980960-571cd900-6b43-11e9-82bf-23360194008a.png)

![image](https://user-images.githubusercontent.com/26387391/56980999-6865e580-6b43-11e9-9c91-877db4b52c04.png)

![image](https://user-images.githubusercontent.com/26387391/56981015-71ef4d80-6b43-11e9-8453-b55630cdac38.png)

**Comment by stevefox3781** [comment]
Also can we delete the 56 records under the Engine Request Data tab - we do not need those as of today.

**Comment by stellaballa** [comment]
@stevefox3781  we will address this today.

**Comment by SagarPC** [comment]
@stevefox3781  We removed "Engine Specification" tab from the AERA MMS and now all the request will be showing "Specification Request Data" tab.

We uploaded this change to the live site.
