### ISSUE TITLE
Missing Technical Bulletins

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#98]
Got a note from Dave this morning regarding some missing TB's as follows: 

I was adding the TB2766 that disappeared last Friday and go this error message.

![Missing TB Error](https://user-images.githubusercontent.com/26387391/57236262-45777d80-6fea-11e9-8e18-a299124bc1bd.png)

I then found another bulletin that is missing, TB2768, I was trying to figure out what Date the TB2766 was and ran across an additional missing one, I’m wondering if, since it’s all number in sequence, if Stella could point out the “missing a number” and give us a list of numbers missing?

**Comment by stellaballa** [comment]
@stevefox3781  we will look into this.

**Comment by SagarPC** [comment]
Please find attached file for the list of missing number with deleted date and time. Please let me know if any other information required.

[missing_bulletins_number.xlsx](https://github.com/stellaballa/AERA/files/3149260/missing_bulletins_number.xlsx)

**Comment by stevefox3781** [comment]
All good.
